Rem
Rem emaas_savedsearch_seed_data.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savedsearch_seed_data.sql
Rem
Rem    DESCRIPTION
Rem      EM Analytics framework seed data sql file.
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    miayu       04/20/15 - seed data for OOB categories and OOB folders only
Rem    miayu       08/28/14 - Make demo folder/searches deletable
Rem    miayu       08/22/14 - Introduce schema version
Rem    miayu       06/06/14 - Reserve some permanent category/folder ID(s) for internal integrator
Rem    kuabhina    12/13/13 - Created
Rem


DEFINE TENANT_ID = '&1'
DECLARE
V_FOLDER_ID					 NUMBER(38,0)          ;
V_NAME						 VARCHAR2(64 BYTE)     ;
V_PARENT_ID					 NUMBER(38,0)          ;
V_DESCRIPTION				 VARCHAR2(256 BYTE)    ;
V_CREATION_DATE				 TIMESTAMP(6)          ;
V_OWNER						 VARCHAR2(64 BYTE)     ;
V_LAST_MODIFICATION_DATE	 TIMESTAMP(6)          ;
V_LAST_MODIFIED_BY			 VARCHAR2(64 BYTE)     ;
V_NAME_NLSID				 VARCHAR2(256 BYTE)    ;
V_NAME_SUBSYSTEM			 VARCHAR2(64 BYTE)     ;
V_DESCRIPTION_NLSID			 VARCHAR2(256 BYTE)    ;
V_DESCRIPTION_SUBSYSTEM		 VARCHAR2(64 BYTE)     ;
V_SYSTEM_FOLDER				 NUMBER(1,0)           ;
V_EM_PLUGIN_ID				 VARCHAR2(64 BYTE)     ;
V_UI_HIDDEN					 NUMBER(1,0)           ;
V_DELETED					 NUMBER(38,0)          ;
V_TENANT_ID					 NUMBER(38,0)          ;

V_CATEGORY_ID                NUMBER(38,0);
V_DEFAULT_FOLDER_ID          NUMBER(38,0);
V_PROVIDER_NAME              VARCHAR2(64 BYTE);
V_PROVIDER_VERSION           VARCHAR2(64 BYTE);
V_PROVIDER_ASSET_ROOT        VARCHAR2(64 BYTE);


BEGIN
--Rem SEED DATA FOR ROOT FOLDER OF EACH APP

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (1,'All Searches',null,'Search Console Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_SEARCHES_NAME','EMANALYTICS','ALL_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
 V_FOLDER_ID				:=   1;
 V_NAME						:=   'All Searches';
 V_PARENT_ID				:=   null;
 V_DESCRIPTION				:=   'Search Console Root Folder';
 V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 V_OWNER					:=   'ORACLE';
 V_LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 V_LAST_MODIFIED_BY			:=   'ORACLE';
 V_NAME_NLSID				:=   'ALL_SEARCHES_NAME';
 V_NAME_SUBSYSTEM			:=   'EMANALYTICS';
 V_DESCRIPTION_NLSID		:=   'ALL_SEARCHES_DESC';
 V_DESCRIPTION_SUBSYSTEM	:=   'EMANALYTICS';
 V_SYSTEM_FOLDER			:=   1;
 V_EM_PLUGIN_ID				:=   'oracle.sysman.core';
 V_UI_HIDDEN				:=   0;
 V_TENANT_ID				:=   '&TENANT_ID';

 Insert into
 EMS_ANALYTICS_FOLDERS
 (FOLDER_ID,
  NAME,
  PARENT_ID,
  DESCRIPTION,
  CREATION_DATE,
  OWNER,
  LAST_MODIFICATION_DATE,
  LAST_MODIFIED_BY,
  NAME_NLSID,
  NAME_SUBSYSTEM,
  DESCRIPTION_NLSID,
  DESCRIPTION_SUBSYSTEM,
  SYSTEM_FOLDER,
  EM_PLUGIN_ID,
  UI_HIDDEN,
  TENANT_ID)
  values
  (V_FOLDER_ID,
   V_NAME,
   V_PARENT_ID,
   V_DESCRIPTION,
   V_CREATION_DATE,
   V_OWNER,
   V_LAST_MODIFICATION_DATE,
   V_LAST_MODIFIED_BY,
   V_NAME_NLSID,
   V_NAME_SUBSYSTEM,
   V_DESCRIPTION_NLSID,
   V_DESCRIPTION_SUBSYSTEM,
   V_SYSTEM_FOLDER,
   V_EM_PLUGIN_ID,
   V_UI_HIDDEN,
   V_TENANT_ID);
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (2,'Log Analytics Searches',1,'Log Analytics Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_LOG_ANALYTICS_SEARCHES_NAME','EMANALYTICS','ALL_LOG_ANALYTICS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
  V_FOLDER_ID				:=  2;
  V_NAME						:=  'Log Analytics Searches';
  V_PARENT_ID				:=  1;
  V_DESCRIPTION				:=  'Log Analytics Root Folder';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY		:=  'ORACLE';
  V_NAME_NLSID				:=  'ALL_LOG_ANALYTICS_SEARCHES_NAME';
  V_NAME_SUBSYSTEM			:=  'EMANALYTICS';
  V_DESCRIPTION_NLSID		:=  'ALL_LOG_ANALYTICS_SEARCHES_DESC';
  V_DESCRIPTION_SUBSYSTEM	:=  'EMANALYTICS';
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID			:=  'oracle.sysman.core';
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (3,'IT Analytics Searches',1,'IT Analytics Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_IT_ANALYTICS_SEARCHES_NAME','EMANALYTICS','ALL_IT_ANALYTICS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
  V_FOLDER_ID				:=   3;
  V_NAME						:=   'IT Analytics Searches';
  V_PARENT_ID				:=   1;
  V_DESCRIPTION				:=   'IT Analytics Root Folder';
  V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=   'ORACLE';
  V_NAME_NLSID				:=   'ALL_IT_ANALYTICS_SEARCHES_NAME';
  V_NAME_SUBSYSTEM			:=   'EMANALYTICS';
  V_DESCRIPTION_NLSID		:=   'ALL_IT_ANALYTICS_SEARCHES_DESC';
  V_DESCRIPTION_SUBSYSTEM	:=   'EMANALYTICS';
  V_SYSTEM_FOLDER			:=   1;
  V_EM_PLUGIN_ID				:=   'oracle.sysman.core';
  V_UI_HIDDEN				:=   0;
  V_TENANT_ID				:=   '&TENANT_ID';

  Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (4,'Target Analytics Searches',1,'Target Analytics Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_TARGET_ANALYTICS_SEARCHES_NAME','EMANALYTICS','ALL_TARGET_ANALYTICS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
  V_FOLDER_ID				:= 4;
  V_NAME						:= 'Target Analytics Searches';
  V_PARENT_ID				:= 1;
  V_DESCRIPTION				:= 'Target Analytics Root Folder';
  V_CREATION_DATE			:= SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:= SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:= 'ORACLE';
  V_NAME_NLSID				:= 'ALL_TARGET_ANALYTICS_SEARCHES_NAME';
  V_NAME_SUBSYSTEM			:= 'EMANALYTICS';
  V_DESCRIPTION_NLSID		:= 'ALL_TARGET_ANALYTICS_SEARCHES_DESC';
  V_DESCRIPTION_SUBSYSTEM	:= 'EMANALYTICS';
  V_SYSTEM_FOLDER			:= 1;
  V_EM_PLUGIN_ID				:= 'oracle.sysman.core';
  V_UI_HIDDEN				:= 0;
  V_TENANT_ID				:= '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
-- folder id 5 is reserved as root folder for APMCS
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (5,'APMCS Searches',1,'Application Performance Monitoring Cloud Service Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_APMCS_SEARCHES_NAME','EMANALYTICS','ALL_APMCS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
  V_FOLDER_ID				:=  5;
  V_NAME						:=  'APMCS Searches';
  V_PARENT_ID				:=  1;
  V_DESCRIPTION				:=  'Application Performance Monitoring Cloud Service Root Folder';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=  'ORACLE';
  V_NAME_NLSID				:=  'ALL_APMCS_SEARCHES_NAME';
  V_NAME_SUBSYSTEM			:=  'EMANALYTICS';
  V_DESCRIPTION_NLSID		:=  'ALL_APMCS_SEARCHES_DESC';
  V_DESCRIPTION_SUBSYSTEM	:=  'EMANALYTICS';
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID				:=  'oracle.sysman.core';
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';


Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
-- *********************** LA FOLDERS ********************************
-- folder id between 200 - 299 are reserved for Log Analytics
-- LA DATABASE
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (201,'Database',2,'Databases',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=  201;
  V_NAME						:=  'Database';
  V_PARENT_ID				:=  2;
  V_DESCRIPTION				:=  'Databases';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=  'ORACLE';
  V_NAME_NLSID				:=  null;
  V_NAME_SUBSYSTEM			:=  null;
  V_DESCRIPTION_NLSID		:=  null;
  V_DESCRIPTION_SUBSYSTEM	:=  null;
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID				:=  null;
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (206,'Alerts',201,'Searches based on database alert logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=  206;
  V_NAME						:=  'Alerts';
  V_PARENT_ID				:=  201;
  V_DESCRIPTION				:=  'Searches based on database alert logs';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=  'ORACLE';
  V_NAME_NLSID				:=  null;
  V_NAME_SUBSYSTEM			:=  null;
  V_DESCRIPTION_NLSID		:=  null;
  V_DESCRIPTION_SUBSYSTEM	:=  null;
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID				:=  null;
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

-- LA MIDDLEWARE
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (202,'Middleware',2,'Middleware',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=   202;
  V_NAME						:=   'Middleware';
  V_PARENT_ID				:=   2;
  V_DESCRIPTION				:=   'Middleware';
  V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=   'ORACLE';
  V_NAME_NLSID				:=   null;
  V_NAME_SUBSYSTEM			:=   null;
  V_DESCRIPTION_NLSID		:=   null;
  V_DESCRIPTION_SUBSYSTEM	:=   null;
  V_SYSTEM_FOLDER			:=   1;
  V_EM_PLUGIN_ID				:=   null;
  V_UI_HIDDEN				:=   0;
  V_TENANT_ID				:=   '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (207,'Access',202,'Searches based on HTTP request access logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=    207;
  V_NAME						:=    'Access';
  V_PARENT_ID				:=    202;
  V_DESCRIPTION				:=    'Searches based on HTTP request access logs';
  V_CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=    'ORACLE';
  V_NAME_NLSID				:=    null;
  V_NAME_SUBSYSTEM			:=    null;
  V_DESCRIPTION_NLSID		:=    null;
  V_DESCRIPTION_SUBSYSTEM	:=    null;
  V_SYSTEM_FOLDER			:=    1;
  V_EM_PLUGIN_ID				:=    null;
  V_UI_HIDDEN				:=    0;
  V_TENANT_ID				:=    '&TENANT_ID';


Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (208,'Server',202,'Searches based on operational middleware server logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 V_FOLDER_ID				:=     208;
  V_NAME						:=     'Server';
  V_PARENT_ID				:=     202;
  V_DESCRIPTION				:=     'Searches based on operational middleware server logs';
  V_CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=     'ORACLE';
  V_NAME_NLSID				:=     null;
  V_NAME_SUBSYSTEM			:=     null;
  V_DESCRIPTION_NLSID		:=     null;
  V_DESCRIPTION_SUBSYSTEM	:=     null;
  V_SYSTEM_FOLDER			:=     1;
  V_EM_PLUGIN_ID				:=     null;
  V_UI_HIDDEN				:=     0;
  V_TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
-- LA HOST
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (203,'Servers, Storage and Network',2,'Servers, Storage and Network',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=    203;
  V_NAME						:=    'Servers, Storage and Network';
  V_PARENT_ID				:=    2;
  V_DESCRIPTION				:=    'Servers, Storage and Network';
  V_CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=    'ORACLE';
  V_NAME_NLSID				:=    null;
  V_NAME_SUBSYSTEM			:=    null;
  V_DESCRIPTION_NLSID		:=    null;
  V_DESCRIPTION_SUBSYSTEM	:=    null;
  V_SYSTEM_FOLDER			:=    1;
  V_EM_PLUGIN_ID				:=    null;
  V_UI_HIDDEN				:=    0;
  V_TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (209,'Security',203,'Searches based on logs that capture host-level security',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',
--SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=     209;
  V_NAME						:=     'Security';
  V_PARENT_ID				:=     203;
  V_DESCRIPTION				:=     'Searches based on logs that capture host-level security';
  V_CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=     'ORACLE';
  V_NAME_NLSID				:=     null;
  V_NAME_SUBSYSTEM			:=     null;
  V_DESCRIPTION_NLSID		:=     null;
  V_DESCRIPTION_SUBSYSTEM	:=     null;
  V_SYSTEM_FOLDER			:=     1;
  V_EM_PLUGIN_ID				:=     null;
  V_UI_HIDDEN				:=     0;
  V_TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (210,'Lifecycle',203,'Searches based on logs that capture host lifecycle, such as package managers',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',
--SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=     210;
  V_NAME						:=     'Lifecycle';
  V_PARENT_ID				:=     203;
  V_DESCRIPTION				:=     'Searches based on logs that capture host lifecycle,such as package managers';
  V_CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=     'ORACLE';
  V_NAME_NLSID				:=     null;
  V_NAME_SUBSYSTEM			:=     null;
  V_DESCRIPTION_NLSID		:=     null;
  V_DESCRIPTION_SUBSYSTEM	:=     null;
  V_SYSTEM_FOLDER			:=     1;
  V_EM_PLUGIN_ID				:=     null;
  V_UI_HIDDEN				:=     0;
  V_TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
-- LA ENTERPRISE MANAGER
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (205,'Enterprise Manager',2,'Entprise Manager',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=     205;
  V_NAME						:=     'Enterprise Manager';
  V_PARENT_ID				:=     2;
  V_DESCRIPTION				:=     'Entprise Manager';
  V_CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=     'ORACLE';
  V_NAME_NLSID				:=     null;
  V_NAME_SUBSYSTEM			:=     null;
  V_DESCRIPTION_NLSID		:=     null;
  V_DESCRIPTION_SUBSYSTEM	:=     null;
  V_SYSTEM_FOLDER			:=     1;
  V_EM_PLUGIN_ID				:=     null;
  V_UI_HIDDEN				:=     0;
  V_TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (211,'Servers',205,'Searches based on Enterprise Manager server logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=    211;
  V_NAME						:=    'Servers';
  V_PARENT_ID				:=    205;
  V_DESCRIPTION				:=    'Searches based on Enterprise Manager server logs';
  V_CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=    'ORACLE';
  V_NAME_NLSID				:=    null;
  V_NAME_SUBSYSTEM			:=    null;
  V_DESCRIPTION_NLSID		:=    null;
  V_DESCRIPTION_SUBSYSTEM	:=    null;
  V_SYSTEM_FOLDER			:=    1;
  V_EM_PLUGIN_ID				:=    null;
  V_UI_HIDDEN				:=    0;
  V_TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (212,'Agents',205,'Searches based on Enterprise Manager agent logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=    212;
  V_NAME						:=    'Agents';
  V_PARENT_ID				:=    205;
  V_DESCRIPTION				:=    'Searches based on Enterprise Manager agent logs';
  V_CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=    'ORACLE';
  V_NAME_NLSID				:=    null;
  V_NAME_SUBSYSTEM			:=    null;
  V_DESCRIPTION_NLSID		:=    null;
  V_DESCRIPTION_SUBSYSTEM	:=    null;
  V_SYSTEM_FOLDER			:=    1;
  V_EM_PLUGIN_ID				:=    null;
  V_UI_HIDDEN				:=    0;
  V_TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
-- *********************** ITA FOLDERS ********************************
-- folder id between 300 - 399 are reserved for IT Analytics
--NONE

-- *********************** TA FOLDERS ********************************
-- folder id between 400 - 499 are reserved for IT Analytics
--NONE

-- *********************** APM FOLDERS ********************************
-- folder id between 500 - 599 are reserved for APMCS
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (501,'Requests',5,'Request Types Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=    501;
  V_NAME						:=    'Requests';
  V_PARENT_ID				:=    5;
  V_DESCRIPTION				:=    'Request Types Folder';
  V_CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=    'ORACLE';
  V_NAME_NLSID				:=    null;
  V_NAME_SUBSYSTEM			:=    null;
  V_DESCRIPTION_NLSID		:=    null;
  V_DESCRIPTION_SUBSYSTEM	:=    null;
  V_SYSTEM_FOLDER			:=    1;
  V_EM_PLUGIN_ID				:=    null;
  V_UI_HIDDEN				:=    0;
  V_TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (502,'Pages',5,'Page Types Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=   502;
  V_NAME						:=   'Pages';
  V_PARENT_ID				:=   5;
  V_DESCRIPTION				:=   'Page Types Folder';
  V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=   'ORACLE';
  V_NAME_NLSID				:=   null;
  V_NAME_SUBSYSTEM			:=   null;
  V_DESCRIPTION_NLSID		:=   null;
  V_DESCRIPTION_SUBSYSTEM	:=   null;
  V_SYSTEM_FOLDER			:=   1;
  V_EM_PLUGIN_ID				:=   null;
  V_UI_HIDDEN				:=   0;
  V_TENANT_ID				:=   '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (503,'Instances',5,'Instances Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=  503;
  V_NAME						:=  'Instances';
  V_PARENT_ID				:=  5;
  V_DESCRIPTION				:=  'Instances Folder';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=  'ORACLE';
  V_NAME_NLSID				:=  null;
  V_NAME_SUBSYSTEM			:=  null;
  V_DESCRIPTION_NLSID		:=  null;
  V_DESCRIPTION_SUBSYSTEM	:=  null;
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID				:=  null;
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (504,'Agents',5,'Agents Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=   504;
  V_NAME						:=   'Agents';
  V_PARENT_ID				:=   5;
  V_DESCRIPTION				:=   'Agents Folder';
  V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=   'ORACLE';
  V_NAME_NLSID				:=   null;
  V_NAME_SUBSYSTEM			:=   null;
  V_DESCRIPTION_NLSID		:=   null;
  V_DESCRIPTION_SUBSYSTEM	:=   null;
  V_SYSTEM_FOLDER			:=   1;
  V_EM_PLUGIN_ID				:=   null;
  V_UI_HIDDEN				:=   0;
  V_TENANT_ID				:=   '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (505,'App Servers',5,'App Servers Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=   505;
  V_NAME						:=   'App Servers';
  V_PARENT_ID				:=   5;
  V_DESCRIPTION				:=   'App Servers Folder';
  V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=   'ORACLE';
  V_NAME_NLSID				:=   null;
  V_NAME_SUBSYSTEM			:=   null;
  V_DESCRIPTION_NLSID		:=   null;
  V_DESCRIPTION_SUBSYSTEM	:=   null;
  V_SYSTEM_FOLDER			:=   1;
  V_EM_PLUGIN_ID				:=   null;
  V_UI_HIDDEN				:=   0;
  V_TENANT_ID				:=   '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (506,'Ajax Calls',5,'Ajax Calls Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=  506;
  V_NAME						:=  'Ajax Calls';
  V_PARENT_ID				:=  5;
  V_DESCRIPTION				:=  'Ajax Calls Folder';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=  'ORACLE';
  V_NAME_NLSID				:=  null;
  V_NAME_SUBSYSTEM			:=  null;
  V_DESCRIPTION_NLSID		:=  null;
  V_DESCRIPTION_SUBSYSTEM	:=  null;
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID				:=  null;
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (507,'JDBC Calls',5,'JDBC Calls Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
  V_FOLDER_ID				:=  507;
  V_NAME						:=  'JDBC Calls';
  V_PARENT_ID				:=  5;
  V_DESCRIPTION				:=  'JDBC Calls Folder';
  V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_OWNER					:=   'ORACLE';
  V_LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY			:=  'ORACLE';
  V_NAME_NLSID				:=  null;
  V_NAME_SUBSYSTEM			:=  null;
  V_DESCRIPTION_NLSID		:=  null;
  V_DESCRIPTION_SUBSYSTEM	:=  null;
  V_SYSTEM_FOLDER			:=  1;
  V_EM_PLUGIN_ID				:=  null;
  V_UI_HIDDEN				:=  0;
  V_TENANT_ID				:=  '&TENANT_ID';

  Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (V_FOLDER_ID,
  V_NAME,
  V_PARENT_ID,
  V_DESCRIPTION,
  V_CREATION_DATE,
  V_OWNER,
  V_LAST_MODIFICATION_DATE,
  V_LAST_MODIFIED_BY,
  V_NAME_NLSID,
  V_NAME_SUBSYSTEM,
  V_DESCRIPTION_NLSID,
  V_DESCRIPTION_SUBSYSTEM,
  V_SYSTEM_FOLDER,
  V_EM_PLUGIN_ID,
  V_UI_HIDDEN,
  V_TENANT_ID);
--Rem SEED DATA FOR CATEGORY

--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID ,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (1,'Log Analytics','Search Category for Log Analytics','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'LOG_ANALYTICS_CATEGORY_NAME','EMANALYTICS','LOG_ANALYTICS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',2,'LoganService','0.1','assetRoot','&TENANT_ID');
 V_CATEGORY_ID              :=1;
 V_NAME                     :='Log Analytics';
 V_DESCRIPTION              :='Search Category for Log Analytics';
 V_OWNER					:=   'ORACLE';
 V_CREATION_DATE            :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
 V_NAME_NLSID               :='LOG_ANALYTICS_CATEGORY_NAME';
 V_NAME_SUBSYSTEM           :='EMANALYTICS';
 V_DESCRIPTION_NLSID        :='LOG_ANALYTICS_CATEGORY_DESC';
 V_DESCRIPTION_SUBSYSTEM    :='EMANALYTICS';
 V_EM_PLUGIN_ID             :='oracle.sysman.core';
 V_DEFAULT_FOLDER_ID        :=2;
 V_PROVIDER_NAME             :='LoganService';
 V_PROVIDER_VERSION         :='0.1';
 V_PROVIDER_ASSET_ROOT      :='assetRoot';
 V_TENANT_ID                :='&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
V_CATEGORY_ID,
V_NAME,
V_DESCRIPTION,
V_OWNER,
V_CREATION_DATE,
V_NAME_NLSID,
V_NAME_SUBSYSTEM,
V_DESCRIPTION_NLSID,
V_DESCRIPTION_SUBSYSTEM,
V_EM_PLUGIN_ID,
V_DEFAULT_FOLDER_ID,
V_PROVIDER_NAME ,
V_PROVIDER_VERSION,
V_PROVIDER_ASSET_ROOT,
V_TENANT_ID);

--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID ,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (2,'Target Analytics','Search Category for Target Analytics','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'TARGET_ANALYTICS_CATEGORY_NAME','EMANALYTICS','TARGET_ANALYTICS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',4,'TargetAnalytics','1.0','assetRoot','&TENANT_ID');
 V_CATEGORY_ID              := 2;
 V_NAME                     := 'Target Analytics';
 V_DESCRIPTION              := 'Search Category for Target Analytics';
 V_OWNER					:=   'ORACLE';
 V_CREATION_DATE            := SYS_EXTRACT_UTC(SYSTIMESTAMP);
 V_NAME_NLSID               := 'TARGET_ANALYTICS_CATEGORY_NAME';
 V_NAME_SUBSYSTEM           := 'EMANALYTICS';
 V_DESCRIPTION_NLSID        := 'TARGET_ANALYTICS_CATEGORY_DESC';
 V_DESCRIPTION_SUBSYSTEM    := 'EMANALYTICS';
 V_EM_PLUGIN_ID             := 'oracle.sysman.core';
 V_DEFAULT_FOLDER_ID        := 4;
 V_PROVIDER_NAME             := 'TargetAnalytics';
 V_PROVIDER_VERSION         := '1.0';
 V_PROVIDER_ASSET_ROOT      := 'assetRoot';
 V_TENANT_ID                := '&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
V_CATEGORY_ID,
V_NAME,
V_DESCRIPTION,
V_OWNER,
V_CREATION_DATE,
V_NAME_NLSID,
V_NAME_SUBSYSTEM,
V_DESCRIPTION_NLSID,
V_DESCRIPTION_SUBSYSTEM,
V_EM_PLUGIN_ID,
V_DEFAULT_FOLDER_ID,
V_PROVIDER_NAME ,
V_PROVIDER_VERSION,
V_PROVIDER_ASSET_ROOT,
V_TENANT_ID);

--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID ,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (3,'IT Analytics','Search Category for IT Analytics','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'IT_ANALYTICS_CATEGORY_NAME','EMANALYTICS','IT_ANALYTICS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',3,'EmcitasApplications','0.1','assetRoot','&TENANT_ID');
 V_CATEGORY_ID              :=  3;
 V_NAME                     :=  'IT Analytics';
 V_DESCRIPTION              :=  'Search Category for IT Analytics';
 V_OWNER					:=   'ORACLE';
 V_CREATION_DATE            :=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 V_NAME_NLSID               :=  'IT_ANALYTICS_CATEGORY_NAME';
 V_NAME_SUBSYSTEM           :=  'EMANALYTICS';
 V_DESCRIPTION_NLSID        :=  'IT_ANALYTICS_CATEGORY_DESC';
 V_DESCRIPTION_SUBSYSTEM    :=  'EMANALYTICS';
 V_EM_PLUGIN_ID             :=  'oracle.sysman.core';
 V_DEFAULT_FOLDER_ID        :=  3;
 V_PROVIDER_NAME             :=  'EmcitasApplications';
 V_PROVIDER_VERSION         :=  '0.1';
 V_PROVIDER_ASSET_ROOT      :=  'assetRoot';
 V_TENANT_ID                :=  '&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
V_CATEGORY_ID,
V_NAME,
V_DESCRIPTION,
V_OWNER,
V_CREATION_DATE,
V_NAME_NLSID,
V_NAME_SUBSYSTEM,
V_DESCRIPTION_NLSID,
V_DESCRIPTION_SUBSYSTEM,
V_EM_PLUGIN_ID,
V_DEFAULT_FOLDER_ID,
V_PROVIDER_NAME ,
V_PROVIDER_VERSION,
V_PROVIDER_ASSET_ROOT,
V_TENANT_ID);
--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (4,'APMCS','Search Category for Application Performance Monitoring Cloud Service','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'APMCS_CATEGORY_NAME','EMANALYTICS','APMCS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',5,'ApmUI','0.1','home','&TENANT_ID');
 V_CATEGORY_ID              :=   4;
 V_NAME                     :=   'APMCS';
 V_DESCRIPTION              :=   'Search Category for Application Performance Monitoring Cloud Service';
 V_OWNER					:=   'ORACLE';
 V_CREATION_DATE            :=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 V_NAME_NLSID               :=   'APMCS_CATEGORY_NAME';
 V_NAME_SUBSYSTEM           :=   'EMANALYTICS';
 V_DESCRIPTION_NLSID        :=   'APMCS_CATEGORY_DESC';
 V_DESCRIPTION_SUBSYSTEM    :=   'EMANALYTICS';
 V_EM_PLUGIN_ID             :=   'oracle.sysman.core';
 V_DEFAULT_FOLDER_ID        :=   5;
 V_PROVIDER_NAME             :=   'ApmUI';
 V_PROVIDER_VERSION         :=   '0.1';
 V_PROVIDER_ASSET_ROOT      :=   'home';
 V_TENANT_ID                :=   '&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
V_CATEGORY_ID,
V_NAME,
V_DESCRIPTION,
V_OWNER,
V_CREATION_DATE,
V_NAME_NLSID,
V_NAME_SUBSYSTEM,
V_DESCRIPTION_NLSID,
V_DESCRIPTION_SUBSYSTEM,
V_EM_PLUGIN_ID,
V_DEFAULT_FOLDER_ID,
V_PROVIDER_NAME ,
V_PROVIDER_VERSION,
V_PROVIDER_ASSET_ROOT,
V_TENANT_ID);

END;
/
