Rem
Rem emaas_savedsearch_seed_data.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savedsearch_seed_data.sql
Rem
Rem    DESCRIPTION
Rem      EM Analytics framework seed data sql file.
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    miayu       04/20/15 - seed data for OOB categories and OOB folders only
Rem    miayu       08/28/14 - Make demo folder/searches deletable
Rem    miayu       08/22/14 - Introduce schema version
Rem    miayu       06/06/14 - Reserve some permanent category/folder ID(s) for internal integrator
Rem    kuabhina    12/13/13 - Created
Rem


DEFINE TENANT_ID = '&1'
var FOLDER_ID					NUMBER;
var NAME						VARCHAR2;
var PARENT_ID					NUMBER;
var DESCRIPTION					VARCHAR2;
var CREATION_DATE				VARCHAR2;
var OWNER						VARCHAR2;
var LAST_MODIFICATION_DATE		VARCHAR2;
var LAST_MODIFIED_BY			VARCHAR2;
var NAME_NLSID					VARCHAR2
var NAME_SUBSYSTEM				VARCHAR2;
var DESCRIPTION_NLSID			VARCHAR2;
var DESCRIPTION_SUBSYSTEM		VARCHAR2;
var SYSTEM_FOLDER				NUMBER;
var EM_PLUGIN_ID				VARCHAR2;
var UI_HIDDEN					NUMBER;
var DELETED						NUMBER;
var TENANT_ID					NUMBER;

--Rem SEED DATA FOR ROOT FOLDER OF EACH APP

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (1,'All Searches',null,'Search Console Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_SEARCHES_NAME','EMANALYTICS','ALL_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
 exec :FOLDER_ID				:=   1;
 exec :NAME						:=   'All Searches';
 exec :PARENT_ID				:=   null;
 exec :DESCRIPTION				:=   'Search Console Root Folder';
 exec :CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=   'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=   'ORACLE';
 exec :NAME_NLSID				:=   'ALL_SEARCHES_NAME';
 exec :NAME_SUBSYSTEM			:=   'EMANALYTICS';
 exec :DESCRIPTION_NLSID		:=   'ALL_SEARCHES_DESC';
 exec :DESCRIPTION_SUBSYSTEM	:=   'EMANALYTICS';
 exec :SYSTEM_FOLDER			:=   1;
 exec :EM_PLUGIN_ID				:=   'oracle.sysman.core';
 exec :UI_HIDDEN				:=   0;
 exec :TENANT_ID				:=   '&TENANT_ID';

 Insert into
 EMS_ANALYTICS_FOLDERS
 (FOLDER_ID,
  NAME,
  PARENT_ID,
  DESCRIPTION,
  CREATION_DATE,
  OWNER,
  LAST_MODIFICATION_DATE,
  LAST_MODIFIED_BY,
  NAME_NLSID,
  NAME_SUBSYSTEM,
  DESCRIPTION_NLSID,
  DESCRIPTION_SUBSYSTEM,
  SYSTEM_FOLDER,
  EM_PLUGIN_ID,
  UI_HIDDEN,
  TENANT_ID)
  values
  (:FOLDER_ID,
   :NAME,
   :PARENT_ID,
   :DESCRIPTION,
   :CREATION_DATE,
   :OWNER,
   :LAST_MODIFICATION_DATE,
   :LAST_MODIFIED_BY,
   :NAME_NLSID,
   :NAME_SUBSYSTEM,
   :DESCRIPTION_NLSID,
   :DESCRIPTION_SUBSYSTEM,
   :SYSTEM_FOLDER,
   :EM_PLUGIN_ID,
   :UI_HIDDEN,
   :TENANT_ID);
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (2,'Log Analytics Searches',1,'Log Analytics Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_LOG_ANALYTICS_SEARCHES_NAME','EMANALYTICS','ALL_LOG_ANALYTICS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
 exec :FOLDER_ID				:=  2;
 exec :NAME						:=  'Log Analytics Searches';
 exec :PARENT_ID				:=  1;
 exec :DESCRIPTION				:=  'Log Analytics Root Folder';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  'ALL_LOG_ANALYTICS_SEARCHES_NAME';
 exec :NAME_SUBSYSTEM			:=  'EMANALYTICS';
 exec :DESCRIPTION_NLSID		:=  'ALL_LOG_ANALYTICS_SEARCHES_DESC';
 exec :DESCRIPTION_SUBSYSTEM	:=  'EMANALYTICS';
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  'oracle.sysman.core';
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID'

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (3,'IT Analytics Searches',1,'IT Analytics Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_IT_ANALYTICS_SEARCHES_NAME','EMANALYTICS','ALL_IT_ANALYTICS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
 exec :FOLDER_ID				:=   3;
 exec :NAME						:=   'IT Analytics Searches';
 exec :PARENT_ID				:=   1;
 exec :DESCRIPTION				:=   'IT Analytics Root Folder';
 exec :CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=   'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=   'ORACLE';
 exec :NAME_NLSID				:=   'ALL_IT_ANALYTICS_SEARCHES_NAME';
 exec :NAME_SUBSYSTEM			:=   'EMANALYTICS';
 exec :DESCRIPTION_NLSID		:=   'ALL_IT_ANALYTICS_SEARCHES_DESC';
 exec :DESCRIPTION_SUBSYSTEM	:=   'EMANALYTICS';
 exec :SYSTEM_FOLDER			:=   1;
 exec :EM_PLUGIN_ID				:=   'oracle.sysman.core';
 exec :UI_HIDDEN				:=   0;
 exec :TENANT_ID				:=   '&TENANT_ID';

  Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (4,'Target Analytics Searches',1,'Target Analytics Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_TARGET_ANALYTICS_SEARCHES_NAME','EMANALYTICS','ALL_TARGET_ANALYTICS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
 exec :FOLDER_ID				:= 4;
 exec :NAME						:= 'Target Analytics Searches';
 exec :PARENT_ID				:= 1;
 exec :DESCRIPTION				:= 'Target Analytics Root Folder';
 exec :CREATION_DATE			:= SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:= 'ORACLE';
 exec :LAST_MODIFICATION_DATE	:= SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:= 'ORACLE';
 exec :NAME_NLSID				:= 'ALL_TARGET_ANALYTICS_SEARCHES_NAME';
 exec :NAME_SUBSYSTEM			:= 'EMANALYTICS';
 exec :DESCRIPTION_NLSID		:= 'ALL_TARGET_ANALYTICS_SEARCHES_DESC';
 exec :DESCRIPTION_SUBSYSTEM	:= 'EMANALYTICS';
 exec :SYSTEM_FOLDER			:= 1;
 exec :EM_PLUGIN_ID				:= 'oracle.sysman.core';
 exec :UI_HIDDEN				:= 0;
 exec :TENANT_ID				:= '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
-- folder id 5 is reserved as root folder for APMCS
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                          values (5,'APMCS Searches',1,'Application Performance Monitoring Cloud Service Root Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','ALL_APMCS_SEARCHES_NAME','EMANALYTICS','ALL_APMCS_SEARCHES_DESC','EMANALYTICS',1,'oracle.sysman.core',0,'&TENANT_ID');
 exec :FOLDER_ID				:=  5;
 exec :NAME						:=  'APMCS Searches';
 exec :PARENT_ID				:=  1;
 exec :DESCRIPTION				:=  'Application Performance Monitoring Cloud Service Root Folder';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  'ALL_APMCS_SEARCHES_NAME';
 exec :NAME_SUBSYSTEM			:=  'EMANALYTICS';
 exec :DESCRIPTION_NLSID		:=  'ALL_APMCS_SEARCHES_DESC';
 exec :DESCRIPTION_SUBSYSTEM	:=  'EMANALYTICS';
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  'oracle.sysman.core';
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID';


Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
-- *********************** LA FOLDERS ********************************
-- folder id between 200 - 299 are reserved for Log Analytics
-- LA DATABASE 
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (201,'Database',2,'Databases',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=  201;
 exec :NAME						:=  'Database';
 exec :PARENT_ID				:=  2;
 exec :DESCRIPTION				:=  'Databases';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  null;
 exec :NAME_SUBSYSTEM			:=  null;
 exec :DESCRIPTION_NLSID		:=  null;
 exec :DESCRIPTION_SUBSYSTEM	:=  null;
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  null;
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (206,'Alerts',201,'Searches based on database alert logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=  206;
 exec :NAME						:=  'Alerts';
 exec :PARENT_ID				:=  201;
 exec :DESCRIPTION				:=  'Searches based on database alert logs';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  null;
 exec :NAME_SUBSYSTEM			:=  null;
 exec :DESCRIPTION_NLSID		:=  null;
 exec :DESCRIPTION_SUBSYSTEM	:=  null;
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  null;
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

-- LA MIDDLEWARE
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (202,'Middleware',2,'Middleware',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=   202;
 exec :NAME						:=   'Middleware';
 exec :PARENT_ID				:=   2;
 exec :DESCRIPTION				:=   'Middleware';
 exec :CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=   'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=   'ORACLE';
 exec :NAME_NLSID				:=   null;
 exec :NAME_SUBSYSTEM			:=   null;
 exec :DESCRIPTION_NLSID		:=   null;
 exec :DESCRIPTION_SUBSYSTEM	:=   null;
 exec :SYSTEM_FOLDER			:=   1;
 exec :EM_PLUGIN_ID				:=   null;
 exec :UI_HIDDEN				:=   0;
 exec :TENANT_ID				:=   '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (207,'Access',202,'Searches based on HTTP request access logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=    207;
 exec :NAME						:=    'Access';
 exec :PARENT_ID				:=    202;
 exec :DESCRIPTION				:=    'Searches based on HTTP request access logs';
 exec :CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=    'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=    'ORACLE';
 exec :NAME_NLSID				:=    null;
 exec :NAME_SUBSYSTEM			:=    null;
 exec :DESCRIPTION_NLSID		:=    null;
 exec :DESCRIPTION_SUBSYSTEM	:=    null;
 exec :SYSTEM_FOLDER			:=    1;
 exec :EM_PLUGIN_ID				:=    null;
 exec :UI_HIDDEN				:=    0;
 exec :TENANT_ID				:=    '&TENANT_ID';


Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (208,'Server',202,'Searches based on operational middleware server logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
exec :FOLDER_ID				:=     208;
 exec :NAME						:=     'Server';
 exec :PARENT_ID				:=     202;
 exec :DESCRIPTION				:=     'Searches based on operational middleware server logs';
 exec :CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=     'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=     'ORACLE';
 exec :NAME_NLSID				:=     null;
 exec :NAME_SUBSYSTEM			:=     null;
 exec :DESCRIPTION_NLSID		:=     null;
 exec :DESCRIPTION_SUBSYSTEM	:=     null;
 exec :SYSTEM_FOLDER			:=     1;
 exec :EM_PLUGIN_ID				:=     null;
 exec :UI_HIDDEN				:=     0;
 exec :TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
-- LA HOST
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (203,'Servers, Storage and Network',2,'Servers, Storage and Network',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=    203;
 exec :NAME						:=    'Servers, Storage and Network';
 exec :PARENT_ID				:=    2;
 exec :DESCRIPTION				:=    'Servers, Storage and Network';
 exec :CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=    'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=    'ORACLE';
 exec :NAME_NLSID				:=    null;
 exec :NAME_SUBSYSTEM			:=    null;
 exec :DESCRIPTION_NLSID		:=    null;
 exec :DESCRIPTION_SUBSYSTEM	:=    null;
 exec :SYSTEM_FOLDER			:=    1;
 exec :EM_PLUGIN_ID				:=    null;
 exec :UI_HIDDEN				:=    0;
 exec :TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (209,'Security',203,'Searches based on logs that capture host-level security',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',
--SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=     209;
 exec :NAME						:=     'Security';
 exec :PARENT_ID				:=     203;
 exec :DESCRIPTION				:=     'Searches based on logs that capture host-level security';
 exec :CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=     'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=     'ORACLE';
 exec :NAME_NLSID				:=     null;
 exec :NAME_SUBSYSTEM			:=     null;
 exec :DESCRIPTION_NLSID		:=     null;
 exec :DESCRIPTION_SUBSYSTEM	:=     null;
 exec :SYSTEM_FOLDER			:=     1;
 exec :EM_PLUGIN_ID				:=     null;
 exec :UI_HIDDEN				:=     0;
 exec :TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (210,'Lifecycle',203,'Searches based on logs that capture host lifecycle, such as package managers',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',
--SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=     210;
 exec :NAME						:=     'Lifecycle';
 exec :PARENT_ID				:=     203;
 exec :DESCRIPTION				:=     'Searches based on logs that capture host lifecycle,such as package managers';
 exec :CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=     'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=     'ORACLE';
 exec :NAME_NLSID				:=     null;
 exec :NAME_SUBSYSTEM			:=     null;
 exec :DESCRIPTION_NLSID		:=     null;
 exec :DESCRIPTION_SUBSYSTEM	:=     null;
 exec :SYSTEM_FOLDER			:=     1;
 exec :EM_PLUGIN_ID				:=     null;
 exec :UI_HIDDEN				:=     0;
 exec :TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
-- LA ENTERPRISE MANAGER
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (205,'Enterprise Manager',2,'Entprise Manager',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=     205;
 exec :NAME						:=     'Enterprise Manager';
 exec :PARENT_ID				:=     2;
 exec :DESCRIPTION				:=     'Entprise Manager';
 exec :CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=     'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=     'ORACLE';
 exec :NAME_NLSID				:=     null;
 exec :NAME_SUBSYSTEM			:=     null;
 exec :DESCRIPTION_NLSID		:=     null;
 exec :DESCRIPTION_SUBSYSTEM	:=     null;
 exec :SYSTEM_FOLDER			:=     1;
 exec :EM_PLUGIN_ID				:=     null;
 exec :UI_HIDDEN				:=     0;
 exec :TENANT_ID				:=     '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (211,'Servers',205,'Searches based on Enterprise Manager server logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=    211;
 exec :NAME						:=    'Servers';
 exec :PARENT_ID				:=    205;
 exec :DESCRIPTION				:=    'Searches based on Enterprise Manager server logs';
 exec :CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=    'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=    'ORACLE';
 exec :NAME_NLSID				:=    null;
 exec :NAME_SUBSYSTEM			:=    null;
 exec :DESCRIPTION_NLSID		:=    null;
 exec :DESCRIPTION_SUBSYSTEM	:=    null;
 exec :SYSTEM_FOLDER			:=    1;
 exec :EM_PLUGIN_ID				:=    null;
 exec :UI_HIDDEN				:=    0;
 exec :TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--values (212,'Agents',205,'Searches based on Enterprise Manager agent logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=    212;
 exec :NAME						:=    'Agents';
 exec :PARENT_ID				:=    205;
 exec :DESCRIPTION				:=    'Searches based on Enterprise Manager agent logs';
 exec :CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=    'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=    'ORACLE';
 exec :NAME_NLSID				:=    null;
 exec :NAME_SUBSYSTEM			:=    null;
 exec :DESCRIPTION_NLSID		:=    null;
 exec :DESCRIPTION_SUBSYSTEM	:=    null;
 exec :SYSTEM_FOLDER			:=    1;
 exec :EM_PLUGIN_ID				:=    null;
 exec :UI_HIDDEN				:=    0;
 exec :TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
-- *********************** ITA FOLDERS ********************************
-- folder id between 300 - 399 are reserved for IT Analytics
--NONE

-- *********************** TA FOLDERS ********************************
-- folder id between 400 - 499 are reserved for IT Analytics
--NONE

-- *********************** APM FOLDERS ********************************
-- folder id between 500 - 599 are reserved for APMCS
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (501,'Requests',5,'Request Types Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=    501;
 exec :NAME						:=    'Requests';
 exec :PARENT_ID				:=    5;
 exec :DESCRIPTION				:=    'Request Types Folder';
 exec :CREATION_DATE			:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=    'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=    SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=    'ORACLE';
 exec :NAME_NLSID				:=    null;
 exec :NAME_SUBSYSTEM			:=    null;
 exec :DESCRIPTION_NLSID		:=    null;
 exec :DESCRIPTION_SUBSYSTEM	:=    null;
 exec :SYSTEM_FOLDER			:=    1;
 exec :EM_PLUGIN_ID				:=    null;
 exec :UI_HIDDEN				:=    0;
 exec :TENANT_ID				:=    '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (502,'Pages',5,'Page Types Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=   502;
 exec :NAME						:=   'Pages';
 exec :PARENT_ID				:=   5;
 exec :DESCRIPTION				:=   'Page Types Folder';
 exec :CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=   'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=   'ORACLE';
 exec :NAME_NLSID				:=   null;
 exec :NAME_SUBSYSTEM			:=   null;
 exec :DESCRIPTION_NLSID		:=   null;
 exec :DESCRIPTION_SUBSYSTEM	:=   null;
 exec :SYSTEM_FOLDER			:=   1;
 exec :EM_PLUGIN_ID				:=   null;
 exec :UI_HIDDEN				:=   0;
 exec :TENANT_ID				:=   '&TENANT_ID';

Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (503,'Instances',5,'Instances Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=  503;
 exec :NAME						:=  'Instances';
 exec :PARENT_ID				:=  5;
 exec :DESCRIPTION				:=  'Instances Folder';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  null;
 exec :NAME_SUBSYSTEM			:=  null;
 exec :DESCRIPTION_NLSID		:=  null;
 exec :DESCRIPTION_SUBSYSTEM	:=  null;
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  null;
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (504,'Agents',5,'Agents Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=   504;
 exec :NAME						:=   'Agents';
 exec :PARENT_ID				:=   5;
 exec :DESCRIPTION				:=   'Agents Folder';
 exec :CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=   'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=   'ORACLE';
 exec :NAME_NLSID				:=   null;
 exec :NAME_SUBSYSTEM			:=   null;
 exec :DESCRIPTION_NLSID		:=   null;
 exec :DESCRIPTION_SUBSYSTEM	:=   null;
 exec :SYSTEM_FOLDER			:=   1;
 exec :EM_PLUGIN_ID				:=   null;
 exec :UI_HIDDEN				:=   0;
 exec :TENANT_ID				:=   '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (505,'App Servers',5,'App Servers Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=   505;
 exec :NAME						:=   'App Servers';
 exec :PARENT_ID				:=   5;
 exec :DESCRIPTION				:=   'App Servers Folder';
 exec :CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=   'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=   'ORACLE';
 exec :NAME_NLSID				:=   null;
 exec :NAME_SUBSYSTEM			:=   null;
 exec :DESCRIPTION_NLSID		:=   null;
 exec :DESCRIPTION_SUBSYSTEM	:=   null;
 exec :SYSTEM_FOLDER			:=   1;
 exec :EM_PLUGIN_ID				:=   null;
 exec :UI_HIDDEN				:=   0;
 exec :TENANT_ID				:=   '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (506,'Ajax Calls',5,'Ajax Calls Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=  506;
 exec :NAME						:=  'Ajax Calls';
 exec :PARENT_ID				:=  5;
 exec :DESCRIPTION				:=  'Ajax Calls Folder';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  null;
 exec :NAME_SUBSYSTEM			:=  null;
 exec :DESCRIPTION_NLSID		:=  null;
 exec :DESCRIPTION_SUBSYSTEM	:=  null;
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  null;
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID';

 Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);

--Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,TENANT_ID)
--                         values (507,'JDBC Calls',5,'JDBC Calls Folder',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');
 exec :FOLDER_ID				:=  507;
 exec :NAME						:=  'JDBC Calls';
 exec :PARENT_ID				:=  5;
 exec :DESCRIPTION				:=  'JDBC Calls Folder';
 exec :CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :OWNER					:=  'ORACLE';
 exec :LAST_MODIFICATION_DATE	:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
 exec :LAST_MODIFIED_BY			:=  'ORACLE';
 exec :NAME_NLSID				:=  null;
 exec :NAME_SUBSYSTEM			:=  null;
 exec :DESCRIPTION_NLSID		:=  null;
 exec :DESCRIPTION_SUBSYSTEM	:=  null;
 exec :SYSTEM_FOLDER			:=  1;
 exec :EM_PLUGIN_ID				:=  null;
 exec :UI_HIDDEN				:=  0;
 exec :TENANT_ID				:=  '&TENANT_ID';

  Insert into
EMS_ANALYTICS_FOLDERS
(FOLDER_ID,
 NAME,
 PARENT_ID,
 DESCRIPTION,
 CREATION_DATE,
 OWNER,
 LAST_MODIFICATION_DATE,
 LAST_MODIFIED_BY,
 NAME_NLSID,
 NAME_SUBSYSTEM,
 DESCRIPTION_NLSID,
 DESCRIPTION_SUBSYSTEM,
 SYSTEM_FOLDER,
 EM_PLUGIN_ID,
 UI_HIDDEN,
 TENANT_ID)
 values
 (:FOLDER_ID,
  :NAME,
  :PARENT_ID,
  :DESCRIPTION,
  :CREATION_DATE,
  :OWNER,
  :LAST_MODIFICATION_DATE,
  :LAST_MODIFIED_BY,
  :NAME_NLSID,
  :NAME_SUBSYSTEM,
  :DESCRIPTION_NLSID,
  :DESCRIPTION_SUBSYSTEM,
  :SYSTEM_FOLDER,
  :EM_PLUGIN_ID,
  :UI_HIDDEN,
  :TENANT_ID);
--Rem SEED DATA FOR CATEGORY
var CATEGORY_ID                  NUMBER;
var NAME                         VARCHAR2;
var DESCRIPTION                  VARCHAR2;
var OWNER                        VARCHAR2;
var CREATION_DATE                VARCHAR2;
var NAME_NLSID                   VARCHAR2;
var NAME_SUBSYSTEM               VARCHAR2;
var DESCRIPTION_NLSID            VARCHAR2;
var DESCRIPTION_SUBSYSTEM        VARCHAR2;
var EM_PLUGIN_ID                 VARCHAR2;
var DEFAULT_FOLDER_ID            NUMBER;
var PROVIDER_NAME                VARCHAR2;
var PROVIDER_VERSION             VARCHAR2;
var PROVIDER_ASSET_ROOT          VARCHAR2;
var TENANT_ID                    NUMBER;
--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID ,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (1,'Log Analytics','Search Category for Log Analytics','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'LOG_ANALYTICS_CATEGORY_NAME','EMANALYTICS','LOG_ANALYTICS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',2,'LoganService','0.1','assetRoot','&TENANT_ID');
exec :CATEGORY_ID              :=1;
exec :NAME                     :='Log Analytics';
exec :DESCRIPTION              :='Search Category for Log Analytics';
exec :OWNER                    :='ORACLE';
exec :CREATION_DATE            :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
exec :NAME_NLSID               :='LOG_ANALYTICS_CATEGORY_NAME';
exec :NAME_SUBSYSTEM           :='EMANALYTICS';
exec :DESCRIPTION_NLSID        :='LOG_ANALYTICS_CATEGORY_DESC';
exec :DESCRIPTION_SUBSYSTEM    :='EMANALYTICS';
exec :EM_PLUGIN_ID             :='oracle.sysman.core';
exec :DEFAULT_FOLDER_ID        :=2;
exec :PROVIDER_NAME            :='LoganService';
exec :PROVIDER_VERSION         :='0.1';
exec :PROVIDER_ASSET_ROOT      :='assetRoot';
exec :TENANT_ID                :='&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
:CATEGORY_ID,
:NAME,
:DESCRIPTION,
:OWNER,
:CREATION_DATE,
:NAME_NLSID,
:NAME_SUBSYSTEM,
:DESCRIPTION_NLSID,
:DESCRIPTION_SUBSYSTEM,
:EM_PLUGIN_ID,
:DEFAULT_FOLDER_ID,
:PROVIDER_NAME,
:PROVIDER_VERSION,
:PROVIDER_ASSET_ROOT,
:TENANT_ID);

--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID ,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (2,'Target Analytics','Search Category for Target Analytics','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'TARGET_ANALYTICS_CATEGORY_NAME','EMANALYTICS','TARGET_ANALYTICS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',4,'TargetAnalytics','1.0','assetRoot','&TENANT_ID');
exec :CATEGORY_ID              := 2;
exec :NAME                     := 'Target Analytics';
exec :DESCRIPTION              := 'Search Category for Target Analytics';
exec :OWNER                    := 'ORACLE';
exec :CREATION_DATE            := SYS_EXTRACT_UTC(SYSTIMESTAMP);
exec :NAME_NLSID               := 'TARGET_ANALYTICS_CATEGORY_NAME';
exec :NAME_SUBSYSTEM           := 'EMANALYTICS';
exec :DESCRIPTION_NLSID        := 'TARGET_ANALYTICS_CATEGORY_DESC';
exec :DESCRIPTION_SUBSYSTEM    := 'EMANALYTICS';
exec :EM_PLUGIN_ID             := 'oracle.sysman.core';
exec :DEFAULT_FOLDER_ID        := 4;
exec :PROVIDER_NAME            := 'TargetAnalytics';
exec :PROVIDER_VERSION         := '1.0';
exec :PROVIDER_ASSET_ROOT      := 'assetRoot';
exec :TENANT_ID                := '&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
:CATEGORY_ID,
:NAME,
:DESCRIPTION,
:OWNER,
:CREATION_DATE,
:NAME_NLSID,
:NAME_SUBSYSTEM,
:DESCRIPTION_NLSID,
:DESCRIPTION_SUBSYSTEM,
:EM_PLUGIN_ID,
:DEFAULT_FOLDER_ID,
:PROVIDER_NAME,
:PROVIDER_VERSION,
:PROVIDER_ASSET_ROOT,
:TENANT_ID);

--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID ,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (3,'IT Analytics','Search Category for IT Analytics','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'IT_ANALYTICS_CATEGORY_NAME','EMANALYTICS','IT_ANALYTICS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',3,'EmcitasApplications','0.1','assetRoot','&TENANT_ID');
exec :CATEGORY_ID              :=  3;
exec :NAME                     :=  'IT Analytics';
exec :DESCRIPTION              :=  'Search Category for IT Analytics';
exec :OWNER                    :=  'ORACLE';
exec :CREATION_DATE            :=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
exec :NAME_NLSID               :=  'IT_ANALYTICS_CATEGORY_NAME';
exec :NAME_SUBSYSTEM           :=  'EMANALYTICS';
exec :DESCRIPTION_NLSID        :=  'IT_ANALYTICS_CATEGORY_DESC';
exec :DESCRIPTION_SUBSYSTEM    :=  'EMANALYTICS';
exec :EM_PLUGIN_ID             :=  'oracle.sysman.core';
exec :DEFAULT_FOLDER_ID        :=  3;
exec :PROVIDER_NAME            :=  'EmcitasApplications';
exec :PROVIDER_VERSION         :=  '0.1';
exec :PROVIDER_ASSET_ROOT      :=  'assetRoot';
exec :TENANT_ID                :=  '&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
:CATEGORY_ID,
:NAME,
:DESCRIPTION,
:OWNER,
:CREATION_DATE,
:NAME_NLSID,
:NAME_SUBSYSTEM,
:DESCRIPTION_NLSID,
:DESCRIPTION_SUBSYSTEM,
:EM_PLUGIN_ID,
:DEFAULT_FOLDER_ID,
:PROVIDER_NAME,
:PROVIDER_VERSION,
:PROVIDER_ASSET_ROOT,
:TENANT_ID);
--Insert into EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)
--                           values (4,'APMCS','Search Category for Application Performance Monitoring Cloud Service','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'APMCS_CATEGORY_NAME','EMANALYTICS','APMCS_CATEGORY_DESC','EMANALYTICS','oracle.sysman.core',5,'ApmUI','0.1','home','&TENANT_ID');
exec :CATEGORY_ID              :=   4;
exec :NAME                     :=   'APMCS';
exec :DESCRIPTION              :=   'Search Category for Application Performance Monitoring Cloud Service';
exec :OWNER                    :=   'ORACLE';
exec :CREATION_DATE            :=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
exec :NAME_NLSID               :=   'APMCS_CATEGORY_NAME';
exec :NAME_SUBSYSTEM           :=   'EMANALYTICS';
exec :DESCRIPTION_NLSID        :=   'APMCS_CATEGORY_DESC';
exec :DESCRIPTION_SUBSYSTEM    :=   'EMANALYTICS';
exec :EM_PLUGIN_ID             :=   'oracle.sysman.core';
exec :DEFAULT_FOLDER_ID        :=   5;
exec :PROVIDER_NAME            :=   'ApmUI';
exec :PROVIDER_VERSION         :=   '0.1';
exec :PROVIDER_ASSET_ROOT      :=   'home';
exec :TENANT_ID                :=   '&TENANT_ID';

Insert into EMS_ANALYTICS_CATEGORY (
CATEGORY_ID,
NAME,
DESCRIPTION,
OWNER,
CREATION_DATE,
NAME_NLSID,
NAME_SUBSYSTEM,
DESCRIPTION_NLSID,
DESCRIPTION_SUBSYSTEM,
EM_PLUGIN_ID,
DEFAULT_FOLDER_ID,
PROVIDER_NAME,
PROVIDER_VERSION,
PROVIDER_ASSET_ROOT,
TENANT_ID
)values (
:CATEGORY_ID,
:NAME,
:DESCRIPTION,
:OWNER,
:CREATION_DATE,
:NAME_NLSID,
:NAME_SUBSYSTEM,
:DESCRIPTION_NLSID,
:DESCRIPTION_SUBSYSTEM,
:EM_PLUGIN_ID,
:DEFAULT_FOLDER_ID,
:PROVIDER_NAME,
:PROVIDER_VERSION,
:PROVIDER_ASSET_ROOT,
:TENANT_ID);
                           
