Rem
Rem emaas_savesearch_seed_data.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for category and default folder
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    ADUAN       07/05/16 - Add new category for Security Analytics
Rem

DEFINE TENANT_ID ='&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON


DECLARE
  v_count     INTEGER;
  V_TENANT_ID                    NUMBER(38,0);
  V_TID                   NUMBER(38,0) := '&TENANT_ID';
  CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_FOLDERS ORDER BY TENANT_ID;
BEGIN
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;
  --CHECK IF THE DATA IN 'EMS_ANALYTICS_SEARCH' HAS BEEN IMPORTED.
  SELECT count(1) into v_count FROM EMS_ANALYTICS_SEARCH_PARAMS WHERE NAME='WIDGET_SOURCE' AND TENANT_ID = V_TENANT_ID;
  IF (v_count > 0)  THEN
    --MERGE "WIDGET_SOURCE" INTO EMS_ANALYTICS_SEARCH.WIDGET_SOURCE
    DBMS_OUTPUT.PUT_LINE('MERGE ROWS FOR TENANT:'||V_TENANT_ID||' FROM EMS_ANALYTICS_SEARCH_PARAMS TO EMS_ANALYTICS_SEARCH.WIDGET_SOURCE');
    MERGE INTO EMS_ANALYTICS_SEARCH T1 USING (SELECT * FROM EMS_ANALYTICS_SEARCH_PARAMS WHERE NAME='WIDGET_SOURCE') T2 ON (T1.SEARCH_ID=T2.SEARCH_ID AND T1.TENANT_ID=T2.TENANT_ID AND T2.TENANT_ID=V_TENANT_ID) WHEN MATCHED THEN UPDATE SET T1.WIDGET_SOURCE=T2.PARAM_VALUE_STR;
    
    --delete old data in EMS_ANALYTICS_SEARCH_PARAMS
		DBMS_OUTPUT.PUT_LINE('DELETE WIDGET_SOURCE DATA FOR TENANT:'||V_TENANT_ID||' EMS_ANALYTICS_SEARCH_PARAMS TABLE');
		DELETE FROM EMS_ANALYTICS_SEARCH_PARAMS T1 WHERE T1.NAME ='WIDGET_SOURCE' AND T1.TENANT_ID  =V_TENANT_ID;
        
       --update widget source for integrator created ones
    DBMS_OUTPUT.PUT_LINE('UPDATE WIDGET_SOURCE FOR INTEGRATOR WIDGETS FOR TENANT:'||V_TENANT_ID||'');
    UPDATE EMS_ANALYTICS_SEARCH S SET WIDGET_SOURCE = '1' WHERE S.TENANT_ID = V_TENANT_ID AND S.SEARCH_ID >= 10000 AND S.WIDGET_SOURCE = '0';
  
    DBMS_OUTPUT.PUT_LINE('WIDGET_SOURCE data in EMS_ANALYTICS_SEARCH has been moved successfully!');
  ELSE
    DBMS_OUTPUT.PUT_LINE('WIDGET_SOURCE data in EMS_ANALYTICS_SEARCH has been moved previously, no need to move again.');
  END IF;
  IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  COMMIT;

  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Failed to moving WIDGET_SOURCE data in EMS_ANALYTICS_SEARCH due to '||SQLERRM);
      RAISE;
END;
/
