DEFINE TENANT_ID ='&tenant_id'
DEFINE EMSAAS_SQL_ROOT ='&log_root'
SET SERVEROUTPUT ON
spool '&EMSAAS_SQL_ROOT/oob_widget_verify.log';
DECLARE

ALL_OOB_COUNT NUMBER;
V_SEARCH_NAME  VARCHAR2(64 BYTE);
V_SEARCH_DESC  VARCHAR2(256 BYTE);
V_TENANT_ID NUMBER := '&TENANT_ID';
V_SEARCH_ID NUMBER;
V_SEARCH_PARAMCOUNT NUMBER;
V_CURRENT_TENANT_ID NUMBER;

C_SEARCH_NAME  VARCHAR2(64 BYTE);
C_SEARCH_DESC  VARCHAR2(256 BYTE); 
C_SEARCH_ID NUMBER;
C_SEARCH_EXPECTED_PARAMCOUNT NUMBER;
 CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_SEARCH ORDER BY TENANT_ID;
	
ALL_OOB_COUNT_EXPECTED NUMBER :=45;
SEARCH_NAME_EXPECTED_2028   VARCHAR2(64 BYTE) :='Host Log Trend'                                             ;
SEARCH_NAME_EXPECTED_2029   VARCHAR2(64 BYTE) :='Application Server Log Records'                             ;
SEARCH_NAME_EXPECTED_3079   VARCHAR2(64 BYTE) :='Entity Status'                                              ;
SEARCH_NAME_EXPECTED_3080   VARCHAR2(64 BYTE) :='Entity Count'                                               ;
SEARCH_NAME_EXPECTED_3081   VARCHAR2(64 BYTE) :='Entities: Fatal Alerts'                                     ;
SEARCH_NAME_EXPECTED_3082   VARCHAR2(64 BYTE) :='Entities: Critical Alerts'                                  ;
SEARCH_NAME_EXPECTED_3083   VARCHAR2(64 BYTE) :='Entities: Warning Alerts'                                   ;
SEARCH_NAME_EXPECTED_3084   VARCHAR2(64 BYTE) :='Host Status by Type'                                        ;
SEARCH_NAME_EXPECTED_3085   VARCHAR2(64 BYTE) :='Host CPU Metrics'                                           ;
SEARCH_NAME_EXPECTED_3086   VARCHAR2(64 BYTE) :='Database I/O Metrics'                                       ;
SEARCH_NAME_EXPECTED_3087   VARCHAR2(64 BYTE) :='Load Balancer Status by Type'                               ;
SEARCH_NAME_EXPECTED_3088   VARCHAR2(64 BYTE) :='Load Balancer Performance Metrics'                          ;
SEARCH_NAME_EXPECTED_3089   VARCHAR2(64 BYTE) :='Database Status by Type'                                    ;
SEARCH_NAME_EXPECTED_3090   VARCHAR2(64 BYTE) :='Application Server Status by Type'                          ;
SEARCH_NAME_EXPECTED_3091   VARCHAR2(64 BYTE) :='Application Server Load Metrics'                            ;
SEARCH_NAME_EXPECTED_3092   VARCHAR2(64 BYTE) :='CPU Utilization by Host Type'                               ;
SEARCH_NAME_EXPECTED_3093   VARCHAR2(64 BYTE) :='Hosts Grouped by Memory Utilization'                        ;
SEARCH_NAME_EXPECTED_3094   VARCHAR2(64 BYTE) :='Host Status'                                                ;
SEARCH_NAME_EXPECTED_3095   VARCHAR2(64 BYTE) :='Hosts: Fatal Alerts'                                        ;
SEARCH_NAME_EXPECTED_3096   VARCHAR2(64 BYTE) :='Hosts: Critical Alerts'                                     ;
SEARCH_NAME_EXPECTED_3097   VARCHAR2(64 BYTE) :='Hosts: Warning Alerts'                                      ;
SEARCH_NAME_EXPECTED_3098   VARCHAR2(64 BYTE) :='Host Performance Metrics'                                   ;
SEARCH_NAME_EXPECTED_3099   VARCHAR2(64 BYTE) :='Hosts: Top 5 by Alert Count'                                ;
SEARCH_NAME_EXPECTED_3200   VARCHAR2(64 BYTE) :='Avg Disk I/O Request Rate'                                  ;
SEARCH_NAME_EXPECTED_3201   VARCHAR2(64 BYTE) :='Database Status'                                            ;
SEARCH_NAME_EXPECTED_3202   VARCHAR2(64 BYTE) :='Databases: Fatal Alerts'                                    ;
SEARCH_NAME_EXPECTED_3203   VARCHAR2(64 BYTE) :='Databases: Critical Alerts'                                 ;
SEARCH_NAME_EXPECTED_3204   VARCHAR2(64 BYTE) :='Databases: Warning Alerts'                                  ;
SEARCH_NAME_EXPECTED_3205   VARCHAR2(64 BYTE) :='Database Performance Metrics'                               ;
SEARCH_NAME_EXPECTED_3206   VARCHAR2(64 BYTE) :='Space Used by Database Type'                                ;
SEARCH_NAME_EXPECTED_3207   VARCHAR2(64 BYTE) :='Databases Grouped by Transactions'                          ;
SEARCH_NAME_EXPECTED_3208   VARCHAR2(64 BYTE) :='Databases: Top 5 by Alert Count'                            ;
SEARCH_NAME_EXPECTED_3209   VARCHAR2(64 BYTE) :='Entities'                                                   ;
SEARCH_NAME_EXPECTED_3210   VARCHAR2(64 BYTE) :='Application Server Status'                                  ;
SEARCH_NAME_EXPECTED_3211   VARCHAR2(64 BYTE) :='Application Server: Fatal Alerts'                           ;
SEARCH_NAME_EXPECTED_3212   VARCHAR2(64 BYTE) :='Application Server: Critical Alerts'                        ;
SEARCH_NAME_EXPECTED_3213   VARCHAR2(64 BYTE) :='Application Server: Warning Alerts'                         ;
SEARCH_NAME_EXPECTED_3214   VARCHAR2(64 BYTE) :='Application Servers: Top 5 by Alert Count'                  ;
SEARCH_NAME_EXPECTED_3215   VARCHAR2(64 BYTE) :='Application Server Performance Metrics'                     ;
SEARCH_NAME_EXPECTED_3216   VARCHAR2(64 BYTE) :='Average Memory Usage'                                       ;
SEARCH_NAME_EXPECTED_3217   VARCHAR2(64 BYTE) :='CPU Utilization by Application Server Type'                 ;
SEARCH_NAME_EXPECTED_3218	VARCHAR2(64 BYTE) :='Application Servers Grouped by Web Request Rate'            ;
SEARCH_NAME_EXPECTED_3029   VARCHAR2(64 BYTE) :='OMC Oracle Database - Transactions Rate'                    ;
SEARCH_NAME_EXPECTED_3030   VARCHAR2(64 BYTE) :='OMC WebLogic Server - Web Request Rate'                     ;
SEARCH_NAME_EXPECTED_3031	VARCHAR2(64 BYTE) :='OMC Host CPU Utilization'                                   ;

SEARCH_DESC_EXPECTED_2028   VARCHAR2(256 BYTE) := 'Histogram of incoming log records for entities of type ''Host''' ;
SEARCH_DESC_EXPECTED_2029   VARCHAR2(256 BYTE) := 'Histogram of incoming log records for entities of type ''Web Application Server''';

SEARCH_DESC_EXPECTED_3085   VARCHAR2(256 BYTE) :='svw';
SEARCH_DESC_EXPECTED_3086   VARCHAR2(256 BYTE) :='svw';

SEARCH_DESC_EXPECTED_3029   VARCHAR2(256 BYTE) :='OMC Oracle Database - Avg Transactions Rate by Hour';
SEARCH_DESC_EXPECTED_3030   VARCHAR2(256 BYTE) :='OMC WebLogic Server - Avg Web Request Rate by Hour';
SEARCH_DESC_EXPECTED_3031	VARCHAR2(256 BYTE) :='OMC Host - Avg CPU Utilization by Hour';

SEARCH_PARAMCOUNT_2028  NUMBER := 7  ;
SEARCH_PARAMCOUNT_2029  NUMBER := 7  ;
SEARCH_PARAMCOUNT_3079  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3080  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3081  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3082  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3083  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3084  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3085  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3086  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3087  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3088  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3089  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3090  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3091  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3092  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3093  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3094  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3095  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3096  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3097  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3098  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3099  NUMBER := 72 ;
SEARCH_PARAMCOUNT_3200  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3201  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3202  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3203  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3204  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3205  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3206  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3207  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3208  NUMBER := 72 ;
SEARCH_PARAMCOUNT_3209  NUMBER := 72 ;
SEARCH_PARAMCOUNT_3210  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3211  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3212  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3213  NUMBER := 74 ;
SEARCH_PARAMCOUNT_3214  NUMBER := 72 ;
SEARCH_PARAMCOUNT_3215  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3216  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3217  NUMBER := 73 ;
SEARCH_PARAMCOUNT_3218	NUMBER:=  73 ;
SEARCH_PARAMCOUNT_3029  NUMBER := 70 ;
SEARCH_PARAMCOUNT_3030  NUMBER := 70 ;
SEARCH_PARAMCOUNT_3031	NUMBER:=  70 ;

PROCEDURE CHECK_SEARCH(	C_SEARCH_ID IN NUMBER,	C_SEARCH_NAME IN VARCHAR2,	C_SEARCH_DESC IN VARCHAR2,	V_SEARCH_ID IN OUT NUMBER,
V_SEARCH_NAME IN OUT VARCHAR2,	V_SEARCH_DESC IN OUT VARCHAR2,	V_TENANT_ID IN NUMBER)
IS
BEGIN
	SELECT SEARCH_ID,NAME,DESCRIPTION INTO V_SEARCH_ID,V_SEARCH_NAME,V_SEARCH_DESC FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID=V_TENANT_ID AND SYSTEM_SEARCH=1 AND SEARCH_ID=C_SEARCH_ID;
	IF(C_SEARCH_ID = V_SEARCH_ID) THEN
		DBMS_OUTPUT.PUT_LINE('OOB SEARCH ID CORRECT SEARCH_ID: '||V_SEARCH_ID||', TENANT_ID: ' || V_TENANT_ID); 
	ELSE
		DBMS_OUTPUT.PUT_LINE('[ERROR]OOB SEARCH ID WRONG SEARCH_ID: '||V_SEARCH_ID||', TENANT_ID: ' || V_TENANT_ID); 
	END IF;	 
	
	IF(C_SEARCH_NAME = V_SEARCH_NAME) THEN
		DBMS_OUTPUT.PUT_LINE('OOB SEARCH NAME CORRECT SEARCH_ID: '||V_SEARCH_ID||', TENANT_ID: ' || V_TENANT_ID); 
	ELSE
		DBMS_OUTPUT.PUT_LINE('[ERROR] OOB SEARCH NAME WRONG SEARCH_ID: '||V_SEARCH_ID||', TENANT_ID: ' || V_TENANT_ID); 
	END IF;	 	 
	
	IF(C_SEARCH_DESC = V_SEARCH_DESC OR (C_SEARCH_DESC IS NULL AND V_SEARCH_DESC IS NULL)) THEN
		DBMS_OUTPUT.PUT_LINE('OOB SEARCH DESC CORRECT SEARCH_ID: '||V_SEARCH_ID||', TENANT_ID: ' || V_TENANT_ID); 
	ELSE
		DBMS_OUTPUT.PUT_LINE('[ERROR] OOB SEARCH DESC WRONG SEARCH_ID: '||V_SEARCH_ID||', TENANT_ID: ' || V_TENANT_ID); 
	END IF;	 	  
END;

PROCEDURE CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID IN NUMBER,	C_SEARCH_EXPECTED_PARAMCOUNT IN NUMBER,	V_SEARCH_PARAMCOUNT IN OUT NUMBER, V_TENANT_ID IN NUMBER)
IS
BEGIN
	SELECT COUNT(1) INTO V_SEARCH_PARAMCOUNT FROM EMS_ANALYTICS_SEARCH_PARAMS WHERE TENANT_ID = V_TENANT_ID AND SEARCH_ID = C_SEARCH_ID;
	IF (V_SEARCH_PARAMCOUNT = C_SEARCH_EXPECTED_PARAMCOUNT) THEN
		dbms_output.put_line('PARAM COUNT CORRECT, SEARCH_ID: '||V_SEARCH_ID||',TENANT_ID: '||V_TENANT_ID);
	ELSE
		dbms_output.put_line('[ERROR] PARAM COUNT WRONG, SEARCH_ID: '||V_SEARCH_ID||',TENANT_ID: '||V_TENANT_ID);
    END IF;
END;

BEGIN
 OPEN TENANT_CURSOR;
  LOOP
    IF (V_TENANT_ID<>-1) THEN
      V_CURRENT_TENANT_ID := V_TENANT_ID;
    ELSE
      FETCH TENANT_CURSOR INTO V_CURRENT_TENANT_ID;
      EXIT WHEN TENANT_CURSOR%NOTFOUND;     
    END IF;  
    
	ALL_OOB_COUNT_EXPECTED :=45;
	SELECT COUNT(1) INTO ALL_OOB_COUNT FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID = V_CURRENT_TENANT_ID AND DELETED = 0 AND SYSTEM_SEARCH = 1 AND IS_WIDGET = 1 AND SEARCH_ID IN (2028,
		2029, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095,
		3096, 3097, 3098, 3099, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213,
		3214, 3215, 3216, 3217, 3218, 3029, 3030, 3031); 
	IF (ALL_OOB_COUNT = ALL_OOB_COUNT_EXPECTED)THEN
		dbms_output.put_line('ALL_OOB_COUNT CORRECT, TENANT_ID: ' || V_CURRENT_TENANT_ID);
	ELSE
		dbms_output.put_line('[ERROR] ALL_OOB_COUNT WRONG, TENANT_ID:' || V_CURRENT_TENANT_ID);
    CONTINUE;
	END IF;

	--2028
	C_SEARCH_ID                  :=2028;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_2028;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_2028;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_2028;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
  
	--2029
	C_SEARCH_ID                  :=2029;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_2029;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_2029;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_2029;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);

	--3079
	C_SEARCH_ID                  :=3079;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3079;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3079;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3080
	C_SEARCH_ID                  :=3080;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3080;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3080;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3081
	C_SEARCH_ID                  :=3081;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3081;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3081;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3082
	C_SEARCH_ID                  :=3082;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3082;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3082;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3083
	C_SEARCH_ID                  :=3083;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3083;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3083;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3084
	C_SEARCH_ID                  :=3084;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3084;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3084;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3085
	C_SEARCH_ID                  :=3085;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3085;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_3085;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3085;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3086
	C_SEARCH_ID                  :=3086;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3086;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_3086;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3086;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3087
	C_SEARCH_ID                  :=3087;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3087;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3087;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3088
	C_SEARCH_ID                  :=3088;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3088;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3088;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3089
	C_SEARCH_ID                  :=3089;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3089;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3089;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3090
	C_SEARCH_ID                  :=3090;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3090;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3090;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3091
	C_SEARCH_ID                  :=3091;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3091;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3091;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3092
	C_SEARCH_ID                  :=3092;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3092;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3092;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3093
	C_SEARCH_ID                  :=3093;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3093;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3093;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3094
	C_SEARCH_ID                  :=3094;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3094;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3094;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3095
	C_SEARCH_ID                  :=3095;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3095;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3095;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3096
	C_SEARCH_ID                  :=3096;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3096;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3096;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3097
	C_SEARCH_ID                  :=3097;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3097;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3097;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3098
	C_SEARCH_ID                  :=3098;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3098;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3098;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3099
	C_SEARCH_ID                  :=3099;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3099;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3099;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3200
	C_SEARCH_ID                  :=3200;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3200;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3200;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3201
	C_SEARCH_ID                  :=3201;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3201;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3201;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3202
	C_SEARCH_ID                  :=3202;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3202;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3202;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3203
	C_SEARCH_ID                  :=3203;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3203;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3203;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3204
	C_SEARCH_ID                  :=3204;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3204;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3204;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3205
	C_SEARCH_ID                  :=3205;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3205;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3205;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
		
	  --3206
	C_SEARCH_ID                  :=3206;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3206;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3206;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
		
	  --3207
	C_SEARCH_ID                  :=3207;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3207;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3207;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
		
	  --3208
	C_SEARCH_ID                  :=3208;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3208;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3208;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
		
	  --3209
	C_SEARCH_ID                  :=3209;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3209;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3209;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
		
	  --3210
	C_SEARCH_ID                  :=3210;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3210;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3210;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3211
	C_SEARCH_ID                  :=3211;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3211;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3211;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3212
	C_SEARCH_ID                  :=3212;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3212;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3212;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3213
	C_SEARCH_ID                  :=3213;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3213;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3213;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3214
	C_SEARCH_ID                  :=3214;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3214;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3214;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3215
	C_SEARCH_ID                  :=3215;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3215;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3215;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3216
	C_SEARCH_ID                  :=3216;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3216;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3216;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3217
	C_SEARCH_ID                  :=3217;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3217;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3217;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3218
	C_SEARCH_ID                  :=3218;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3218;
	C_SEARCH_DESC                :=null;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3218;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3029
	C_SEARCH_ID                  :=3029;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3029;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_3029;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3029;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
	  --3030
	C_SEARCH_ID                  :=3030;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3030;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_3030;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3030;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
		
	  --3031
	C_SEARCH_ID                  :=3031;
	C_SEARCH_NAME                :=SEARCH_NAME_EXPECTED_3031;
	C_SEARCH_DESC                :=SEARCH_DESC_EXPECTED_3031;
	C_SEARCH_EXPECTED_PARAMCOUNT :=SEARCH_PARAMCOUNT_3031;
	CHECK_SEARCH(C_SEARCH_ID, C_SEARCH_NAME, C_SEARCH_DESC, V_SEARCH_ID, V_SEARCH_NAME, V_SEARCH_DESC, V_CURRENT_TENANT_ID);
	CHECK_SEARCH_PARAMS_COUNT(C_SEARCH_ID ,	C_SEARCH_EXPECTED_PARAMCOUNT, V_SEARCH_PARAMCOUNT ,	V_CURRENT_TENANT_ID);
	
    IF (V_TENANT_ID<>-1) THEN
      EXIT;
    END IF;
    END LOOP;
    CLOSE TENANT_CURSOR;  
END;
/  
spool off;









