Rem
Rem    DDL change during upgrade
Rem    add column CREATION_DATE & LAST_MODIFICATION_DATE to all tables
Rem    MODIFIED   (MM/DD/YY)
Rem    Rex Liang    06/29/2016 - created
Rem
Rem

ALTER TABLE EMS_ANALYTICS_CATEGORY ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;

ALTER TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;
ALTER TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;

ALTER TABLE EMS_ANALYTICS_LAST_ACCESS ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;
ALTER TABLE EMS_ANALYTICS_LAST_ACCESS ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;
ALTER TABLE EMS_ANALYTICS_LAST_ACCESS MODIFY OBJECT_ID NUMBER(*,0);

ALTER TABLE EMS_ANALYTICS_SCHEMA_VER_SSF ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;
ALTER TABLE EMS_ANALYTICS_SCHEMA_VER_SSF ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;

ALTER TABLE EMS_ANALYTICS_SEARCH_PARAMS ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;
ALTER TABLE EMS_ANALYTICS_SEARCH_PARAMS ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP;

ALTER TRIGGER EMS_ANALYTICS_FOLDERS_TR DISABLE;
ALTER TRIGGER EMS_ANALYTICS_CATEGORY_TR DISABLE;
ALTER TRIGGER EMS_ANALYTICS_SEARCH_TR DISABLE;