Rem
Rem emaas_savesearch_seed_data_la.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data_la.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for Log Analytics
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    miayu          04/21/15 - move OOB folder for LA to emaas_savesearch_seed_data.sql. Only OOB SEARCHES are expected to be in this file
Rem    jerrusse       08/21/14 - Created for Log Analytics 
Rem		 sdhamdhe				03/25/15 - Removed OOB searches for all of LA as requested by Jerry


DEFINE TENANT_ID = '&1'

--OOB Searches
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,UI_HIDDEN,DELETED,METADATA_CLOB,SEARCH_DISPLAY_STR,IS_WIDGET,TENANT_ID) 
values (2000,'Top Log Sources','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows the top sources based on number of log entries',2,1,null,null,null,null,1,null,0,0,0,null,'',1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2000,'WIDGET_TEMPLATE',null,1,'html/search/widgets/loganBarChart.html','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2000,'WIDGET_VIEWMODEL',null,1,'js/viewmodel/search/visualization/loganVisStatsViewModel.js','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2000,'time',null,1,'ALL','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2000,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_BAR','&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,UI_HIDDEN,DELETED,METADATA_CLOB,SEARCH_DISPLAY_STR,IS_WIDGET,TENANT_ID) 
values (2001,'All Logs Trend','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows time histogram of log entries',2,1,null,null,null,null,1,null,0,0,0,null,'',1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2001,'WIDGET_VIEWMODEL',null,1,'js/viewmodel/search/results/loganSearchChartsViewModel.js','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2001,'time',null,1,'ALL','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2001,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2001,'WIDGET_TEMPLATE',null,1,'html/search/widgets/loganHistogram.html','&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,UI_HIDDEN,DELETED,METADATA_CLOB,SEARCH_DISPLAY_STR,IS_WIDGET,TENANT_ID) 
values (2002,'Database Log Trends','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows time histogram of log entries for database target types',201,1,null,null,null,null,1,null,0,0,0,null,'',1,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2002,'WIDGET_TEMPLATE',null,1,'html/search/widgets/loganHistogram.html','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2002,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2002,'time',null,1,'ALL','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID) values (2002,'WIDGET_VIEWMODEL',null,1,'js/viewmodel/search/results/loganSearchChartsViewModel.js','&TENANT_ID');

insert into EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE,TENANT_ID) 
select SEARCH_ID,'ORACLE',2,SYS_EXTRACT_UTC(SYSTIMESTAMP),'&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=2000 and search_id<=2999 and TENANT_ID ='&TENANT_ID';
