Rem  drv: <migrate type="data_upgrade" version="13.1.0.0" />
Rem
Rem emaas_savesearch_seed_data_la.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data_la.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for Log Analytics
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    jerrusse       08/21/14 - Created for Log Analytics 
Rem


DEFINE TENANT_ID = '&1'

-- *********************** FOLDERS ********************************
-- folder id between 200 - 299 are reserved for Log Analytics

-- DATABASE 
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (201,'Database',2,'Databases',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (206,'Alerts',201,'Searches based on database alert logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');


-- MIDDLEWARE
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (202,'Middleware',2,'Middleware',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (207,'Access',202,'Searches based on HTTP request access logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (208,'Server',202,'Searches based on operational middleware server logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');



-- HOST
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (203,'Servers, Storage and Network',2,'Servers, Storage and Network',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (209,'Security',203,'Searches based on logs that capture host-level security',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',
SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (210,'Lifecycle',203,'Searches based on logs that capture host lifecycle, such as package managers',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',
SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

-- ENTERPRISE MANAGER
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (205,'Enterprise Manager',2,'Entprise Manager',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (211,'Servers',205,'Searches based on Enterprise Manager server logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
TENANT_ID) 
values (212,'Agents',205,'Searches based on Enterprise Manager agent logs',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');


-- APPLICATIONS 
-- Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN,
--TENANT_ID) 
-- values (204,'Applications',2,'Applications',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0,'&TENANT_ID');




-- ********************  SAVED SEARCHES  ********************************

-- search id 2000 - 2999 are reserved for LA searches

-- DATABASE 
---- Alerts
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2000,206,'Top Process IDs per Target with Alerts','"Log Rule" = "Database Alert Log Rule" | stats count as "Alert Count" by target, "oracle process id"|top limit=3 "Alert Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2001,206,'Top Database Targets with Errors','"Log Rule" = "Database Alert Log Rule" AND severity  in ("error","ERROR","SEVERE","severe") |stats count as "Error Count" by target |top limit=10 "Error Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2002,206,'Top Alert Message IDs','"Log Rule" = "Database Alert Log Rule" |stats count as "Alert Count" by "Message ID" |top limit=10 "Alert Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2003,206,'Disaster Recovery Alerts','"Log Rule" = "Database Alert Log Rule" AND Group = "dra"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2004,206,'Administration DDL Alerts','"Log Rule" = "Database Alert Log Rule" AND Group = "admin_ddl"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2005,206,'Database Instance Shutdown Alerts By Target','"Log Rule" = "Database Alert Log Rule" AND Group = "shutdown" AND "Instance shutdown complete" |stats count as "Alert Count" by target |top limit=10 "Alert Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2006,206,'Lost Database Connections (ORA-609) By Target','"Log Rule" = "Database Alert Log Rule"  AND "ORA-609" |stats count as "Alert Count" by target |top limit=10 "Alert Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');




-- MIDDLEWARE
---- Access
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2007,207,'Response Size > 10KB','"Log Rule" = "FMW WLS Server Access Log Rule" AND "Content Size" > 10240','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2008,207,'Response Size > 50KB','"Log Rule" = "FMW WLS Server Access Log Rule" AND "Content Size" > 51200','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2009,207,'Top Accessed Pages','"Log Rule" = "FMW WLS Server Access Log Rule" |stats count as "Request Count" by URI |top limit=10 "Request Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2010,207,'Top Client IP Addresses','"Log Rule" = "FMW WLS Server Access Log Rule" |stats count as "Request Count" by "Host IP Address (Client)" |top limit=10 "Request Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2011,207,'Failed HTTP Requests','"Log Rule" = "FMW WLS Server Access Log Rule" AND status in ("400","401","402","403","404","405","406","407","408","409","410","411","412","413","414","415","416","417","500","501","502","503","504","505")','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),
SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2012,207,'Top Weblogic Targets By Number of Requests','"Log Rule" = "FMW WLS Server Access Log Rule" |stats count as "Request Count" by target |top limit=10 "Request Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

---- Server Logs
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2013,208,'Top BEA-XXXXXX Error Codes','"Log Rule" = "FMW WLS Server Log Rule" AND "Error ID" != "bea-000000" |stats count as cnt by "error id" |top limit=10 cnt','ORACLE',
SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2014,208,'Top ECIDs with BEA-XXXXXX Error Codes','"Log Rule" = "FMW WLS Server Log Rule" AND "Error ID" != "bea-000000" |stats count as "BEA-XXXXXX Count" by ecid |top limit=10 "BEA-XXXXXX Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2015,208,'Top WebLogic Targets with Errors','"Log Rule" = "FMW WLS Server Log Rule" AND severity  in ("error","ERROR","SEVERE","severe") |stats count as "Error Count" by target |top limit=10 "Error Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');


-- HOST
---- Security
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2016,209,'Invalid User Login Attempts','"Log Rule" = "Secure Log Rule" AND ("Invalid user" OR "user unknown")','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2017,209,'Failed Password Attempts','"Log Rule" = "Secure Log Rule" AND ("Failed password for" OR "authentication failure")','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');


Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2018,209,'Top Commands Run with Sudo','"Log Rule" = "Sudo log Rule"  |stats count as "Execution Count" by command |top limit=10 "Execution Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

---- Lifecycle
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2019,210,'Linux Kernel Package Lifecyclce','"Log Rule" = "YUM Log Rule" "kernel"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');


-- ENTERPRISE MANAGER
---- Server
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2020,211,'Oracle Management Server Errors','"Log Rule" = "EM Cloud Control OMS Log Rule" AND severity  in ("error","ERROR","SEVERE","severe","incident_error","INCIDENT_ERROR")','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');

---- Agent

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,FOLDER_ID,NAME,SEARCH_DISPLAY_STR,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,
SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,UI_HIDDEN,TENANT_ID) 
values (2021,212,'Top Targets with Oracle Management Agent Errors','"Log Rule" = "EM Cloud Control Agent Log Rule" AND severity  in ("error","ERROR","SEVERE","severe","incident_error","INCIDENT_ERROR")  |stats count as "Error Count" by target |top limit=10 "Error Count"','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,1,null,null,null,null,1,null,0,null,0,'&TENANT_ID');


-- APPLICATIONS


-- SEARCH PARAMATERS 
-- For now, we just make all searches have same params. We will revisit this in future
Insert into EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID)
select SEARCH_ID,'INVISIBLE_TO_DASHBOARD',1,'FALSE','&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=2000 and search_id<=2999  and TENANT_ID ='&TENANT_ID';

Insert into EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID)
select SEARCH_ID,'HISTOGRAM_GROUPBY',1,null ,'&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=2000 and search_id<=2999  and TENANT_ID ='&TENANT_ID';

Insert into EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_TYPE,PARAM_VALUE_STR,TENANT_ID)
select SEARCH_ID,'time_range',1,'ALL_TIME','&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=2000 and search_id<=2999  and TENANT_ID ='&TENANT_ID';


-- LAST ACCESS MARKERS
Insert into EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE,TENANT_ID)
select SEARCH_ID,'SYSMAN',2,SYS_EXTRACT_UTC(SYSTIMESTAMP),'&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=2000 and search_id<=2999 and TENANT_ID ='&TENANT_ID';
