Rem
Rem emaas_savesearch_seed_data_la.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data_la.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for Log Analytics
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    miayu          04/21/15 - move OOB folder for LA to emaas_savesearch_seed_data.sql. Only OOB SEARCHES are expected to be in this file
Rem    jerrusse       08/21/14 - Created for Log Analytics 
Rem		 sdhamdhe				03/25/15 - Removed OOB searches for all of LA as requested by Jerry


DEFINE TENANT_ID = '&1'

--OOB Searches
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2000,'Top Log Sources','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top Log Sources based on number of log entries collected.',2,1,null,null,null,null,1,null,0,'* | STATS COUNT AS cnt BY ''Log Source'' | TOP LIMIT = 10 cnt',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2000,'VISUALIZATION_TYPE_KEY',null,1,'BAR',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2000,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_BAR',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2000,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganBarChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2000,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2000,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2001,'All Logs Trend','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of all log entries from all sources.',2,1,null,null,null,null,1,null,0,'*',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2001,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2001,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2001,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganHistogram.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2001,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/results/loganSearchChartsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2001,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2002,'Database Log Trends','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of all log entries from Database targets.',2,1,null,null,null,null,1,null,0,'''Target Type'' IN (''Database Instance'', ''Automatic Storage Management'', ''Listener'', ''Cluster'')',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2002,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2002,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2002,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganHistogram.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2002,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/results/loganSearchChartsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2002,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2003,'Enterprise Manager Logs Trend','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of all log entries from Enterprise Manager targets',2,1,null,null,null,null,1,null,0,'''Target Type'' IN (''Agent'', ''Harvester'', ''Gateway'', ''Oracle Management Service'', ''Lama'')',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2003,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2003,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2003,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganHistogram.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2003,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/results/loganSearchChartsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2003,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2004,'Host Logs Trend','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of all log entries from Host targets',2,1,null,null,null,null,1,null,0,'''Target Type'' IN (''Host'')',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2004,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2004,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2004,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganHistogram.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2004,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/results/loganSearchChartsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2004,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2005,'Top Database Targets with Log Errors','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top 10 Database targets that have the most log entries with ERROR or SEVERE severity.',2,1,null,null,null,null,1,null,0,'''Target Type'' IN (''Database Instance'', ''Automatic Storage Management'', ''Listener'', ''Cluster'') AND Severity IN (''error'', ''ERROR'', ''SEVERE'', ''severe'')  |stats count as ''Error Count'' by target |top limit=10 ''Error Count''',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2005,'VISUALIZATION_TYPE_KEY',null,1,'PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2005,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2005,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganPieChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2005,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2005,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2006,'Middleware Logs Trend','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of all log entries from Middleware targets',2,1,null,null,null,null,1,null,0,'''Target Type'' IN (''Oracle WebLogic Server'', ''Oracle Internet Directory'', ''Oracle HTTP Server'', ''Oracle Access Management Server'', ''Oracle WebLogic Domain'')',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2006,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2006,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2006,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganHistogram.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2006,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/results/loganSearchChartsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2006,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2007,'Web Server Top Accessed Pages','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top 10 recently accessed web pages in Middleware access logs.',2,1,null,null,null,null,1,null,0,'''log source'' in (''FMW WLS Server Access Log'',''FMW OHS Access Log'') |stats count as ''Request Count'' by URI |top limit=10 ''Request Count''',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2007,'VISUALIZATION_TYPE_KEY',null,1,'BAR',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2007,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_BAR',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2007,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganBarChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2007,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2007,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2008,'Web Server Failed HTTP Requests','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of recent HTTP request failures.',2,1,null,null,null,null,1,null,0,'''log source'' IN (''FMW WLS Server Access Log'', ''FMW OHS Access Log'') AND Status IN (''400'', ''401'', ''402'', ''403'', ''404'', ''405'', ''406'', ''407'', ''408'', ''409'', ''410'', ''411'', ''412'', ''413'', ''414'', ''415'', ''416'', ''417'', ''500'', ''501'', ''502'', ''503'', ''504'', ''505'')',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2008,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2008,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_HISTOGRAM',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2008,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganHistogram.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2008,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/results/loganSearchChartsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2008,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2009,'Top Web Server Targets by Requests','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top 10 web server targets with the most HTTP requests.',2,1,null,null,null,null,1,null,0,'''log source'' in (''FMW WLS Server Access Log'',''FMW OHS Access Log'') |stats count as ''Request Count'' by target |top limit=10 ''Request Count''',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2009,'VISUALIZATION_TYPE_KEY',null,1,'PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2009,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2009,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganPieChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2009,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2009,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2010,'Top Middleware Error Codes','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top 10 most common recent Middleware errors codes (such as BEA-XXXXXX).',2,1,null,null,null,null,1,null,0,'''target type'' in (''Oracle WebLogic Server'', ''Oracle Internet Directory'',''Oracle HTTP Server'',''Oracle Access Management Server'',''Oracle WebLogic Domain'') AND ''Error ID'' != ''bea-000000'' |stats count as cnt by ''error id'' |top limit=10 cnt',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2010,'VISUALIZATION_TYPE_KEY',null,1,'PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2010,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2010,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganPieChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2010,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2010,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2011,'Top ECIDs with BEA Errors','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top 10 Execution IDs (ECIDs) based on number of log entries containing BEA error codes.',2,1,null,null,null,null,1,null,0,'''target type'' in (''Oracle WebLogic Server'',''Oracle Internet Directory'',''Oracle HTTP Server'',''Oracle Access Management Server'', ''Oracle WebLogic Domain'') AND ''Error ID'' != ''bea-000000'' |stats count as ''BEA-XXXXXX Count'' by ecid |top limit=10 ''BEA-XXXXXX Count''',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2011,'VISUALIZATION_TYPE_KEY',null,1,'PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2011,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2011,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganPieChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2011,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2011,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
values (2012,'Top Middleware Targets with Errors','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Top 10 Middleware targets that have the most log entries with ERROR or SEVERE severity.',2,1,null,null,null,null,1,null,0,'''target type'' in (''Oracle WebLogic Server'',''Oracle Internet Directory'',''Oracle HTTP Server'',''Oracle Access Management Server'', ''Oracle WebLogic Domain'') AND severity  in (''error'',''ERROR'',''SEVERE'',''severe'') |stats count as ''Error Count'' by target |top limit=10 ''Error Count''',0,0,1,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2012,'VISUALIZATION_TYPE_KEY',null,1,'PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2012,'WIDGET_KOC_NAME',null,1,'LA_WIDGET_PIE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2012,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/loganPieChart.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2012,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/visualization/loganVisStatsViewModel.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2012,'time',null,1,'{"type":"relative", "duration":"24", "timeUnit":"HOUR"}',null,'&TENANT_ID');

insert into EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE,TENANT_ID) 
select SEARCH_ID,'ORACLE',2,SYS_EXTRACT_UTC(SYSTIMESTAMP),'&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=2000 and search_id<=2999 and TENANT_ID ='&TENANT_ID';
