Rem  drv: <migrate type="data_upgrade" version="13.1.0.0" />
Rem
Rem emaas_savesearch_seed_data_ta.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data_ta.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for Target Analytics
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    miayu       07/02/14 - Created for Target Analytics
Rem


-- folder id between 300 - 399 are reserved for Target Analytics
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN) values (301,'Databases',4,'Databases',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0);
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN) values (302,'Middleware',4,'Middleware',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0);
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN) values (300,'Servers, Storage and Network',4,'Servers, Storage and Network',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0);
Insert into EMS_ANALYTICS_FOLDERS (FOLDER_ID,NAME,PARENT_ID,DESCRIPTION,CREATION_DATE,OWNER,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_FOLDER,EM_PLUGIN_ID,UI_HIDDEN) values (303,'Applications',4,'Applications',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,null,null,null,1,null,0);


-- search id 3000 - 3999 are reserved for TA searches
Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3000,'WebLogic Servers with a specific patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"weblogic_j2eeserver","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(weblogic_j2eeserver,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(weblogic_j2eeserver,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3001,'WebLogic Servers with non-standard Maximum Heap Size','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicResourceconfig_maxheap","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"lt","values":{"jsonConstructor":"CriterionValue","data":{"value":1024}}}}]}},"dataType":"number","displayName":"Maximum Heap Size (MB)","displayDetails":"Resource Usage","targetType":"weblogic_j2eeserver","mcName":"maxheap","mgName":"WeblogicResourceconfig","mgDisplayName":"Resource Usage","isKey":0,"groupKeyColumns":[]}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3002,'WebLogic Servers with non-standard Starting Heap Size','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicResourceconfig_startheap","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"lt","values":{"jsonConstructor":"CriterionValue","data":{"value":256}}}}]}},"dataType":"number","displayName":"Starting Heap Size (MB)","displayDetails":"Resource Usage","targetType":"weblogic_j2eeserver","mcName":"startheap","mgName":"WeblogicResourceconfig","mgDisplayName":"Resource Usage","isKey":0,"groupKeyColumns":[]}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3003,'WebLogic Servers with non-standard Admin Port','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_administrationport","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"lt","values":{"jsonConstructor":"CriterionValue","data":{"value":9002}}}},{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":9002}}}}]}},"dataType":"number","displayName":"Administration Port","displayDetails":"Server Information","targetType":"weblogic_j2eeserver","mcName":"administrationport","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[]}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3004,'WebLogic Servers with non-standard SSL Listen Port','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_ssllistenport","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"lt","values":{"jsonConstructor":"CriterionValue","data":{"value":7000}}}},{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":10000}}}}]}},"dataType":"number","displayName":"SSL Listen Port","displayDetails":"Server Information","targetType":"weblogic_j2eeserver","mcName":"ssllistenport","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[]}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3005,'WebLogic Servers with non-standard Listen Port','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_listenport","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"lt","values":{"jsonConstructor":"CriterionValue","data":{"value":7000}}}},{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":10000}}}}]}},"dataType":"number","displayName":"Listen Port","displayDetails":"Server Information","targetType":"weblogic_j2eeserver","mcName":"listenport","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[]}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3006,'Oracle HTTP Servers with a specific patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_apache","metadata":{"category":false},"displayValue":"Oracle HTTP Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"oracle_apache","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(oracle_apache,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(oracle_apache,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3007,'Databases with a specific patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,301,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"oracle_database","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(oracle_database,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(oracle_database,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) values (3008,'Databases with Autoextend ON and size greater than 30GB','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,301,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_autoextensible","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"YES"}}}}]}},"dataType":"string","displayName":"Autoextensible","displayDetails":"Datafiles","targetType":"oracle_database","mcName":"autoextensible","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName","fileName","tablespaceName","fileName","tablespaceName"]}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_fileSize","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":32212254720}}}}]}},"dataType":"number","displayName":"Size","displayDetails":"Datafiles","targetType":"oracle_database","mcName":"fileSize","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName","fileName","tablespaceName","fileName","tablespaceName"]}}]}',0);

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN) 
values (3009,'Fusion Instances missing a given patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,303,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"fusion_apps_instance","metadata":{"category":false},"displayValue":"Fusion Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"fusion_apps_instance","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(fusion_apps_instance,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"not","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(fusion_apps_instance,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"not","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0);

insert into EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE)
select SEARCH_ID,'SYSMAN',2,SYS_EXTRACT_UTC(SYSTIMESTAMP) from EMS_ANALYTICS_SEARCH where search_id>=3000 and search_id<=3999;


