Rem
Rem emaas_savesearch_seed_data_ta.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data_ta.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for Target Analytics
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    miayu       04/21/15 - Only OOB SEARCHES are expected to be in this file
Rem    WKEICHER    09/30/14 - Update TA OOB Searches
Rem    miayu       07/02/14 - Created for Target Analytics
Rem

DEFINE TENANT_ID ='&1'

-- base TA folder is 4
-- search id 3000 - 3999 are reserved for TA searches
Insert into EMS_ANALYTICS_SEARCH
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET)
values (3000,'WebLogic Servers with their Patch IDs','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows the status, Target Version and list of Patch IDs for WebLogic Servers',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"string","displayName":"Target Status","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":true,"ignoreCase":true},"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"PropertySearchCriterion","data":{"id":"property.orcl_gtp_target_version","_value":null,"dataType":"string","displayName":"Target Version","displayDetails":null,"role":"column","func":null,'||
'"UIProperties":{"useForSort":false},"targetType":"weblogic_j2eeserver","propertyName":"orcl_gtp_target_version"}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"sourceTargetType":"weblogic_j2eeserver","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(weblogic_j2eeserver,oracle_home)"},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":null,"dataType":"string","displayName":"Patch ID","displayDetails":"Unclassified ","role":"column","func":null,"UIProperties":{},"targetType":"oracle_home","unitStr":"n/a","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Unclassified ","isKey":1,"groupKeyColumns":["id","lang","upi"],"isConfig":1}},"id":"installed_at(weblogic_j2eeserver,oracle_home)_oracle_home_LlInvPatches_id","_value":null,"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Unclassified ","role":"column","func":null,"UIProperties":{"useForSort":false}}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3000,'TA_HORI_SORT_COLUMN',null,1,'0',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET)
values (3001,'WebLogic Servers with small Maximum Heap Size','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC
(SYSTIMESTAMP),'ORACLE','Shows WebLogic Servers with Maximum Heap Size less than 1GB running on hosts with Memory Size greater than 8GB',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'TA_CRITERIA',null,2,null,TO_CLOB('{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicResourceconfig_maxheap","_value":null,"dataType":"number","displayName":"Maximum Heap Size (MB)","displayDetails":"Resource Usage","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":true},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"maxheap","mgName":"WeblogicResourceconfig","mgDisplayName":"Resource Usage","isKey":0,"groupKeyColumns":[],"isConfig":1,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"sourceTargetType":"weblogic_j2eeserver","destinationTargetType":"host","associationType":"hosted_by","assocDisplayName":"hosted_by","inverseAssocType":"host_for","id":"hosted_by(weblogic_j2eeserver,host)"},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_memorySizeInMb","_value":null,"dataType":"number","displayName":"Memory Size (MB)","displayDetails":"Hardware","role":"column","func":null,"UIProperties":{},"targetType":"host","unitStr":null,"mcName":"memorySizeInMb","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}},"id":"hosted_by(weblogic_j2eeserver,host)_host_Hw_memorySizeInMb","_value":null,"dataType":"number","displayName":"Memory Size (MB)","displayDetails":"hosted_by (Host) > Hardware","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"}')||
TO_CLOB(',{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicResourceconfig_maxheap","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"lt","values":{"jsonConstructor":"CriterionValue","data":{"value":1024}}}}]}},"dataType":"number","displayName":"Maximum Heap Size (MB)","displayDetails":"Resource Usage","role":"filter","func":null,"UIProperties":{"useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"maxheap","mgName":"WeblogicResourceconfig","mgDisplayName":"Resource Usage","isKey":0,"groupKeyColumns":[],"isConfig":1}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"sourceTargetType":"weblogic_j2eeserver","destinationTargetType":"host","associationType":"hosted_by","assocDisplayName":"hosted_by","inverseAssocType":"host_for","id":"hosted_by(weblogic_j2eeserver,host)"},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_memorySizeInMb","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":8192}}}}]}},"dataType":"number","displayName":"Memory Size (MB)","displayDetails":"Hardware","role":"filter","func":null,"UIProperties":{},"targetType":"host","unitStr":null,"mcName":"memorySizeInMb","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}},"id":"hosted_by(weblogic_j2eeserver,host)_host_Hw_memorySizeInMb","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":8192}}}}]}},"dataType":"number","displayName":"Memory Size (MB)","displayDetails":"hosted_by (Host) > Hardware","role":"filter","func":null,"UIProperties":{"useForSort":false}}}]}'),'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3001,'TA_HORI_SORT_COLUMN',null,1,'0',null,'&TENANT_ID');


Insert into EMS_ANALYTICS_SEARCH
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET)
values (3002,'WebLogic Servers and their Ports','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC
(SYSTIMESTAMP),'ORACLE','Shows the Listen Port, SSL Listen Port and Administration Port for WebLogic Servers',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_listenport","_value":null,"dataType":"number","displayName":"Listen Port","displayDetails":"Server Information","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"string","useForSort":true},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"listenport","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[],"isConfig":1,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_ssllistenport","_value":null,"dataType":"number","displayName":"SSL Listen Port","displayDetails":"Server Information"'||
',"role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"string","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"ssllistenport","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_administrationport","_value":null,"dataType":"number","displayName":"Administration Port","displayDetails":"Server Information","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"string","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"administrationport","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[],"isConfig":1}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3002,'TA_HORI_SORT_COLUMN',null,1,'0',null,'&TENANT_ID');


Insert into EMS_ANALYTICS_SEARCH
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET)
values (3003,'Databases with Autoextend ON and size greater than 10GB','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC
(SYSTIMESTAMP),'ORACLE','Shows Databases for which there is a datafile with size greater than 10GB and Autoextensible is ON for that datafile',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_fileSize","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":10737418240}}}}}}]}},"dataType":"number","displayName":"Size","displayDetails":"Datafiles","role":"filter","func":null,"UIProperties":{"useForSort":false},"targetType":"oracle_database","unitStr":null,"mcName":"fileSize","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName"],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_autoextensible",'||
'"_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"like","values":{"jsonConstructor":"CriterionValue","data":{"value":"%YES%"}}}}}}]}},"dataType":"string","displayName":"Autoextensible","displayDetails":"Datafiles","role":"filter","func":null,"UIProperties":{"useForSort":false},"targetType":"oracle_database","unitStr":null,"mcName":"autoextensible","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName"],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_fileSize","_value":null,"dataType":"number","displayName":"Size","displayDetails":"Datafiles","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":true},"targetType":"oracle_database","unitStr":null,"mcName":"fileSize","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName"],"isConfig":1,"direction":"DESC","inverseNullOrderBy":true}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3003,'TA_HORI_SORT_COLUMN',null,1,'0',null,'&TENANT_ID');


Insert into EMS_ANALYTICS_SEARCH
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET)
values (3004,'Top 10 Listeners by Load','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows Response Time, Connections Established and Connections Refused for top 10 Listeners (by Load)',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_listener","metadata":{"category":false},"displayValue":"Listener"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","UIProperties":{"useForSort":false}}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"string","displayName":"Target Status","displayDetails":null,"role":"column","UIProperties":{"useForSort":false,"ignoreCase":true},"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_listener_Response_tnsPing","_value":null,"dataType":"number","displayName":"Response Time (msec)","displayDetails":"Response","role":"column","UIProperties":{"useForSort":false,"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar"},"targetType":"oracle_listener","mcName":"tnsPing","mgName":"Response","mgDisplayName":"Response","isKey":0,"groupKeyColumns":[],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_listener_Load_estConns","_value":null,"dataType":"number","displayName":"Connections Established","displayDetails":"Load","role":"column",'||
'"UIProperties":{"useForSort":true,"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar"},"targetType":"oracle_listener","mcName":"estConns","mgName":"Load","mgDisplayName":"Load","isKey":0,"groupKeyColumns":[],"isConfig":0,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_listener_Load_refConns","_value":null,"dataType":"number","displayName":"Connections Refused (per","displayDetails":"Load","role":"column","UIProperties":{"useForSort":false,"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar"},"targetType":"oracle_listener","mcName":"refConns","mgName":"Load","mgDisplayName":"Load","isKey":0,"groupKeyColumns":[],"isConfig":0}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'TOP_N_ROWS',null,1,'10',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3004,'TA_HORI_SORT_COLUMN',null,1,'2',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH 
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET) 
values (3018,'Host Inventory By Platform','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows CPU Implementation, Total CPU Cores/Sockets/Threads and Memory Size for Hosts grouped by Operating System',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"host","metadata":{"category":false},"displayValue":"Host"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_HwCpu_impl","_value":null,"dataType":"string","displayName":"Implementation","displayDetails":"CPUs","role":"column","func":null,"UIProperties":{"useForSort":false},"targetType":"host","unitStr":null,"mcName":"impl","mgName":"HwCpu","mgDisplayName":"CPUs","isKey":1,"groupKeyColumns":["numCores","ecacheInMb","freqInMhz","isHyperthreadEnabled","impl","mask","revision","siblings","vendorName"],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_totalCpuCores","_value":null,"dataType":"number","displayName":"Total CPU Cores","displayDetails":"Hardware","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"host","unitStr":null,"mcName":"totalCpuCores","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_physicalCpuCount","_value":null,"dataType":"number","displayName":"Total CPU Sockets","displayDetails":"Hardware","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"host","unitStr":null,"mcName":"physicalCpuCount","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}}'||
',{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_logicalCpuCount","_value":null,"dataType":"number","displayName":"Total CPU Threads","displayDetails":"Hardware","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"host","unitStr":null,"mcName":"logicalCpuCount","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_memorySizeInMb","_value":null,"dataType":"number","displayName":"Memory Size (MB)","displayDetails":"Hardware","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"host","unitStr":null,"mcName":"memorySizeInMb","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Os_name","_value":null,"dataType":"string","displayName":"Name","displayDetails":"Operating System","role":"group by","func":null,"UIProperties":{"useForSort":false},"targetType":"host","unitStr":null,"mcName":"name","mgName":"Os","mgDisplayName":"Operating System","isKey":0,"groupKeyColumns":[],"isConfig":1}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3018,'TA_HORI_SORT_COLUMN',null,1,'-1',null,'&TENANT_ID');


Insert into EMS_ANALYTICS_SEARCH 
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET) 
values (3019,'Top 25 Databases by Resource Consumption','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows the status, Database CPU Time, CPU Utilization, Total Memory Usage and Number of Transactions per second for Top 25 Databases (by Resource Consumption)',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"string","displayName":"Target Status","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_InstanceEfficiency_cpuTimePct","_value":null,"dataType":"number","displayName":"Database CPU Time (%)","displayDetails":"Efficiency","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":true},"targetType":"oracle_database","unitStr":null,"mcName":"cpuTimePct","mgName":"InstanceEfficiency","mgDisplayName":"Efficiency","isKey":0,"groupKeyColumns":[],"isConfig":0,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"sourceTargetType":"oracle_database","destinationTargetType":"host","associationType":"hosted_by","assocDisplayName":"hosted_by","inverseAssocType":"host_for","id":"hosted_by(oracle_database,host)"},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Load_cpuUtil","_value":null,"dataType":"number","displayName":"CPU Utilization (%)","displayDetails":"Utilization ","role":"column","func":null,"UIProperties":{},"targetType":"host","unitStr":"%","mcName":"cpuUtil","mgName":"Load","mgDisplayName":"Utilization ","isKey":0,"groupKeyColumns":[],"isConfig":0}}'||
',"id":"hosted_by(oracle_database,host)_host_Load_cpuUtil","_value":null,"dataType":"number","displayName":"CPU Utilization (%)","displayDetails":"hosted_by (Host) > Utilization ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_MemoryUsage_totalMemory","_value":null,"dataType":"number","displayName":"Total Memory Usage (MB)","displayDetails":"Memory Usage","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"oracle_database","unitStr":null,"mcName":"totalMemory","mgName":"MemoryUsage","mgDisplayName":"Memory Usage","isKey":0,"groupKeyColumns":[],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_InstanceThroughput_transactionsPs","_value":null,"dataType":"number","displayName":"Number of Transactions (per second)","displayDetails":"Throughput","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"oracle_database","unitStr":null,"mcName":"transactionsPs","mgName":"InstanceThroughput","mgDisplayName":"Throughput","isKey":0,"groupKeyColumns":[],"isConfig":0}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'TOP_N_ROWS',null,1,'25',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3019,'TA_HORI_SORT_COLUMN',null,1,'1',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH 
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET) 
values (3020,'Database Configuration and Storage By Version','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows Total CPU Cores, Patch IDs, Tablespace Size and SGA Size for Databases grouped by their version',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"sourceTargetType":"oracle_database","destinationTargetType":"host","associationType":"hosted_by","assocDisplayName":"hosted_by","inverseAssocType":"host_for","id":"hosted_by(oracle_database,host)"},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"host_Hw_totalCpuCores","_value":null,"dataType":"number","displayName":"Total CPU Cores","displayDetails":"Hardware","role":"column","func":null,"UIProperties":{},"targetType":"host","unitStr":null,"mcName":"totalCpuCores","mgName":"Hw","mgDisplayName":"Hardware","isKey":0,"groupKeyColumns":[],"isConfig":1}},"id":"hosted_by(oracle_database,host)_host_Hw_totalCpuCores","_value":null,"dataType":"number","displayName":"Total CPU Cores","displayDetails":"hosted_by (Host) > Hardware","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":true},"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"sourceTargetType":"oracle_database","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(oracle_database,oracle_home)"},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion"'||
',"data":{"id":"oracle_home_LlInvPatches_id","_value":null,"dataType":"string","displayName":"Patch ID","displayDetails":"Unclassified ","role":"column","func":null,"UIProperties":{},"targetType":"oracle_home","unitStr":"n/a","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Unclassified ","isKey":1,"groupKeyColumns":["id","lang","upi"],"isConfig":1}},"id":"installed_at(oracle_database,oracle_home)_oracle_home_LlInvPatches_id","_value":null,"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Unclassified ","role":"column","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbTablespaces_tablespaceSize","_value":null,"dataType":"number","displayName":"Size","displayDetails":"Tablespaces","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"oracle_database","unitStr":null,"mcName":"tablespaceSize","mgName":"DbTablespaces","mgDisplayName":"Tablespaces","isKey":0,"groupKeyColumns":["tablespaceName"],"isConfig":1}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbSga_sgasize","_value":null,"dataType":"number","displayName":"Size","displayDetails":"System Global Area","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"oracle_database","unitStr":null,"mcName":"sgasize","mgName":"DbSga","mgDisplayName":"System Global Area","isKey":0,"groupKeyColumns":["sganame"],"isConfig":1}},{"jsonConstructor":"PropertySearchCriterion","data":{"id":"property.orcl_gtp_target_version","_value":null,"dataType":"string","displayName":"Target Version","displayDetails":null,"role":"group by","func":null,"UIProperties":{"useForSort":false},"targetType":"oracle_database","propertyName":"orcl_gtp_target_version"}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3020,'TA_HORI_SORT_COLUMN',null,1,'0',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH 
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET) 
values (3021,'Top 25 WebLogic Servers by Heap Usage','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows the status, Heap Usage, Current Memory Pool Usage and Garbage Collection Invocation time and frequency for Top 25 WebLogic Servers (by Heap Usage)',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"string","displayName":"Target Status","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false,"ignoreCase":true},"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_Jvm_heapUsed.value","_value":null,"dataType":"number","displayName":"Heap Usage (MB)","displayDetails":"Load ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":true},"targetType":"weblogic_j2eeserver","unitStr":"n/a","mcName":"heapUsed.value","mgName":"Jvm","mgDisplayName":"Load ","isKey":0,"groupKeyColumns":[],"isConfig":0,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_JvmMemoryPools_usedNowInMBytes","_value":null,"dataType":"number","displayName":"Memory Pool - Current Usage (MB)","displayDetails":"Load ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"}'||
',{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":"MB","mcName":"usedNowInMBytes","mgName":"JvmMemoryPools","mgDisplayName":"Load ","isKey":0,"groupKeyColumns":["name"],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_JvmGarbageCollectors_invocationsPerMin","_value":null,"dataType":"number","displayName":"Garbage Collector - Invocations (per min)","displayDetails":"Load ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":"operations per minute","mcName":"invocationsPerMin","mgName":"JvmGarbageCollectors","mgDisplayName":"Load ","isKey":0,"groupKeyColumns":["name"],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_JvmGarbageCollectors_msecsPerInvocation","_value":null,"dataType":"number","displayName":"Garbage Collector - Invocation Time (ms)","displayDetails":"Response ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":"ms","mcName":"msecsPerInvocation","mgName":"JvmGarbageCollectors","mgDisplayName":"Response ","isKey":0,"groupKeyColumns":["name"],"isConfig":0}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'TOP_N_ROWS',null,1,'25',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3021,'TA_HORI_SORT_COLUMN',null,1,'1',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH 
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET) 
values (3022,'Top 25 WebLogic Servers by Load','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows the status, CPU Usage, Active Sessions, Request Processing Time, Requests per minute and Heap Usage for Top 25 WebLogic Servers (by Load)',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"string","displayName":"Target Status","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false,"ignoreCase":true},"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_Jvm_cpuUsage.percentage","_value":null,"dataType":"number","displayName":"CPU Usage (%)","displayDetails":"Utilization ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":true},"targetType":"weblogic_j2eeserver","unitStr":"n/a","mcName":"cpuUsage.percentage","mgName":"Jvm","mgDisplayName":"Utilization ","isKey":0,"groupKeyColumns":[],"isConfig":0,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_ServerModule_session.Active","_value":null,"dataType":"number","displayName":"Active Sessions","displayDetails":"Load ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false}'||
',"targetType":"weblogic_j2eeserver","unitStr":"n/a","mcName":"session.Active","mgName":"ServerModule","mgDisplayName":"Load ","isKey":0,"groupKeyColumns":[],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_ServerServletJsp_service.Time","_value":null,"dataType":"number","displayName":"Request Processing Time (ms)","displayDetails":"Response ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":"ms","mcName":"service.Time","mgName":"ServerServletJsp","mgDisplayName":"Response ","isKey":0,"groupKeyColumns":[],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_ServerServletJsp_service.Throughput","_value":null,"dataType":"number","displayName":"Requests (per minute)","displayDetails":"Load ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":"operations per minute","mcName":"service.Throughput","mgName":"ServerServletJsp","mgDisplayName":"Load ","isKey":0,"groupKeyColumns":[],"isConfig":0}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_Jvm_heapUsed.value","_value":null,"dataType":"number","displayName":"Heap Usage (MB)","displayDetails":"Load ","role":"column","func":null,"UIProperties":{"dropDownOptions":[{"value":"cigar","label":"Cigar Chart"},{"value":"string","label":"Text"}],"dropDownValue":"cigar","useForSort":false},"targetType":"weblogic_j2eeserver","unitStr":"n/a","mcName":"heapUsed.value","mgName":"Jvm","mgDisplayName":"Load ","isKey":0,"groupKeyColumns":[],"isConfig":0}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'TOP_N_ROWS',null,1,'25',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3022,'TA_HORI_SORT_COLUMN',null,1,'1',null,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH 
(SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID
,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID,IS_WIDGET) 
values (3023,'WebLogic Servers by JDK Version','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Shows the Java VM Vendor, Target Version and Platform for WebLogic Servers grouped by Java version',4,2,null,null,null,null,1,null,0,null,'',0,'&TENANT_ID',1);

Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'WIDGET_TEMPLATE',null,1,'/widget/visualizationWidget/visualizationWidget.html',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'WIDGET_ICON',null,1,'/../images/func_horibargraph_24_ena.png',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'WIDGET_VIEWMODEL',null,1,'/widget/visualizationWidget/js/VisualizationWidget.js',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'TIME_PERIOD_KEY',null,1,'24',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'TA_CRITERIA',null,2,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false}}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_javavmvendor","_value":null,"dataType":"string","displayName":"Java VM Vendor","displayDetails":"Server Information","role":"column","func":null,"UIProperties":{"useForSort":false,"ignoreCase":true},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"javavmvendor","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[],"isConfig":1,"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"PropertySearchCriterion","data":{"id":"property.orcl_gtp_target_version","_value":null,"dataType":"string","displayName":"Target Version","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false},"targetType":"weblogic_j2eeserver","propertyName":"orcl_gtp_target_version"}},{"jsonConstructor":"PropertySearchCriterion","data":{"id":"property.orcl_gtp_platform","_value":null,"dataType":"string","displayName":"Platform","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false},"targetType":"weblogic_j2eeserver","propertyName":"orcl_gtp_platform"}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"weblogic_j2eeserver_WeblogicServer_javaversion","_value":null,"dataType":"string","displayName":"Java Version","displayDetails":"Server Information","role":"group by","func":null,"UIProperties":{"useForSort":true,"ignoreCase":true},"targetType":"weblogic_j2eeserver","unitStr":null,"mcName":"javaversion","mgName":"WeblogicServer","mgDisplayName":"Server Information","isKey":0,"groupKeyColumns":[],"isConfig":1,"direction":"DESC","inverseNullOrderBy":true}}]}','&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'PROVIDER_VERSION',null,1,'1.0.5',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'WIDGET_KOC_NAME',null,1,'emcta-visualization',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'VISUALIZATION_TYPE_KEY',null,1,'TABLE',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'PROVIDER_ASSET_ROOT',null,1,'assetRoot',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'WIDGET_SOURCE',null,1,'1',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'PROVIDER_NAME',null,1,'TargetAnalytics',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'TOP_N_ROWS',null,1,'100',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'TA_HORI_SORT_ORDER',null,1,'true',null,'&TENANT_ID');
Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (3023,'TA_HORI_SORT_COLUMN',null,1,'-2',null,'&TENANT_ID');

insert into EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE,TENANT_ID) 
select SEARCH_ID,'ORACLE',2,SYS_EXTRACT_UTC(SYSTIMESTAMP),'&TENANT_ID' from EMS_ANALYTICS_SEARCH where search_id>=3000 and search_id<=3999 and TENANT_ID ='&TENANT_ID';
