SET FEEDBACK ON
SET SERVEROUTPUT ON
DEFINE TENANT_ID ='&1'
DECLARE
    V_SEARCH_ID                         NUMBER(38,0)         ;
    V_NAME                              VARCHAR2(64 BYTE)    ;
    V_OWNER                             VARCHAR2(64 BYTE)    ;
    V_CREATION_DATE                     TIMESTAMP(6)         ;
    V_LAST_MODIFICATION_DATE            TIMESTAMP(6)         ;
    V_LAST_MODIFIED_BY                  VARCHAR2(64 BYTE)    ;
    V_DESCRIPTION                       VARCHAR2(256 BYTE)   ;
    V_FOLDER_ID                         NUMBER(38,0)         ;
    V_CATEGORY_ID                       NUMBER(38,0)         ;
    V_SYSTEM_SEARCH                     NUMBER(1,0)          ;
    V_IS_LOCKED                         NUMBER(1,0)          ;
    V_UI_HIDDEN                         NUMBER(1,0)          ;
    V_DELETED                           NUMBER(38,0)         ;
    V_IS_WIDGET                         NUMBER(1,0)          ;
    V_TENANT_ID                         NUMBER(38,0)         ;
    V_WIDGET_SOURCE                     EMS_ANALYTICS_SEARCH.WIDGET_SOURCE%TYPE;
    V_WIDGET_GROUP_NAME                 EMS_ANALYTICS_SEARCH.WIDGET_GROUP_NAME%TYPE;
    V_WIDGET_ICON                       EMS_ANALYTICS_SEARCH.WIDGET_ICON%TYPE;
    V_WIDGET_KOC_NAME                   EMS_ANALYTICS_SEARCH.WIDGET_KOC_NAME%TYPE;
    V_WIDGET_VIEWMODEL                  EMS_ANALYTICS_SEARCH.WIDGET_VIEWMODEL%TYPE;
    V_WIDGET_TEMPLATE                   EMS_ANALYTICS_SEARCH.WIDGET_TEMPLATE%TYPE;
    V_WIDGET_SUPPORT_TIME_CONTROL       EMS_ANALYTICS_SEARCH.WIDGET_SUPPORT_TIME_CONTROL%TYPE;
    V_DASHBOARD_INELIGIBLE              EMS_ANALYTICS_SEARCH.DASHBOARD_INELIGIBLE%TYPE;
    V_PROVIDER_NAME                     EMS_ANALYTICS_SEARCH.PROVIDER_NAME%TYPE;
    V_PROVIDER_VERSION                  EMS_ANALYTICS_SEARCH.PROVIDER_VERSION%TYPE;
    V_PROVIDER_ASSET_ROOT               EMS_ANALYTICS_SEARCH.PROVIDER_ASSET_ROOT%TYPE;
    V_WIDGET_LINKED_DASHBOARD           EMS_ANALYTICS_SEARCH.WIDGET_LINKED_DASHBOARD%TYPE;
    V_WIDGET_DEFAULT_WIDTH              EMS_ANALYTICS_SEARCH.WIDGET_DEFAULT_WIDTH%TYPE;
    V_WIDGET_DEFAULT_HEIGHT             EMS_ANALYTICS_SEARCH.WIDGET_DEFAULT_HEIGHT%TYPE;
    V_PARAM_ATTRIBUTES                  EMS_ANALYTICS_SEARCH_PARAMS.PARAM_ATTRIBUTES%TYPE;
    V_PARAM_TYPE                        EMS_ANALYTICS_SEARCH_PARAMS.PARAM_TYPE%TYPE;
    V_PARAM_VALUE_STR                   EMS_ANALYTICS_SEARCH_PARAMS.PARAM_VALUE_STR%TYPE;
    V_PARAM_VALUE_CLOB                  CLOB                           ;
    V_CLOB                              CLOB                           ;
    V_SEARCH_STR                        CLOB                           ;
    V_METADATA                          CLOB                           ;

    v_count number;
    V_TID                   NUMBER(38,0) := '&TENANT_ID';
    CURSOR TENANT_CURSOR IS
      SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_FOLDERS ORDER BY TENANT_ID;
BEGIN
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;

       SELECT COUNT(*) INTO v_count FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID = V_TENANT_ID AND SEARCH_ID IN (5009, 5007, 5006);
       IF v_count = 0 THEN
        DELETE FROM EMS_ANALYTICS_SEARCH_PARAMS WHERE TENANT_ID = V_TENANT_ID AND SEARCH_ID IN (5009, 5007,5006);
        DELETE FROM EMS_ANALYTICS_LAST_ACCESS WHERE TENANT_ID = V_TENANT_ID AND OBJECT_ID IN (5009, 5007,5006);
        DELETE FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID = V_TENANT_ID AND SEARCH_ID IN (5009, 5007, 5006);
        DBMS_OUTPUT.PUT_LINE('Searches with id : 5006, 5007, 5008 were deleted successfully for TENANT: '|| V_TENANT_ID);
       ELSE
        DBMS_OUTPUT.PUT_LINE('Searches with id : 5006, 5007, 5008 does not exist in TENANT: '|| V_TENANT_ID || ', no need to remove');
       END IF;
       SELECT COUNT(1) into v_count FROM EMS_ANALYTICS_SEARCH WHERE SEARCH_ID = 5020 AND TENANT_ID = V_TENANT_ID;
       IF v_count > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Orchestration OOB Widget already exists for '||V_TENANT_ID ||', no need to add');
       ELSE
       V_SEARCH_ID                          :=5020;
       V_NAME                               :='Workflow Submission Details';
       V_OWNER                              :='ORACLE';
       V_CREATION_DATE                      :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
       V_LAST_MODIFICATION_DATE             :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
       V_LAST_MODIFIED_BY                   :='ORACLE';
       V_DESCRIPTION                        :=null;
       V_FOLDER_ID                          :=8;
       V_CATEGORY_ID                        :=7;
       V_SYSTEM_SEARCH                      :=1;
       V_IS_LOCKED                          :=0;
       V_UI_HIDDEN                          :=0;
       V_DELETED                            :=0;
       V_IS_WIDGET                          :=1;
       V_METADATA                           :=null;
       V_SEARCH_STR                         :=null;
       V_WIDGET_SOURCE                      :='1';
       V_WIDGET_GROUP_NAME                  :=null;
       V_WIDGET_ICON                        :='/../images/func_horibargraph_24_ena.png';
       V_WIDGET_KOC_NAME                    :='emcos-workflow-widgets';
       V_WIDGET_VIEWMODEL                   := '/umbrellaWidget/js/umbrellaWidget.js';
       V_WIDGET_TEMPLATE                    :='/umbrellaWidget/html/umbrellaWidget.html';
       V_WIDGET_SUPPORT_TIME_CONTROL        :=null;
       V_DASHBOARD_INELIGIBLE               :=null;
       V_PROVIDER_NAME                      :='CosUIService';
       V_PROVIDER_VERSION                   :='1.0';
       V_PROVIDER_ASSET_ROOT                :='assetRoot';
       V_WIDGET_LINKED_DASHBOARD            :=0;
       V_WIDGET_DEFAULT_WIDTH               :=12;
       V_WIDGET_DEFAULT_HEIGHT              :=2;
       INSERT INTO EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,
                                         SYSTEM_SEARCH,IS_LOCKED,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID,METADATA_CLOB,SEARCH_DISPLAY_STR,WIDGET_SOURCE,
                                         WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_KOC_NAME,WIDGET_VIEWMODEL,WIDGET_TEMPLATE,WIDGET_SUPPORT_TIME_CONTROL,
                                         WIDGET_LINKED_DASHBOARD,WIDGET_DEFAULT_WIDTH,WIDGET_DEFAULT_HEIGHT,DASHBOARD_INELIGIBLE,PROVIDER_NAME,PROVIDER_VERSION,
                                         PROVIDER_ASSET_ROOT)
   	    VALUES (V_SEARCH_ID,V_NAME,V_OWNER,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_DESCRIPTION,V_FOLDER_ID,V_CATEGORY_ID,V_SYSTEM_SEARCH,
   	            V_IS_LOCKED,V_UI_HIDDEN,V_DELETED,V_IS_WIDGET,V_TENANT_ID,V_METADATA,V_SEARCH_STR,V_WIDGET_SOURCE,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_KOC_NAME,
   	            V_WIDGET_VIEWMODEL,V_WIDGET_TEMPLATE,V_WIDGET_SUPPORT_TIME_CONTROL,V_WIDGET_LINKED_DASHBOARD,V_WIDGET_DEFAULT_WIDTH,V_WIDGET_DEFAULT_HEIGHT,V_DASHBOARD_INELIGIBLE,
   	            V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT);

        V_NAME                  :='TA_CORRELATION_TIME_PERIOD_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='744';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_CRITERIA';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :='{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"_id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"omc_workflow_submission","metadata":{"category":false},"displayValue":"Orchestration Workflow Submission"}}]}},"dataType":"string","_displayName":"Entity Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false},"measures":[{"name":"TARGETTYPEDISPLAYNAME","displayName":"Target Type","description":"Target type such as Oracle WebLogic Domain or Host","dimensionName":"","dataType":1,"disableGroupBy":false,"precision":256,"scale":0,"hide":0,"isAttr":true}]}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.submitted_user","_value":null,"dataType":"string","_displayName":"User","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false,"ignoreCase":true},"targetType":"omc_workflow_'||'submission","propertyName":"submitted_user","measures":[{"name":"SUBMITTED_USER","displayName":"User","description":"User","dimensionName":"OMC_WORKFLOW_SUBMISSION","dataType":1,"disableGroupBy":false,"precision":4000,"scale":0,"hide":0,"subject":"OMC_WORKFLOW_SUBMISSION","cube":"OMC_WORKFLOW_SUBMISSION-COS_WORKFLOWEXECUTIONSTATUSSUMMARY__BASELINE","flexOnly":false,"isAttr":true}]}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.workflow_type","_value":null,"dataType":"string","_displayName":"Workflow Type","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":false,"ignoreCase":true},"targetType":"omc_workflow_submission","propertyName":"workflow_type","measures":[{"name":"WORKFLOW_TYPE","displayName":"Workflow Type","description":"Workflow Type","dimensionName":"OMC_WORKFLOW_SUBMISSION","dataType":1,"disableGroupBy":false,"precision":4000,"scale":0,"hide":0,"subject":"OMC_WORKFLOW_SUBMISSION","cube":"OMC_WORKFLOW_SUBMISSION-COS_WORKFLOWE'||'XECUTIONSTATUSSUMMARY__BASELINE","flexOnly":false,"isAttr":true}]}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.schedule","_value":null,"dataType":"string","_displayName":"Schedule","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSort":true,"ignoreCase":true},"targetType":"omc_workflow_submission","propertyName":"schedule","measures":[{"name":"SCHEDULE","displayName":"Schedule","description":"Schedule","dimensionName":"OMC_WORKFLOW_SUBMISSION","dataType":1,"disableGroupBy":false,"precision":4000,"scale":0,"hide":0,"subject":"OMC_WORKFLOW_SUBMISSION","cube":"OMC_WORKFLOW_SUBMISSION-COS_WORKFLOWEXECUTIONSTATUSSUMMARY__BASELINE","flexOnly":false,"isAttr":true}],"direction":"DESC","inverseNullOrderBy":true}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.next_schedule_time","_value":null,"dataType":"string","_displayName":"Next Scheduled Time","displayDetails":null,"role":"column","func":null,"UIProperties":{"useForSor'||'t":false},"targetType":"omc_workflow_submission","propertyName":"next_schedule_time","measures":[{"name":"NEXT_SCHEDULE_TIME","displayName":"Next Scheduled Time","description":"Next Scheduled Time","dimensionName":"OMC_WORKFLOW_SUBMISSION","dataType":1,"disableGroupBy":false,"precision":4000,"scale":0,"hide":0,"subject":"OMC_WORKFLOW_SUBMISSION","cube":"OMC_WORKFLOW_SUBMISSION-COS_WORKFLOWEXECUTIONSTATUSSUMMARY__BASELINE","flexOnly":false,"isAttr":true}]}}]}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_DONUT_WIDGET_ENABLE_RANKING';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_DONUT_WIDGET_TOP_N_CONFIG';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='none';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_KEY_METRICS';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{"keyMetricsNameList":[],"otherKeyMetricsNameList":[]}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_OTHER_METRICS_CRITERIA';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '[]';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_3D';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='off';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_KEY_NAME_SELECTION';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '["no"]';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_ORIENTATION';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='vertical';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_HISTOGRAM_INSIGHT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='insights';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_HORI_SORT_COLUMN';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='2';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_HORI_SORT_ORDER';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='true';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_LINECHART_WIDGET_ENABLE_RANKING';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_LINECHART_WIDGET_TOP_N_CONFIG';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_LINE_CHART_WIDGET_SHOW_STACKED';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='on';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_QDELINE_DISPLAY_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["insights"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_QDELINE_TIME_PERIOD_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='744';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_QDELINE_TIME_SERIES_CALLOUT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["no"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_QDELINE_TIME_SERIES_ENABLE_CALLOUT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["avg","min","max"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_QDELINE_WIDGET_ENABLE_RANKING';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_QDELINE_WIDGET_TOP_N_CONFIG';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='none';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_ENABLE_RANKING';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_KEY_METRICS';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{"keyMetricsNameList":[],"otherKeyMetricsNameList":[]}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_OTHER_METRICS_CRITERIA';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '[]';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_SHARE_SAME_YAXIS';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_SHOW_CALLOUT';
        V_PARAM_ATTRIBUTES      :=null;
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_SHOW_KEY_NAME_SELECTION';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '["no"]';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_SHOW_STACKED';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='off';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_TILE_SHOW_THRESHOLD';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_STACKEDBAR_WIDGET_TOP_N_CONFIG';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_TREEMAP_DISPLAY_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["insights"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_TREEMAP_TOP_N_ROWS';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='5000';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_TREEMAP_WIDGET_ENABLE_RANKING';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_TREEMAP_WIDGET_TOP_N_CONFIG';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '{}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='none';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_GAUGE_COLOR_VALUE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='#84bbe6';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_GAUGE_MAX_VALUE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='100';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_GAUGE_SELECTED_TILE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='emcta-tile-circular';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_GAUGE_SHOW_SPARK_CHART';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_GAUGE_THRESHOLD_CRITERION';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
        '[]';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_GAUGE_THRESHOLD_VALUE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='100';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LABEL_SELECTED_TILE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='emcta-tile-label';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LABEL_SHOW_SPARK_CHART';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='true';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LINE_CHART_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='none';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LINE_CHART_SELECTED_TILE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='emcta-tile-line';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LINE_CHART_SHOW_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LINE_CHART_SHOW_STACKED';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='on';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_LINE_CHART_TILE_SHOW_THRESHOLD';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_METRIC_TABLE_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='none';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_METRIC_TABLE_SHOW_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_SELECTED_TILE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='emcta-tile-label';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_SHOW_CALLOUT';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_SHOW_PERCENT_CHANGE';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='true';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_SHOW_SPARK_CHART';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TA_WIDGET_TILE_SHOW_THRESHOLD';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='false';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_AREA_CALLOUT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["avg","min","max"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_AREA_DISPLAY_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["insights"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_AREA_ENABLE_CALLOUT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["no"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_AREA_TIME_PERIOD_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='744';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_AREA_WIDGET_ENABLE_RANKING';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='true';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_AREA_WIDGET_TOP_N_CONFIG';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
            '{}';

        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_CALLOUT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["avg","min","max"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_DISPLAY_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["insights"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_ENABLE_CALLOUT_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='["no"]';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_REFERENCE_LINE_NAME_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='""';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_REFERENCE_LINE_OPTION_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='"nameValue"';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_REFERENCE_LINE_VALUE_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TIME_SERIES_TIME_PERIOD_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='744';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='TOP_N_ROWS';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='50';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='VISUALIZATION_TYPE_KEY';
        V_PARAM_TYPE            :=1;
        V_PARAM_VALUE_STR       :='TABLE';
        V_PARAM_VALUE_CLOB      :=null;
        INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
        VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);



        V_NAME                  :='WIDGET_VISUAL';
        V_PARAM_TYPE            :=2;
        V_PARAM_VALUE_STR       :=null;
        V_PARAM_VALUE_CLOB      :=
 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCACMAN0DAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD+134yeNP2oPC3xL8IQ/Br4OeFPip8Kv8AhRf7RPinxwdV8YaZ4J8UT/HPwnrHwOH7O3wz8Pa/qeuSW+kaX8UNA1v49HXNcvPAHibRdK1bwf4SOteJ/A1pdKnigA+I/hf8ev8AgsF44/Z3/bC8S'||
 '+O/2Fvgv8Ev2gPBWifEjVv2L/Bnij40+D/HFv8AGXVtOtNUufhj4Q+JXhj4efFDWPCfhS417+ztPtNd8TzftG+GNNh1vxNDph0zRtC8PX3jPUwD6B+E/wC0F+3J448XTaV8RP8AgnqvwV8Ht8aNX8H2Xi3xH+1n8I/GF8fgnYp4yudN+NOqeGPh7ofiSWy17W7XQ/CdnbfCbT9X1q9stf8AHENnqPjG20Hw9rPihAD72oAKAPH/AIraz8ZdD1X4NXfwq8J+H/GXhm6+MGlaN8e9MvrmC18Yab8Gte8GeOdGXxZ8M5NU8TeFfDcniDwV8W774T+LfHFtr+oX8938C9G+Ltt4E8M+LfivL8P/AAzqoBF8E/HfxV+IHh3UtX+LXwK1b4A6zBdeFl0rwrrfxA8CfEPUtQsNc+Fnw78Z67Pd6j8PdR1fQdNv/BfxC8U+OPg7rNjHqeoWup658MNS8X+GdU1vwL4p8Ka3qAB7LQAUAFAHMeNtb1vw14M8XeI/DXg7WPiJ4j0Dwxr+t6B8P/Duo+GtI8QeOtb0rSru/wBK8HaFq3jTXPDHg7TNY8T38EGiaZqPizxL4e8NWV7fQXOu65pOlxXV/bgH5f8Ai344/wDBX7wT8PUtdP8A2H/2fPjV8UtO+H3xC1m+8QfDv9oLTvA3gnxL8TLTwfLrXw88AaB4E+KGpabrOgeFLnxJ4p8M+Er74la38T7+/wDEOqfC74sT3nw3+GPhrxf8L/FU4B9Xt43/AGx9ctdL8O6X8EPhn4D1fUNG+IWkeIPit4w+Iv8AwmPhvwZ4qtvhlouv/Cnxt4b+C3hQaRr3xb8Gax8Q9cn8GfEPwLrXxo+A/iXw1eeDfFaeG/GPi3wvfeDviN4jAOR+B/xn/bW13xgfAnxx/Y5i8JaH4c+JE/w51T9oLR/i98K7Pwp8TPCOj/Dfxpqj/tI+CvgbpXjr4oeOvh94I8b/ABQ8HaR4W0b4MeMviF4k+J3grw58Wvh9r'||
 'eta14ml0L4oR+CgD7moAKAPjvTfFn7a2gfF3Q9P8a/DD4V+N/gxrep/Ho3us/B7UXtPFngzRB8aP2c/CP7Lw8RTfFL4geEYtV1iX4PeK/2ifix8fk8K+E9VsLST4cab4V+HM+oeJE8NaL8YAD5//av/AGj/APgp78Nta0g/sqf8E3/CP7SHh/Sfirr+k+JIdY/a1+F3ww1bxv8ACjTvgjqOuaV4j8NXni2LS7X4c6vrXxw1vwx4S0p9Z074k3c+heBPHkWv+DfB9h4x8HfEPRgD6M/Yk8f/ALYnxH+AnhrX/wBun9n34d/s3/tBxwaFZeJvBHwv+LNv8W/CerSnwP4Q1HW/FNrd2umpB4GkufHGo+MNBX4bxeLvivD4Zs/DtpLbfF34gWmpQa3KAfXFABQB8Ea/8Xv2+PDPx++L+g6f+yP4M+Kf7OdpqPhS0+C/jvQPjH4P+Hfj67ivfghrHibxBe+K9A8U6/4ittf0O2+OWjW3w21XVI7P4aeIPCWgeLvDviXw34G+Mtjp/inUdGAOg0T4iftuWvjPw5o/jH4AeBr3wzr3w8/ZGGreJvAHi/Qb7SfA3xc8U6l8dL79s2PXLnxh4/8ACfijXfhf8M/Dvg34L6H8JtR8MfD6+8Ya54t+LNtqN3oXijw5pPjT/hXYB0Pir4z/ALSlno1/D4V/Y88a6p4sm8ba34V0aW6+KHwJ/wCELtvDMXxN+K/hbQPitr+pT/FLR/E40K5+Gvw98GfFe/8ABOkeFr3xelz8dfhl8OY2h1XQ/jRr/wAJQDwvw18Sf+CoHxA8c67HqX7PnwL/AGa/h/4f0X9mvxRpY8V+IIP2ltc+I9xrmgfH/wAQ/tN/CzTtd8E/GP4FR/D7xV4Z1DTf2cPh54O8f634H8V+DvD3iHWviL4qs9I+OXhS+sB4EAPvDSNf8aXfjzxJ4a1j4fvpHg/SfBngXXtC+I8PijRtT0vxX4s8Ra98SNO8Y+BLTw4i2vinSrn4e'||
 'aL4W8A+Ib3xDrOmWmh+JE+KVnpfhye7vvCHicW4B3VABQBxPi/xjN4Ssde1FPBvjbxXb+H/AAX4m8Y3Mfg/TLHVb6/m8PQW89l4N0LS59WsNT17xr4uQ6gvhnS9Js7uwM2lT2/iDVfD9xqnhmLXgDhbn41S2curW118Hfjil1o3g3TPFlzDbeCrTVIrm+v/ALct34H0nUtH8Qajo+s+MtEl0+eHU4dK1G78OzeZY3Gi+I9XstS066ugCXxv8aI/Bfw51f4iJ8KvjX4xbSfBmueMV8B+CPAFzrXxG1V9E0TT9cHhHSPDdxqGnxXXjPWItQ/s7Q9Hl1G3gvtbstQ0hr+C9tjG4B1Z+IVhBoE3iPUPDPxAsLKBrES2Y8D+JNZ1/ZfeGLDxN5sPhrwzZa7r92tmL/8AsC/Sz064nt/E9lf6R5LvbiaQA2tB8R/27qPi/TjoHibRT4Q8RWnh03uvaaLDTvExuvCHhXxcdb8IXaXNwuueHbX/AISn/hGLvVFW3WLxf4c8VaMInGkC6uQCt4z8X2/guw0y+n0Hxf4jfVfEOieHbew8G+G9U8TX8Ems3qW8ur6nFp8bQ6T4e0OyF1q+t6zqdxaWsFlZPZ2Rv9evtG0bUwDoNPvV1CCS4Frf2YjvtTsfJ1C3ktLhzpmpXemtdRxOxL2N8bQ32mXI+S9024tLyMBJ1AAL2B7/AJn/ABoAMD3/ADP+NABge/5n/GgDj/iH4uHw+8AeOfH3/CL+MfG//CEeD/E3i/8A4Qv4eaMfEvj/AMX/APCNaLe61/wi/gfw59qsv7f8Ya/9i/snwzon2y0/tXWruysPtMHn+agBwnhf41R+I/E+ieF7n4VfG3wpJ4g1L4v6dYa54o+H91b+GLdfhL4j0TQ7bUdb13SL/WbTwzpvxY0zWm8Y/CCbxH/ZU3ijw5o+t2uq2/hzxdZR+FrgA9rwPf8AM/40AGB7/mf8aADA9/zP+NABge/5n/GgD5n8IftM2PifX'||
 'fi9o+qfA79pnwHafCPx9YeAV8R+L/gx4hk0L4ovqPieHwpD4w+EI8Hz+Ldb8Y+AYb25ttTv/E82i6Rb6b4Ykm8VX8Nv4f0/VdQsQD3LxR4im8O6L4i1Ow8MeJ/GGpaD4a1bxFaeFvC9tp41rxRNptpdXFr4a8O33iPVfDvhJ/Euu3FsNO0m01rxPothHd3NrNrOp6Rpsj6hGAUtc8W3OnaJJquh+C/GnjS+S7022Xw1odnpGh63NFfa02j3l9HP8RNd8DeHRaaHDBe65qSza/FeXGi2azaFaazfat4fsNYAL/g3xF/wmPhDwr4u/sHxL4V/4Snw3ofiP/hGPGWmnRPF/hz+3NMtdT/sHxVowuLoaR4k0f7V/Z+uaWLq5FhqdvdWguJvK8xgDpMD3/M/40AGB7/mf8aADA9/zP8AjQAYHv8Amf8AGgAwPf8AM/40AGB7/mf8aAExyevQdz7+/tQAuB7/AJn/ABoA8r+K918XrTwvr178HLTwre+KtG8P61rGl6P4v0qfU7Txprdrpt3LofgzTrq28c+CovDVzq2o28FreeJ9burnStLivbSQWN8v26TTgD5I0b9oj9uaw0z4ay+NP2AvFurahqmu+MZfifF8M/jD+zfeyeG/CukyfFix8L2+h2Pj348eCbS98U+I7vTPgtq2n7fEOp6JN4Y8V+PZ/ENz4H8TeF9I8La2Aep2nxU/aug0G71TxB+y3Ade1L4Zabr2ieEPA3xV+H3iiLw18Sb7x7e+Gz4H8W+MPGPiL4WwaxDYeC9U8MfEfxTqvhnwyuj6BZ+H/iP4W8Ja58UPEUXgKDxiAdZN8S/jxZ2HjeVP2cdc1++8P+OLC08Jwx+PPhf4aPjz4dal8RNf8L32t6ZFN448Sw6R4u8J+FdEj8f/APCP+JtS0PSvGvgrxL8P76LXvBnxL174j/BT4KAEnxR+Ifx28OWXiO1+H3wE1fxrqi6vptv4R1nRfFHw11HSpvD39u/CrTNe1'||
 'jxLoHjf4k/Bu+s9et9N8ZfEXxD4c8LaVr2oabrekfB/WV1nxr4T8QeLPA/hrXwD1zxi/jW30GS88DroV7r+nH+0G0bW7O6Nt4ogs7aeaXwzYalDrWmp4U1HXbhbeysvFV/F4ksPD/mveXnhrXUT7PQBl+CfF/ivxRcXy+IfhV4v+G9pBoHgvVrGbxbrfw71O5vtU8S6RNqXiLws9r4B8a+NIbTWPh5erBoHiO8e9l8O6tq0sk/grW/FGhQjWZgD0GgAoAKAOD+KerePNA+GPxH134WeFLPx38TtF8B+L9W+HHgfUdVs9C0/xl4807w9qN54Q8KX2t6jeafp+j2fiLxDDp2kXWq31/Y2enwXj3dzeW0MLzIAeGfCT4nftTeJB8C4/iz+zNa/DiTxh4P8e3fxtuLH4n+BfEtv8JvGGgWvgabwLYxQ6Tr99P4htfiBPqfji1ex8Lt4stfCk/h6D+1fFs1rLYXmvgH1fQAUAFABQB83+EvHn7Sct78Q7Lxx8AfDdlb2N/8AFW5+EeueF/i3pN/a+LNB8JeMX0j4faf8T9K1TRbG/wDhn4p+Jnhq/wBN8R+G/wDhEJ/jH4fj0fRfFN98QtT+FPil/DXw31kA6fxt4x+K2j6p8S9P8I/CzXfFFpovwWbxj8OtdtH+Hg0rxV8Vre58aQSfCzytf+MPg/XJddv4rLwXeae+u6N4B+HkNtqd2t/8YYbu4urTwwAc9o/jP9oPX7ywmtPhLB4WsBP9t1fTfirqPhHw1cjSLi8+OWnW2k6Nrnwo+J3x9ju/FVlc+HfgjqurNqXhzSvDf/CF+N73WtK1jUfGtz4g+GHwpAPXvAWoeLNX8C+C9V8e6BbeFPHWp+E/DmoeNPC1nf22q2fhrxZe6PZ3PiPQLXVLO5vLTUrbRtYlvNOgv7W7ura8itluILmeKRZWAOsoAKACgAoAKACgBO5+g/m1AC0AcH4z8PeNdch1JfCHxCl8DXFx4F8c+HtPlHhbR'||
 'PEsOneNfEEegjwZ8QpINV8t76X4fvp2sND4We5g0TxOniKdNbydN06SIA5lvC3xsZYQPi94TQpofh6CZk+EjlpvEtn4c1/TPE+qjzPiE6xaDrviC88N+J9J8Oqral4dOhajo0/irX7HXo30YA0PFOh/FX/hHbqbwZ420d/GcOkaj9gtvEeh2tp4M1DxDcabpdhYSagun2mpeItN0GwuLbVNaWytL/UNTl1fVI1uNUuNDsI9DlAKt/4a+NHlAaL8VvB0NxHeeFLiOTxB8JrrWYJbax0K50vxrYXkGj/EnwpJLB4l1M2XiXw9NaXNhd+EdTivbO+n8X6HeW2laaAdt4P0HVfDPh+10bWvGvib4h6jb3WrXE3izxhaeDbLxBfRajrF/qdnY3Vt4A8JeBvCyWugWV5b+HtJey8NWd7No+lWE+u3mta/JqmuakAV/Gmj+K9d0q0sPCPjEeBb7+3tAu9S1yPw7p3iS/l8O6fq1re69omk22sTf2Tpuo+IdOgm0WPXdQ07XY9Hgvbi9t9GuL+O0ntQDc0q31K1tZYtV1KLVbptS1m4iuobBdNSLTbvV7670bTTbpcXIkl0bR57HSJ78yK2qzWMmqPb2j3jWsIBpUAFABQBx/xD0XxZ4j8AeOfD3gHxp/wrfx1r3g/xNovgv4if8I5pvjD/AIQLxZqmi3tj4c8af8IjrUsGj+Kf+EW1iez1z/hHNWnh03W/sP8AZl9LHa3UrgAwF8PfFQeN/DGuP8SdDk8FacvxJtPFHgaP4fx28niO08R3/h+/+G+oW/id/E13qOj+IPhpBo+raJeTwW8ugeOdN8Xapd6j4d0nV9K0C8sQD0+gAoAKACgD5xbwf+1Bp2h/FdrT42fDbxR4hvNY8Raz8CrfWfg5e+GNL8M6bqHiafxHo3gj4vanpPxB1248fWWk6WLT4ead4x8FaF8MdVsvC7Xeva7oPjXxp9n1hAD1y38PeJo9Ys7qfx9rFzolhfajqS6Qd'||
 'F8LQ3ervqtz4rkfRPEOrx6Nibwt4ftNZ8M2/g+38Oaf4W8V2svg6G58Z+M/Hi67q1u4BB418M+KfEPgy/8AD3hX4j6/4A8TTR2zaf4+0zRPBmvavY3VncxXaefovibw7qfha+sNSMA03W7UaPaXk2i3V/FoeqeHdbfT/EGmAF7wHo3iXw54H8GeHvGfjG4+InjDQvCnh3RvFfxAu9D0fwxdeOvEul6RZ2Ou+Mbnw34eht9A8PXHifVILrW5tD0OCDR9JkvmsNMhjsreBFAOroAKACgAoAKACgBO5+g/m1AC0AeWfEeDwbqEN34f8Q/EfUvh9rXi/wAHeJvBeg3mjfEFvB2v2tv4y1Xwh4Qn8Q+FLCa9XTbrxlpfivxD4E0fwl4oudF1fU/DPiXxLo+jaFJaTeNr3TtfAOKh8B+Dvt/hjSf+F6/Ei41nwTLa+ANBsG+Lo/tEeP7P4VTSvN4q02Ex/wDCx/Hd14AnX4j3vhX4nWnjLw880MHxLj8Fw3CtrDgGj4k+D/hTxraTXMvxN+L2nySeANF+G9jrHhD43eOPDS6dENb0bxPY+K7e00DXrPw9qHxF1m/tPDiy+L9d0rWNW1Lw+Z/CkTHwj4z8Y6J4oAOa+L/wBsvG/wAUPhp8Z4v2h/2hvgrqvw/J0BvDvw6+K9tpHwj+Iq+I5rzQtD0r4i/Cfx3ofjT4a+IdVj1LxTeWnh/VdP8ADuj+LL/V9R0KO61jVbvwt4CTw2AaupfCPwz4o0Gy1LRPjT8YdH0TVfiJoHxf8L+IPC/xk1a7tRrGqazfavFpelatq8+v2nib4W+NG8SjSofhR4hk8S/Cy30g6BYeBvCnh4aVoUloAZQ8L/Cf4rfCXTvD3gP4/eNn+Gaat4Q8PX3i74Z/tB6vrPiDxEnh220nwxbeCrv45yeIPEvxM07UPE8ieH4PEmteEviD4d+Juv6+51NvFyeIPFfie88RAH0Po2j2uhWc1lZ3Gq3MU+q69rDyazres'||
 'eILxbrxFrmo+IL63hv9cvtQvYNKtL3U7i10HRILiPR/DWhw6d4c8PWOmaBpWmabaAGrQAUAFAHAfFfRdL8SfC34leHdb8deIfhfouv+APGWi6v8S/CPie38FeK/h3peq+HdRsb/AMdeGPGV3FPaeEvEPhK0nl1/RfE91BNb6DqWn22qzRSR2jIwBxHh7whoN34x+H/jzRPjn4+1+3l0X4ueJPDvheLx9oGt+BPiF4O+LGv+CPFM2pT6PHpU58TaD8Nr2Dw3bfCbxTpN/HqHgbw54svfC9vr934Y8YXOlX4B7tQAUAFABQB8nad+z+mtx/EHWdI/ai/aE8Ry6/4x8X33gy7X4maHcaB8GNch+LOn+NPEfg7wvpvg7w74dtPGGg+HviD4ItvCFx4X+N1z8UtR8K+CbDxZ8ENJ1Dw98PfFvj7whrwB7bqU/g/SPEOueINb8eyacfBngqbWNd0TUvG66X4e8IeF9c1DXtQvvHPiPTDfWYjtNUPhjU7PTfEfi6a90rw5p/gzV7TwO3htG8bHVwDl9bi+FvjHw3b/AAgT4p6hZ3Dtp/h/Tz4T+NOu6N8UBqPhy68VLZW8fi/SPFMfj/U9attQ+FPjlNaTUtV1G68TN8P/AB9pnjOLX7DTPG1g4B23w00PTfDHw58AeGtF8WeIPHuj+HvBPhXQ9J8deLPE8njbxV4003SdCsLCw8WeJfGcrPL4t8QeI7W3i1jWfE8rtJr2o3lzqrszXZJAO2oAKACgAoAKACgBO5+g/m1AC0AeZ/ED4XeAfiTdeGG8d2Opasvh7X/Duu+HtMTxX4t0jRB4m8HeO/Avxc8La1d+H9E1zTtD1rW/DnjH4V+GNX0bU9a0/UL7TtNg8S+GrWeLwv448caL4jAPmbxv4U/Yy8G6zpnhjxre6l4e8aeHnj1DwKs3jj40WPxLQWPwD+JXwlcfBXXdP19PHeq23hH4Lax8XtT1Gx+EmpXtt4B1nVfiF8ZtRt9B+I994'||
 'g8dSgHoPiTwN+zbe+P7ebUor/RPHFzqfhnwOi+GPEvxN8ExXs+meGfEP/CJ+HbyDwbq+h6FfaLo+m399f6TbX0c2gaR4rj8J6zD9l8baZ4JvLQAwPGGofsy/FX4UavD4tufiPp3wzsfEnhHwVeXgP7RnwfvfDeufBzxJb+NPA+vaNrGmDwR4t8I2VrrCaR4h8PfFrw/eaTovxA0lvC93ZeMfFHh2Xw6XAOP+DfgL9i74DeD9O8D/CVvFXhnwD4RuLbxlYeC5fGv7QniTwj4Zv8A4o+IPhp8S9Hm/wCEX8V6/rmjaNquveJNL8MeK/CugTWFvqGn6lqfxOuvDemWMnjD4yDWQD2/4gw/BXwd8KtN+Hvj7UPFSeBILXwJ4K8Pyy6/8WfEXjPVtV1u8Ph7wBF4W8e6XqGq/E/xT8TrPVtPt9c0fxFoHiTVfiZ4W13T9H+JH9q6Rq1lpPiaIA77wN4R+Huk6r468Z+CdLjtNU8f+KLufxxqayavv1rxL4QluPBlzLLa6pM0Vs2nvo82mI+m21rY3cdsl3AbqGWG5kAPRqACgAoA8i/aBk+FEXwF+Nsvx5CH4Gx/CL4kyfGYSR+IZoz8KE8G603xEEkXhFX8VyofCA1gNH4YR/ELrldFVtSNsCAfPXwy+FP7Evwq8cfs+fDr4aWOkaB4y+Guh/tAaF8B9BtPF/xC1KPTbLQJvhx4S+PWiNNqmv6ho2veI9O2+BluNM8aXOq+K1sbXVfEPhWA2Fj4v1SAA+4qACgAoAKAPz98Jyf8E87a8/aG1bwXffDDT7lvE3xY8KftcS6FqWtabGPFvi74lw6J42b9pu2tbm3t49abxQt5B8OfE3xchW58PfDG48W3nwc1fS/g1f8Aiy4uAD6M1jSfhZ4v8aeIba8vPiKPF3j3wBqHwo8RaZoniX42+GI9N8FWeq/EJLbW7nR/DuqaRpHwyvdU1Oy8eW/gH45R2nhTxJ4qFnFa+APiBq1tb6DEgBzvi'||
 'jwh8B/h34HXx74+0bxt4t8J+Gbe2vID8Q1+Nn7QGq+GxfyfELTLvxDY+D/F7/EXxRoeo/2F8YPHvh/xl4ss9CtNTsvhVdjw34y1W3+F/gTRdP8ADQB6Z8Fbz4d6j8G/hLqHwgSaP4TX3wz8B3nwvjuLHxFpc6fDu58LaVP4JSfTfGFvaeLdOmXw0+mLLY+KLW28RWjhrfW7eHU47qNQD0ygAoAKACgAoAKAE7n6D+bUALQBzuteJLXQ57C2m07xDqM+pXFnDCNE8Paxq8FvHda94e8PPdajfWNnLp2mwWVz4kstRu1vruC6GgWXiDX7e2uNK8Na/dacAeaWnxws7zX9M0SP4YfG6G31DUfAOmTeIrv4Ya5Z6BpM/wAQvCXiLxXY3Gpy3Pl6oNO8NSaJpvhbx9qdjpV/p/gfxb4v8O6Z4hubK2tvFmoeFwDUsfi1Bf8AxA0bwNH8PPizb2Ov+GZfEem/ES+8B6jY/D9J47LStSj8MazfXUsXiPwt4muNO1OaaK08V+GdE05L3R9V8P3OqQeKFsNEvwDzXUf2ptPtNDv9csPgP+1Jrot/Efwz8NabpOnfAzxNY65r9z8SL6zsbjVLDTvEsmgNpnhz4cC4ur34meIfFcnhvStBsdLvJtMudda50eLVQDf8R/tBw6HNMmnfBf8AaE8XwQSaMZbzw58Lb6CEWmt+DvEPjOC/it/FV/4Z1K7jsbfQIvD2s2FlY3Ot6P4x8Q+HvDGoaVBqd3eRWAB7P4o1qfw34Z8ReIrXw/rviy50DQtX1q38LeF4tOn8TeJZ9L0+4vofD/h2DWNT0XSZtd1mSBdO0iLVNY0nTpNQubdL7U7C2aW6iAMXwt4807xbqeuaXZaH430qTQrLwvqL3firwN4p8KaZqtn4t0ZdZ09tD1HX9LsLXVL3TlE+meKNFhkGveEdZtm07xLpely3WnG9AO3oAKACgDj/AIh+L/8AhX3gDxz4+/4Rfxh43/4Qjwf4m8X/A'||
 'PCF/DzRP+El8f8Ai/8A4RrRb3Wv+EX8D+HPtNl/b/jDX/sX9k+GdE+2Wn9q61d2Vh9pg8/zUAPMvBXx7h8aa14M0Wf4OfHzwbJ40k+Kn9n6n43+GN5pejaFH8MNT0HTobnxjqljf6rb+DV+Jmn+If7f+FkPiE6fe+JdJ0jxDZ6ha6H4i0yTQJAD32gAoAKACgD5f0v476L8RZfjT4I8Zfs7/H/Q/Dfg7V9c8BXD/EP4Of2v4O+OOiHWf+EK1rUvh9ZeHtR8Yy+I/A2qTX8G1vG+j+E21/wnf3Piez0q/wDB+m+IdX0oA9p8VeOIPC9n4rli8MeN/FOpeFvBGo+OE0Pwr4W1DULzxPBYRak0Xhjwpqt6um+FNT8b6nPpps9O8LT+I7HUHlvtNubtbTTbxL5QChefETdpn2/w14F+I3jC6E1iraLZ+GD4N1NbW81bW9Hkv/O+LN78OtGeHT5/D9/d31nFq76wNJn0TV7XTLrTvE3hu41YA6Pwd4j/AOEw8I+FvFv9heI/C3/CU+HND8R/8Iz4x0v+xPF3hz+29MtdT/sLxVovn3X9keI9I+1f2frml/abj7BqdvdWnny+V5jAHR0AFABQAUAFABQAnc/QfzagBaAPGPirrPxr0rUfByfCLwt4f8T2l5r3hS38aL4jW1srTTPDN38YPg9o/jTV7LXD430fUItd0L4M6v8AGDxR4c8OweCvEWn+JfEHh7TF1DxR4ZuNM0zwh8UADH1H4h/Gbw/4d+HU6fAfxT8RtcvdO8JzfFD/AIR7XfhT4DutEm1bwT441DXn8KeGPEvxc8RaTqGt+HvHvhzwf4d1zwle/E7/AIR/T9C+JFrrnhX4rfEibwfr1hcAHf3OvePLHxLNpjeA11nw9ear4cttJ8S6N4h0iAabp2oW+vzeJL/xXpWtT6ffwQ+HDoumw2jeGU8S3uv6j4y0OyTSdM0zSvE3iLTADkdF8RfHT/hT9td+Ifh74ab476d4U8L2u'||
 'v6NpPiC3h+GGufEG78G+HdS8W6j4E1W61G68SP8PNH8YanregaVH4ztPCvi3Uk8N3jyWMGnXuj+IdTAIr/4g/F5ZL2XR/gJ4hu4W8J6JrGlWWt+NPhrok48Qyta3HiDwrq2o6Z4y8UxQ6pa2etWVnps2n6dfeHLjW/CfjqOfxSmjy+BtY8WgEC+JPj7b2nji7m+H3h/U00fXIJ/BVpaahp2leIvF/hmy+I/jBfEOnyaRdeMdS8OaP4iufhZpfhmL4c6lqXj200rxX4t1/T9e8fad8HbC78Q+CfAQB7PpF7fX9rLPqOj3Oh3Eep63ZR2V3dafdyz2Onazf6fpesJLpl1eWyW3iHTbW01+ytZJU1Cys9TgstWtbHVbe9srcA06ACgAoA4X4o3/wAQNL+GfxF1P4TaHovib4p6d4E8XX/w08N+I7w6f4e8Q/ECz8P6hceDdD16/W7sGsdF1bxHHpthql4L+yNtY3E8wu7Yp5yAHh3wp8eftY6vB+z/AB/F/wCBHg7wjeeJ/BHi1v2hp/DHxE0rW9P+G3xB0nRvBN34Uk8LI96954g8NeLtZn8e6S2k2keuXugpa6FfX/ih4IJv7cAPqugAoAKACgD5y8K+Mf2mVT4nweOPgt4CkuNN1P4o3fwX1Hwl8VGWy8a+HtB8V39r8N9J+KOna14X+1/C7xT4w8M3eg3MF74SvPjFoE8WmeKde8St8NdVm8P/AA3vADsfFWufFa01n4jWPhrwv9t0qz+EVprnw41yPSPDmqx3nxWjuvHMOp+F9S0/U/jB4Evde8+2i+H95pGkXS/DXw4VfXYNR+MFrLqsQ8JAHJWevftIajrWjT2Xg/whp/h06nfXXiTS/H9tbeFNZg8Ova/tBRaNpnh7xB4A+J3xrstR8Vpr2mfs4Q69NqnhjRvD1r4J1nx74x0m71fxdrMPwk+FwB694Du/F9/4H8GX3xB0vTND8e3vhTw7d+N9E0W5N5o2j+L7nSLObxLpe'||
 'k3ZuLs3WmafrL3tpYXJu7oz2sMUpuJy3mMAdXQAUAFABQAUAFACdz9B/NqAFoA4nxjoHi3W7HV4/CXj278Eanc+C/GWgaRdp4e0DxHYaX4t16DSl8LePbnTtWthcand+BbiwvZbLw9/aljoGvQ63qEGv2149vpNxpoBz0Hhb4sLB4fF18WNJlu9H0Sxi1OW3+G1lbWvivxRF4Xu9K1DUtctZfEt3PaeGbzxLJZ+LLfw14ZvvD+s2P2afQn8aXlhdrJagGB4o8A/G7U9YhvvC/x/j8LaV/Z62d1olx8KPCviCNrn/hXfxB8PyatZahcajY3trqB+IuufDr4ixx3Tajpaaf4A1jwM+mzWnjp9c8NAGdYeAP2ioNU1G+v/ANojw3f2V54512az0ZPgbplnZaT8JtU8S+ItY0vw9aXC+PJtUuPi/wCGtD1PQfCOm/FTUb+8+Ht7p3hlNU1z4Aapr2r6hqVAHQ+PPA3xb17WvB1/4F+OV14B0nSPi1oPjLxnoNx8OfB/i+Lxl8MNP8Mx6PrXwbstQ1Aaff8AhW18Q6/F/wAJa/j2CTVvFel3lxd6TYv/AGK1nZ2IB61qMN7caff2+m3senajPZXUNhqEtot/FYXssEiWt7JYtNbrex2s7RzvaNcQLcLGYTNEH3qAYHhnTPFGkg2eveI/+EptotE8Nwx6xe2OnadrV5r9nZT2HiW9urPRdO03R7bT9We00zW7W2toZJbXV9T8Q28b2+ixaHp1iAdXQAUAFAHH/EPRfFniPwB458PeAfGn/Ct/HWveD/E2i+C/iJ/wjmm+MP8AhAvFmqaLe2Phzxp/wiOtSwaP4p/4RbWJ7PXP+Ec1aeHTdb+w/wBmX0sdrdSuADnoPDPxTTxt4b1yf4paVP4M01PifbeI/AqfDuzhfxNb+KdY8Oal8NLyLxT/AMJJJqWh658K7DSNa8Py3drbXWiePNL8V6jcaz4bsNb03QtX00A9RoAKACgAoA+apfA/7'||
 'T9lpfxTnt/jx4H8Ra3PqPirV/gXpl18IIfCOkaFbaj4pHirw34M+M+tQeKfGd7490zRLC0tfhlb+K/AGhfCjWI/Aepa9rGr6R4p+I7aH4v0YA9lg0HxMniC3v5/HWoz+HrMXk8Xh9dD8Ow3OpXup33iCa4t/EGtjT3kudB0SxvvDtj4OsPD1h4W1yxfw/d3njLxP49bXWh00Ap+MPC3irXfA914a8MfEzxF4G8UtbWS2PxFsND8Ea7rkF5YTQXPn3mh+IPDN94QvbXV3t/sWv2lvoOnTS6ReajD4dvvDGrvpuuaUAaPgPRvEvhzwP4M8PeM/GNx8RPGGheFPDujeK/iBd6Ho/hi68deJdL0izsdd8Y3Phvw9Db6B4euPE+qQXWtzaHocEGj6TJfNYaZDHZW8CKAdXQAUAFABQAUAFACdz9B/NqAFoA8q+Kvxt+CvwP07Sdd+Nvxi+GPwc0bVdTk03RtW+KHxC8KfDzStZ1RLGaeTS7G+8WavpFpqV5HaCW9axtpZZ0jg+1GMJCWAB53fW3wh+LhsPGWg/tD69daP8VINa+F3gS5+Gfx4GneFdX8U+E9Q1zxLrMXw5/4RTV103WPiN4Uuvhv4xuNdjsZdY1FND8KeNvDnivT73whp3iPRIgDn/Dvwt8EeErXVPBl5+1H8X/EniL4X/DTw3F4vufGnxytrrxZ4Y8J33j7xH4/0H4k+PbPSV8PxWura4PDGueE7Hxv4q0v+zde8EeCtU8N3kOs6ZbeModVANLRPgL8N/GcWi+ILf40/Hfx7/wis+n+FLjWtB/ah+Kuk6VqXjP4Rtf/AAx8aTeJ9L+FfjTwn4Qv/FN1rXhy90T4p+GJtGh8O2nj3QNXv18I+HfGs3ie9vwDf+A/wb0b9l34cHwZqPxw+NXxXsbvxXZXEXjr9pz4ry/EnxudY8Tjw54S0rw3beLtZtdLkFlrHiCGz/sLw7HGVbxR4lvLHRYY49RsNLtwDoPjgfA1zoHhP'||
 'QfH3xl1H4M6Z4r+JHgzwzpN1o3xE0j4X6z8R/E+pX8jeH/hHpPiq7+z+JVv/HN/bpbxaR8ONY8PfEHXFspNM0XWYrO51WzvQD1bStLh0i1ltLe41K6SXUtZ1RpdV1S/1e6WbW9XvtaubeK71K4uriLTbS41CW00bS45FsNE0iCx0XSre00uws7SEA0qACgAoA85+MWn6Fq3wj+KeleKfiFrXwj8M6n8OPG+n+I/iv4c8WWfgHxD8MdCvPDOqW2r/ELQfHWopJp/gvWvBenyXHiTS/Fl9HJZ+HL7TYNYukeCzdSAee+DvD3gzUPFfw28d+FP2hPGniyx1/w/8X/iD4N8NwfE/wAPeLPAvxR8AfFrX/APiy48Q2enfYb+TxT4L+Gl5eeD7f4SeKfDWpRL4C8M+OB4VtNdufC3jQaTfgH0RQAUAFABQB8j+EfgVp+qN8UPE3hf9q79oPxlD4y+JniHUdFuo/ip4U8R+Hfg3rvhX4uJq3jn4ZeArDS/CaaRN4f0jx14LvPhx4l8KfExfiBrnhDw/p/in4V6XqPhfS9Q8TaRdAHtPifxB8NtJufG0/iz4kad4ei8CfDqfxZ48s774jJ4WtvAHw88Ry+K5ZfiN4oeDWdKu/DOiX48D+LItF8ca9dW+n6HF4F8SjwhqOivpfip5QDlNX8SfBDxzY2vwdT406f/AGxdapZ6BYaX4P8AjneaB8UJ9b8N6p8RTb6Pb674X8XWHxAvtXtNU+A/xcs9b0+XULq88QL8IPivo3i6HWrHwt8QrGIA9B+GGm6Po/w1+HmkeHfGWsfEbw/pXgbwlpuhfELxD4oXxvr/AI70ex0DT7XTPGWueNEZk8Xax4nsooNb1PxQjMuv3t9PqqsRdg0AdzQAUAFABQAUAFACdz9B/NqAFoA4rxjpfhDXbHUPDHi/SZNZ03xpoeq+ENQsH0vV9QtNR0LX/smj61o00+n280djDqcGpxvqKefaTTaTY3usXDnSvDN/f'||
 'aWAfL3gv9nH9jHUdRs/Cvw50zStM8R/A/UYblvC/gT4qePvCnjP4Sa/8RdF8ceMdObxD4f8O+NtI8UeBvFGueF/jR8RdU0GPxHZ6Zr1p4V+Jni6DRktNC8T6rBdgFLS/h7+wh4L8S+Hv2XNLX4ZeAvGk/g25+HnhL4NJ4xv/A/i/wAceDdNv4vjf4jtPDfh6XXtH134qWj6lPfeOPiN4k0pPFNzqd1qXjI+PtXu5NX8YW12AW9e8b/sXaV4ev8Axb4y8X6N4Tsvi78T/hjZ3w8da/478FeL/EXxTXxnqmvfCTUG8M+K7vRvHGl63bXfhy48Q+DfEcekadFZfCD4d6JrunalD8E/hb4evPDIB2WieIP2SviL4ttLXwT4o+HHxB8T+INT8FfEe70/4Z+J18YwPd+NNG8OfGD4Z/FTxvpvgPUdT0fS9M8W6N8CvDOv/Df4neN7ey0fX4dA0/RPCPiG7k8VjStfAPoPxXeaBa6Hew+KEdtA1OGfSdVLWOoXljFp9/bTxXsusz2FvOmkaLHZ+edS1rUpLLSdNt9019f2seJKAOO+GumfDBoLPxf8NfEUXijT/Ffw7+Gn9k63Y/EbW/H+i6x8ONNsNal+G+u6DPf+JNf0mXSdbstV1m/t/F+kATeO2d9U1bWNfntILqAA9UoAKACgDyr473nws074H/GXUPjmlpJ8E7D4U/EO8+MUd/Yavqli/wALLXwjrE/xBS80zw/b3mvajaN4STV1uLDRLS61e8hL2+m2897JDEwB4V4C8CfsaeCfGP7P/g7wBp3hTQPGPgzQ/jMnwI0Kw1PxNBdaNaaXZeA/DXxr0Bbe6vjbHxLpdlqPgy38Q+EPGHm+LdPFle6hb6RDJ4d8R3emgH2VQAUAFABQB8EaDef8E520v9pTXtI1r9nfw5pjePfGHw//AGvbm98Q6B4GFx8SPF3xHu/CV5Y/tD2ur6hoU934o17x1a3OifCrXfiJby3t3pOspb/B7VG8H'||
 '+MYP7ZAPpTUrn4e6j4h8QXs6/EOPxFrfhefwHraaJafGTS7mHw7pl58TLi0voNP8Pw2kXh+4kvfDXjpfCXxH0y203V9WlufD9t4T8UXv/CV+BItZAOd8V2nwU8KaI2uePdE8VeIdD8MS3ipc+N/Dvxa+LFv4feeH4peHNZ16zg8Raf4wfS4pvDnin4jaD4k8Y2cMEMnwx1nT9K13WW+HM/hCCgD0H4Qah8P9W+E3wv1T4TRrF8K9S+HfgnUPhpEmm6xoqR/D+88NaZceDY00fxDa2Ov6SqeHJNNVdN1yxs9YsQBa6na297FPCgB6JQAUAFABQAUAFACdz9B/NqAFoAYW2so2O2+QqSoBEeImffJkghCUCAgMd7oMYJYAHiXjb4033gvxt4b8DJ8FPjh4wuvGFxqtt4e8R+CfC3h7WfBLyaH4euvEept4l8Wz+L9P0f4cW6wWp0rSrv4nz+C7TxT4hntdD8Iza/qE6xAAyLn9oRrHx74V+H+ofA39oe2vvFnxH174eweJLb4bR694C0K20TQ/GfiOL4ieKvG/hjXdb8PeHvhxr2l+G/DK6DrWoXseq3GufFHwZ4QvdC0/wAY6F8W/D/wxAKfjj9pD/hBJ7+2u/gL+0n4jlsPiV4Y+HR/4Qf4XDxhBeWvimC7vbf4kWF5omu3VldfDXR9NsZ73xPrS3A1jw7O1poGqeH7fxXqOm6BdgHZ/Db4tXfxIXVJF+Enxg8CxaL4t1fwbqEnxJ8N6H4Tb+0NBk1621TVdLtpvE91e+JPCQvdGsrXSPGXhi21nwx4rj8TaDq3g/Vdf0BNf1bQgD0fxFq8ugeH9d16DRdZ8RzaJo2qavD4e8OwWlz4g16XTbKe8j0XQrbUL3TLC41nVHhFjpkF7qWn2kt7PBHc3tpCzzxgHLeEtd0vX/EPiS5bwH4k8IeK7TR/BVprWoeJfC9tYz6xo13pl94i0PS7PxjpM2q6B4ng8I6tr/izR9R0fTfEeov4X'||
 '8RtrtwbSHSfEuia34kAPQqACgAoA4/4h+L/APhX3gDxz4+/4Rfxh43/AOEI8H+JvF//AAhfw80T/hJfH/i//hGtFvda/wCEX8D+HPtNl/b/AIw1/wCxf2T4Z0T7Zaf2rrV3ZWH2mDz/ADUAOG0/4pafr/jbwr4V1L4T/FbTLu81b4wro/ivX/h68vhPw/qnwo1bTfCK39/4msbrVYPDSfFfw94q1XX/AISazci0s/F3hDTvFGn397oniJrfwtqYB7TQAUAFABQB8rWf7SWh+LZ/i14b1b9n39pS20X4d+MV+Gnii68U/AnXG8O+Nodc8aaf4Bh174e2YfUL34tfDnUtP1S68Zan4k8F6R4g0jRvh/pmq3/iwaNqLWGh6gAfRmo6zd2Qu1tPDeu6zPa6VqWpLb6cdEgN3PZl10/R7S61rWtJ099V19o5Rpqy3sOn2IRJPEuoeH4rqykuQDK8R+KtU0PwqPEWn+AfGXi3Ut+mo3grw43hCHxUn2y9t7XUXMvifxb4b8Junh+3lutT1Iw+KZDf2WnXMfhceItTutI07UwC34J8TN408GeEfGL+HPE/g9/FnhjQPEz+EfG+mRaL4z8LNr2lWmqN4c8XaPBeahBpPifRDdHTNf0yG/vorDVbW7tY7y5SITOAdPQAUAFABQAUAFACdz9B/NqAFoA5XxDrHiDTLnTIND8J6j4jS9urFL+7t7/QLCx0izl8TeFtI1Ce6fVdasdQmubPQdZ1zxVb2mnaXfxXtj4S1ewa9tNcu/DekeIwDyGf4kfHuPUPAs0P7N81x4b1h3j+ICj4seBYvG/giRPhN4r8cB9E8PSN/wAIl4202T4h6b4R+DEV63xE8LaifFPirUfEs2gQfDfwwfG2tgGjrfj7436RruuadZfAAeKNFtPDnh+80DxF4f8Aip4SgTWvFV1b6zdeJtAvdJ8UWvhq+0XRdGGn6XYaR4mU6pda/q/iC3iuvDOg6Ppuo67EAaPjfx98U'||
 'vDWkWd94Y+A/iL4h6lLP8M1vdE0Dxz8OdIuLS38T+IL2y+JEkN54y8R+GtPu5vhh4cso9cSI3VunjW+1bStF0WW3C6zqWkAHNfBv4ofHfxt8PfDut/Fr9mLW/gl8SL7WdSsfEfgOb4q/DH4h6FoGkWHjfRNFtNdtfHHhPWSdZGt+CNXu/HFhpaeGbO6tLvwz4k8J6rJZ3Z8Kap4uANTw94/+Nd18Ok8TeKfgDcaN49Piu8sW+GujfErwVr86+DLbWpfsviRvFV3caD4eGv6l4ThF7H4US4ks7LxreWvhO48VP4Yiu/iTCAdz4S1/wAe6t4j+IWm+LPh9b+EPDvh/XrCx+H3iWHxjp3iOT4iaBcaLZXd/r93odnp1ldeCrjT9cl1DRV0W/udVkvLWzttYjvYxfPp9kAd9QAUAFAHHfEXWfF3hz4feOvEPw/8GL8R/Hug+DfE+s+Cfh43iHTfCK+PPF2l6JfX3hvwY3ivWEk0jwwvijWYLLQz4h1WOTTdFF9/aV8jWttKpAPLfAnxG+O2t6t4FsfHf7Oc/gbTfEafFFvFut2nxV8DeK4Ph9/wi+o+HE+GA1aws30+/wBan+Kmjal4gu7u38KRa9b+ANY8OHR9V1HVtP1Sw8RSAH0HQAUAFABQB83+E/iZ+0Je6z8U7Txt+zK3h3RPDviXWNP+EmteG/jJ4G8V3XxN8Maf4kj0Ww8ReJ9G1C28JH4ZXmuaTcw+LtN0KLUvHTx6BY61BrN/oviuHRvCuugHqfizxF4z0q38Xx+FPh7feK9U0nwFf+IvCRn17w1oHh/xb4zgTV10/wCHsuqXWq3OtaFfahcWmlebr194Wbw1YWWqfaDqt1d2tzp0IBnT+J/iTfWCy+Hvhj9j1QTWbyWHxG8XaD4Y082M2qeJrC8WHV/AMnxduX1Wys9I0TWo7WXQ4NNvNN8UaTENYt9Yi8R6R4XAOq8G6l4i1rwf4U1jxf4aHgvxbq3hvQtS8UeDl1iy8'||
 'RL4T8RX+l2t1rfhoeINNVNO10aFqUtzpY1iwRLLUxa/bbVVgnjAAOkoAKACgAoAKACgBO5+g/m1AC0AVJ4biSWB4bx7aOOTNxEsMEguI8xSBA8qM0L7ohE0illNrPdoIluntL2xAOd0ix8c22u+IZtb8S+GNV8Kz3WjHwjpVj4N1LSPE2j2FvoKW2vQ+KfE0njbVNH8VahqviYPrOmX+jeC/A9pomiuPDtzpOuXq/8ACSsAYVxovxZX4iafq2n/ABB8FL8K3N3J4g8C6v8ADHVdQ8byyHQksdNi8KfErTfiZoOj6BYw69EmvapD4i+GXjm91G3nvtGsdR0SOSxvdOAOK1HwH+0DF4d03RfDf7QOgpqdr400DXtR8X+NfgrpPiTxDqnhO21nVNf8UeBPsvhXxn8OfCllaaw82jeDtB8QweGW17w38OdO1Ky1C48U/ErV7b4raMAac3hP486noXivS9S+MvgnRtV1LwX4e0/wh4l8BfBi50jUPC/xBt9CubbxZ4r1Sx8d/FH4naL4o8Jaz4le01jw54FTTdA1bwvotvN4e1Tx/wCMb26XxLbAHr2owX1xaSppt8unXwV2tbmW0S/tROI3EK31m0ltLdWPmlGure0vtNvJokaK31KydxOgBheHI/HFube18XXnhTVlt/CnhSO61zw5pur+Hjq/jhDrMfji8t/Cup6r4mHhzwpcCPw/eeFNNk8Y+KdXtDd6zp2r6re/2dZapqgB1dABQAUAcf8AEPRfFniPwB458PeAfGn/AArfx1r3g/xNovgv4if8I5pvjD/hAvFmqaLe2Phzxp/wiOtSwaP4p/4RbWJ7PXP+Ec1aeHTdb+w/2ZfSx2t1K4AOebQfiyvjbwbq6fEHw1ceCdOX4gaf4z8HnwM9leeIbDW/7Euvh1rdl4i/4SHULnT/ABX4Em0S+0nWBb21t4W8aad411zUW8PeH9Q0Lw3BAAeo0AFABQAUAfPMfhb9qDSfDnxYgsvjH'||
 '8IfFXiXVPFGpa58ELrxX8D/ABJpVl4M8M33inUNcXwD8TZfCvxntR8Q/wCzvDt3b+BfDXjnwzpPw5v9GtNO0/xR4q8NfEfWo9Vg1wA9Qi8NeJEvbaSX4i+I5dPtdW1PVhaf2R4Kju9Qi1R/HG3w3q98vhgwyeFvD8PiXwuvhddG0/QvF0U/w50GXxZ4y8ZRa34xtvEIAzxp4Z8U+IPDWp6T4W+JHiDwDr1y4n03xVpuieDNeudMmivLm+gtZNI8S+HdS0m/0mfzLfStTt5LeHVrjQ7Zo9N1zRtfnbxGgBf8CaP4k8O+CPBvh/xl4wn+IfjDQvCvh7R/Ffj+60PSPDNz458SaZpFnZa74wuPDegRQ6D4fn8TapBda1NoeiQxaRpMl61hpsUdnbwqADqqACgAoAKACgAoATufoP5tQAtAHJ6/448EeFtR0jSvFHjLwv4b1XXHjbQdM13xFpWjX+tmfxH4S8EQjS7K/vLa41RZfGPxB8C+E4ltYpw/ijxp4Q0NAdW8RaLa3gB5j4e+Htj4k8Y2/wAbvDfx6+KPijwp4x1rwf8AEbw34Y0fxr4V1b4MXfhi3+EXiXwJpei+FrXSvDTvqHw88XnxnD8Yb+4j8SajqOufEfRPB2v2fiSPwnpNv4WnANrTvhjpv/Cxrfx3a/Ev4oX8HhzQW8Ir8OX+IV7e/D6z1D7NoDprmtaRtfW9Y8XQ6ZYxATeJ/EGqWssev6lq11pc+rX1rqluAfP1z8AtL+IngKLxZo/7cf7TM/grXPHngz45aZ8RfA3xb+FNpotx4I8IW1zfaX4B0jxNoPwy/wCEen+B2t6Z/ZUviySFp/EfjWz0K31DxJ491S41vxnfeKAD6b8O+CtL0DxR4jvbXxn421a41PTfCnneFNe8b6nr2meHbLR457DSdQ0jT7+4m1PTn119LuxrOoXV7cnxTe2V/Nqcl9creswBkal4++EfxD0vx94F034veGDeW0B8DeL5PA3xM0rTf'||
 'GXgjVfGXiHxH8LdKtxqmgawut+C/F93470HxL4Q8LXG+w1lPH/hvVNG0nPiLQ7u1tgDqvDHg6Twvqev3sXi/wAaa5p2tw+HI7Tw74n1e213TPDM3h/RINBnu9A1C704+KvO8S21nYX3iSHW/EetWNzrdrPrunWml6rrfiW71oA7OgAoAKAPN/jJY6Bqfwh+Kum+LPiJrHwg8Lah8N/HNj4l+LPh7xdZeANf+F+gXfhjVLfWfiJofjzUkk07wTrHgnTpLnxLpni6/jey8N3umQazdI0FlIpAPPvBvhjwbJ4u+HvjDwv+0F468UW/iDR/jL8RfCfhV/ilofi/wb8TPA3xX8R+A/FV9rllp1zZald+IfA/wv1DUPCFp8Jtf8LanbW3w88NeOIvCVprE3hXxhFo96AfRNABQAUAFAHyN4E+BOnzXPxb8V+Ef2s/2iPGVv8AEP4t3uuW07fFTwZ418OfCDVvAXxYa78f/CH4ZadN4K1LQdG8KJ4q8J6x8K/G/hbxdbeLvEvhPRrXxJ4G0TWPCGox3zQgHtvizxP8MY7PxlYeKfiHo+gW/h3wVqmr+NWHxKl8HXnhDwVrcfiuK78Xatqem+INH1TwjZIngTxsdI8aSXmmS6BJ4L8VT+H9X0yfw/rUlsAc1r/in4KeK7KD4bah8YtKivJ9csdKgsPDfxsuvCPju41vQtc8dNa6DFrvg/xZofjeW9h1f4MfE3S9W0pNTN3r8Xwv+JWg+KI9XtPD3jqyQA7j4X2eiaf8NPh3YeGvGup/Enw5Y+BvCVnoHxF1vxPD421nx9oltoGnw6V411fxnbE2/i7U/FNikGu3/ie3Jh1+6v5dViJju1oA7mgAoAKACgAoAKAE7n6D+bUALQBzPiHwx4b8StpcfiOyi1FdP1bS9U0m0uru6S1XW9B1jSfFejajFYJcxWtzqukar4bsdS0+7kgmu7KK2vobeSOxv9VhuwDwz4q2H7Kf9r6Zpfxm8SfDGw8S6'||
 'Ro1tf6XH4++Itlo/iuz0bR/h38drVtZgudZ8SWeviI/Cuf9o8axrpmaXVPA9l8WJtavbzRdE8SyWIB2GqN8Bp/HNrJrVz4CsviEPGPhmwsY9TvdP0XxHq3jbTfDvjHUPCVpZ2t1PZXfiTVbfw3qfju90OKCLUi1pbeI7izDPoV6+ngHMeE779mjxB8MvFceiW/hDSvhfpmuReFfGGieJNHu/AejaBqXg3QvDXhXRdN1Xwv4ysvD8/hzSm8F6N4J1DwNI+mafoPiv4eX/grx54Mm1rwZ4t8OeIdYAKVvpf7Jep+FdYmt9a+EuqeCE8MeBNP8QzL460jUfC3/AAi954a0e++GcuuSnXp9Je1vPCa6XqfgjVdRZprrRdSn1TQryS11+/ub8A6XXPiB8Dpr7xZ8Mde1qK4v/C/ib4XnxDo15a+KbibTfFfxp8Zyz/Ci50zVjavv1O+8aRDU/D194c1GV/AN7pthrXn+F7fRrC8swD1Hwh/wiH9lXf8AwhFxolzo3/CUeN/tsmgXttqFivi8+NNfPxBt557Se4ij1u08e/8ACS2viWyeRbnTfEcOq6dewW15az20QB09ABQAUAeYfG7U/hfonwX+L2s/G+LTpvgvpHwv8f6n8XodX0i/8QaTL8L7Dwpq134/i1PQdKstS1TW9Ok8KRasl7pGm6df3+pWxls7OyuriaOCQA8k0Lwz+yV4X+IvwZ8HeGbLwBpXxD8LRfGub4OadoN1OJ9Pm0KDwj4X+OOkWV5p9w+lz65awa74VXxP4V1u6n1ub7E2uRaVK/hTVNR0cA+qqACgAoAKAPhbR5v+Cd2raP8AtMX2l3X7NOmaU3jzX/Cf7X7z3fg7wfI/xHu/HV94eYftCQ6hLot6/im98Z2F3B8OvEXxAjN/e215Bf8Aw01SXQfEFndaiAfS6674E1XXy0SeLo/EfimTUPhveRW2hfErSNRs7Pw7d/EuS31XXLWDTrJ/BXha8vfCHjxPAnxb1'||
 'qLQfDHi+5m0e38BeM9al8YeDY9cAM34iyfCvwT4Mv8Axf8AEfStV13wp4b84XX9qeGfHXxautLj1BPEXhnVNVt/DNvpnjHXUs20Txl4m03xN4istINpa/D281JvEOow+A9LkksQDovhHrHgDxD8KPhjr/wohjt/hbrnw98F6x8NYIdD1XwxDB4A1Pw3pt74Ohi8N69p+k654ejj8Oz6ciaHrOlaZqukqosNR0+zvLea2jAPQqACgAoAKACgAoATufoP5tQAtAHi978aPBumaneaNqPjTwHp+sWF1FZX+k3viPSrTU7G9n0G78UQWd3Yz6rHdW11N4Z06/8AEcVvNEksmhWN5q6I2n201wnV7GH80vvX+Rjzz/u/+Av/AOSKY+PPw+a2F4vxC+G5tDJoUQuh4s0Q2xl8UN4VTwzGJxrHlGTxE/jrwQmhJu3au3jHwquni4PiHSBeL2MP5n9662t081967hzz/u/+Av8A+SK0f7Q3wymtpb2H4m/C6WzhTVpJruPxp4fe2hj0CTxpDrsks662Yo00WX4b/ESLVmdwunSeAvGiXhhbwtrgsT2NP+Z/fHpv06WYc8/7v/gL/wDkipH+0t8I5oLi6h+LXwjltrPTn1i7uI/HnhmSC10mPw/qfi2TVLiZdeMcGnJ4V0XWPEz30rLbL4f0nU9ZaUadYXVzEeyp/wAz7/FHbvsHPP8Au/8AgL/+SOk0P4yeEvE962m+GvGHgfxDqKRXUz2Gh+INM1a9SGxg0K6vZWtbDVLidYrO28U+Gbi6kMYW3g8R6FNKUj1fT2uH7GD2lJ/Nf5Bzz/u/+Av/AOSG6z8ZvCHhy6ubHxD4y8C6FfWWj+I/EN5Z6z4i0vS7q00DwfY6Jqfi3XLm3vtUgmg0fwtpviXw5qHiPU5USy0Sx8QaJd6nPawarYSTr2NNbya36x6b9OnUOef93/wF/wDyRyUn7UvwVhvbTTZfjP8ABiLUb/RL7xNYafJ8RfCaXt74c'||
 '0zTI9a1LxBaWreIRPc6Jp+jzRatfarDG9haaZLHfz3Edq6yk9lT/mf/AIFH/IOef93/AMBf/wAkd7F8UNEnsvDWoweIPCs2n+NHtI/B1/FqtpJZeLJNQ0i71+wTw1dJqBg1173QbC+1u0XS5LprnSLO71KEPZ280yP2MO8vvX+Qc8/7v/gL/wDkjmoP2hPhpdI8lr8S/hfcxx2VnqTyQeMtAmRNO1FPDL6ffu8etMq2V8njTwc9ndEiC6TxZ4ZaCRxr2lm6Xsaf8z++P+Qc8/7v/gL/APkjOsf2m/g9qcNtcab8X/g/qFveXFza2c9j4/8AC93DdXVkdFW8traWDX5EnuLRvEfh4XMMTNJAde0USqh1Sx889lT/AJn98f8ALzQc8/7v/gL/APkjqYfjF4TuLC91WDxf4In0vTr+z0rUNSh1/TZbCw1TUbLTtS0/Tb28TVGt7W/v9O1jSNQs7OeSO4urLVNOuoI3gvraSV+xh/NL71/kHPP+7/4C/wD5IxtE+Ofwz8aWH9veG/Hvwv8AFmmaP4gsdF/tnRPFPh/XbDSvFOs3x8KaZpP9o2Gr3VvY+INV1LU28N2Nh50Wo319qB0e3iluLs20i9jTe0m/nH/IOef93/wF/wDyRzN5+1z8AtOmnt9Q+PPwJsbi1stB1K5gvPij4LtprfTvFSRyeGNQnin8So8Nl4jjmhfQbqRVg1hJY20+S4V1JPZU/wCZ9PtR67dOvQOef93/AMBf/wAkdTf/ALQHw30rVYNB1T4kfDLTdcuvtX2bRr/xhoNnqtx9i0zQdavfI0641qO8l+yaN4q8MatdeXC32fTPEeg38uy11jT5bg9jT/mf3x/y8194c8/7v/gL/wDki3dfHHwLZXcthe+O/h7aX0M1tbTWd14o0e3u4ri98SX/AINs4JbeXV0mjmu/F+l6n4VtomQPP4k06/0OJX1SzuLWM9jT/mf3x/yDnn/d/wDAX/8AJD7X42+Cb66tbKx8c'||
 'eALy8vr9tKsrS18S6TcXV5qi2Ojao2m2tvDqzy3F+um+I/D2otZwo9wLHXdGuzH9n1SxknPY0/5n98f8g55/wB3/wABf/yRg6z8c/hHfafc6N4h8e/CK80rXdJ8QQ3mlaz4p8M3Gn6zoeneD7Hxf4qiubG+1d7bUdJsfAOu6b4o8QJLFNZ2vg/WbHW9RCaLqNvczHsaf8z++P8AkHPP+7/4C/8A5IqXv7U/wT06G/uNQ+NPwWsLfSpdJg1Se9+I3hK1h02fX7HRdU0KG/ln8QolnLrWm+JPDuo6THcNG+o2Ov6Ld2azW+q2Mk57Kn/M/wDwKPXbp1ug55/3f/AX/wDJHrcfii7lRJYlsZI5EWSOSNZXSRHAZHR1uCrIykMrKSGBBBINP2EO8vvX+Qc8/wC7/wCAv/5Id/wkt9/zytP+/c3/AMfo9hDvL71/kHPP+7/4C/8A5IP+Elvv+eVp/wB+5v8A4/R7CHeX3r/IOef93/wF/wDyQf8ACS33/PK0/wC/c3/x+j2EO8vvX+Qc8/7v/gL/APkg/wCElvv+eVp/37m/+P0ewh3l96/yDnn/AHf/AAF//JB/wkt9/wA8rT/v3N/8fo9hDvL71/kHPP8Au/8AgL/+SD/hJb7/AJ5Wn/fub/4/R7CHeX3r/IOef93/AMBf/wAkH/CS33/PK0/79zf/AB+j2EO8vvX+Qc8/7v8A4C//AJIP+Ekvs58q07f8s5u2f+m/vR7CHeX3r/IOef8Ad+5//JB/wkt9/wA8rT/v3N/8fo9hDvL71/kHPP8Au/8AgL/+SPN5vBPgy4fxFJceEfDE8njBL6PxbJNoGlSv4oTVNE0Lw1qaeIme0ZtbTUfDnhfw1oF8upm6F3onh3QtKuBJY6TYQW+1l2Wu/n/Vl9xJHc+BfBt5DeWt74X0O9sL/R/D/h+70q9021u9Gm0XwreahqHhzTv7GuI5dKS20e91S9ubFI7NDDJJEQSLW1ECsu3ZfdsBc0Hwp'||
 '4W8K2cOneF/DWgeG9PtrjXLu3sdB0bTtHs7e68T6zN4i8S3MNrp9tbwRXHiHxBc3Gu65NGiyatrM82p37XF7K87NJLZW9AMCw+FPwu0u+1PVNM+G3gHTtT1u38V2ms6jYeDvDtnfavaePNc/wCEm8cW2p3dvp0dxf2/jPxJ/wAVD4rhu5JY/EWuf8TbV1vL/wD0ilZdl16Lrv8Af17gX9K+HvgHQbDW9K0PwP4Q0bS/E0mqzeJNN0rw1ounWHiCXXb7VNT1uXW7OzsobfVpNZ1LXNb1DVXv47htQvtY1S7uzNcahdyTFktklffQC1d+C/B2oauviC/8J+Gb3Xksdb0tNbu9B0u51dNM8S2+g2niPTl1Ka1e9Wx8QWnhbwxa63aCYW+q2/hzQYL+OeLSNPW3LLsvu77/AHgcvo3wa+F3hvxbonjfw34J0Tw54i8N+FPGHgnRJvD0Emh6Xp/hrx/4s0Tx34ysIvDmlS2nhx5vEHjDw9pfiG/1SbSZNWbUkvZor6Matqy3pypO6VnZrTs3d6bb6hf9Pw2PRLuys7+JIL60tr2CO5sr1IbuCK4iS8028g1HTrtI5kdFubDULW2vrKcAS2t5bwXMDxzwxurA5XWfhx8PPEVp4isPEHgLwXrtj4v0y00XxZZ6z4W0PU7TxRo9hquta7Y6T4it72xnh1rTLPW/EniLWbSw1JLm1t9V17WtQhiS71S+mnVlrotd9N/X7394Ddb+Gvw68S6LfeHPEfgDwV4g8PanJrMupaDrfhXQtV0XUJfEVzqd74glvtLv7Cexu5NdvNa1i71l54JG1O51bU570zy3908o0no0muzQGjN4N8IXNnc6dceFfDc+n3l3rOoXdhNoely2d1f+I4dWt/EN7c2r2rQT3euwa9rkGs3MqNNqkOs6tFfPOmo3izOy7AY2hfC34deFvFF94z8LeDdA8L+JdW0ptF1zUvDVhF4fHiLT11JtXs08T2WkCz0/xNdaNqNxq'||
 'lx4c1HXrTUdR8MnxF4ti8PXemQ+MfFMesKyve2r38/Xv/w/cDJ8U/BH4S+NNV0vXvEXgHw7d6/o2v8Ag/xNYeILWz/sjX11bwD4t1Dx54QN1rmjPp+q6hpui+MtX1jxHDoeo3d1odzqms6zc3unXLavqIuRxT3S0af3O6/HUL/r+OjO8ufD+gXms6Z4ivND0i78QaLb31po2u3Om2U+s6Ta6osS6nbaZqcsD3thb6isEC30NrPFHdrDELhZBGgVgW49PsIraeyisbOOzuZL6W5tI7aFLa4l1O4nu9SlngVBFLJqF3dXN1fPIjNd3FxPNcGSSaRmAMmbwh4TuNS0TWZ/C/h2fV/DN7rmpeG9Vm0TTZNS8P6j4mjuofEl/ol89s11pN74ghvr2LXLqwlt59WjvLpL+S4W4mDll2/p7gbsMEFsjR28MUEbSzzskMaRI091PJdXUzKiqplubmaW4nkI3zTyySyM0jsxAPPI/g38IYV1dIvhX8N4k1+58GXmurH4H8MIut3fw4g0+2+Hl1q6rpYGpXPgO20nSrfwZPeCaXwvBpmnxaG1jHZ2yxqy7Lp07bfdZW7AegWlpa2FrbWNjbW9lZWVvDaWdnaQx21raWttGsNvbW1vCqQwW8EKJFDDEiRxRoqIqqoAYFigAoAKACgAoAKACgAoAKAP/9k=';

   INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,  PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID)
   VALUES(V_SEARCH_ID,V_NAME,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);

   INSERT INTO EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE,TENANT_ID)
   VALUES (V_SEARCH_ID, V_OWNER, 2, SYS_EXTRACT_UTC(SYSTIMESTAMP), V_TENANT_ID);

   DBMS_OUTPUT.PUT_LINE('Orchestration WIDGET has been added for TENANT: '||V_TENANT_ID);
   END IF;
    IF (V_TID<>-1) THEN
        EXIT;
    END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('FAILED TO  ADD  Orchestration WIDGET DUE TO '||SQLERRM);
  RAISE;  
END;
/
