Rem
Rem emaas_savesearch_seed_data.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data.sql 
Rem
Rem    DESCRIPTION
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    REX       11/14/16 - Add new widget
Rem

DEFINE TENANT_ID ='&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
  V_SID                   VARCHAR(255);
  V_COUNT                 NUMBER(38,0);
  V_TENANT_ID             NUMBER(38,0);
  V_TID                   NUMBER(38,0) := '&TENANT_ID';
  CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_CATEGORY ORDER BY TENANT_ID;
  TYPE SEARCH_ID_CURSOR_TYPE IS REF CURSOR;
  SEARCH_ID_CURSOR SEARCH_ID_CURSOR_TYPE;
BEGIN

  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       IF NOT TENANT_CURSOR%ISOPEN THEN
        OPEN TENANT_CURSOR;
       END IF;
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;
     END IF;
  SELECT COUNT(SEARCH_ID) INTO V_COUNT FROM EMS_ANALYTICS_SEARCH WHERE SYSTEM_SEARCH = 1 AND OWNER != 'ORACLE' AND TENANT_ID=V_TENANT_ID;
  IF (V_COUNT > 0) THEN
    DBMS_OUTPUT.PUT_LINE('The owner of OOB widgets with below id will be correct to ORACLE');
    OPEN SEARCH_ID_CURSOR FOR SELECT SEARCH_ID FROM EMS_ANALYTICS_SEARCH WHERE SYSTEM_SEARCH = 1 AND OWNER != 'ORACLE' AND TENANT_ID=V_TENANT_ID;
    LOOP
      FETCH SEARCH_ID_CURSOR INTO V_SID;
      EXIT WHEN SEARCH_ID_CURSOR%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(V_SID);
    END LOOP;
    CLOSE SEARCH_ID_CURSOR;
    UPDATE EMS_ANALYTICS_SEARCH SET OWNER = 'ORACLE' WHERE SEARCH_ID IN (SELECT SEARCH_ID FROM EMS_ANALYTICS_SEARCH WHERE SYSTEM_SEARCH = 1 AND OWNER != 'ORACLE' AND TENANT_ID=V_TENANT_ID);
    DBMS_OUTPUT.PUT_LINE(V_COUNT || ' wrong owner of OOB rows have been corrected successfully for tenant_id='||V_TENANT_ID);
  ELSE
    DBMS_OUTPUT.PUT_LINE('There is no wrong owner of OOB under tenant_id='||V_TENANT_ID);
  END IF;
  IF (V_TID<>-1) THEN
    EXIT;
  END IF;
  END LOOP;
  IF TENANT_CURSOR%ISOPEN THEN
    CLOSE TENANT_CURSOR;
  END IF;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Failed to correct wrong owner of OOB due to error '||SQLERRM);
    RAISE;
END;
/
