Rem  drv: <migrate type="data_upgrade" version="13.1.0.0" />
Rem  $Header: emcore/source/oracle/sysman/emdrep/sql/core/13.1.0.0/emanalytics/eman_data_upgrade.sql /st_emgc_pt-13.1mstr/2 2014/02/03 025059 saurgarg Exp $
Rem
Rem eman_data_upgrade.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      upgrade_058_059_ddl.sql
Rem
Rem    DESCRIPTION
Rem      EM Analytics framework schema upgrade sql file - introduce TENANTID column.
Rem
Rem    NOTES
Rem      None
Rem
Rem

WHENEVER SQLERROR EXIT ROLLBACK
SET FEEDBACK ON
SET SERVEROUTPUT ON


DECLARE
  V_Version EMS_ANALYTICS_SCHEMA_VER_SSF%rowtype;
BEGIN

 SELECT * INTO V_Version FROM EMS_ANALYTICS_SCHEMA_VER_SSF  WHERE MAJOR=1 AND MINOR =0;
       DBMS_OUTPUT.PUT_LINE('Schema already upgraded');
       RAISE_APPLICATION_ERROR(-20000, 'Schema already upgraded');
    EXCEPTION
         WHEN NO_DATA_FOUND THEN
          DBMS_OUTPUT.PUT_LINE('Upgrade is in progress...');
    END;
/




BEGIN
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_LAST_ACCESS DROP CONSTRAINT EMS_ANALYTICS_LAST_ACCESS_PK'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH_PARAMS DROP CONSTRAINT EMS_ANALYTICS_SEARCH_PARAMS_FK';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH_PARAMS DROP CONSTRAINT EMS_ANALYTICS_SEARCH_PROPS_PK'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH DROP CONSTRAINT EMS_ANALYTICS_SEARCH_FK2'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH DROP CONSTRAINT EMS_ANALYTICS_SEARCH_FK1'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH DROP CONSTRAINT EMS_ANALYTICS_SEARCH_U01'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH DROP CONSTRAINT EMS_ANALYTICS_SEARCH_PK'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY_PARAMS DROP CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK1'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY_PARAMS DROP CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_PK'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY DROP CONSTRAINT  EMS_ANALYTICS_CATEGORY_FK1';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY DROP CONSTRAINT EMS_ANALYICS_CATEGORY_U01'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY DROP CONSTRAINT EMS_ANALYTICS_CATEGORY_PK';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS DROP CONSTRAINT EMS_ANALYTICS_FOLDERS_FK1';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS DROP CONSTRAINT EMS_ANALYTICS_FOLDERS_U01';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS DROP CONSTRAINT EMS_ANALYTICS_FOLDERS_PK'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_LAST_ACCESS ADD TENANT_ID    NUMBER(*,0) DEFAULT -1'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS ADD TENANT_ID    NUMBER(*,0) DEFAULT -1'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD TENANT_ID    NUMBER(*,0) DEFAULT -1';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD PROVIDER_NAME VARCHAR2(64) ';
EXECUTE IMMEDIATE ' UPDATE EMS_ANALYTICS_CATEGORY A SET PROVIDER_NAME = (SELECT NAME FROM EMS_ANALYTICS_CATEGORY B WHERE  B.CATEGORY_ID = A.CATEGORY_ID AND B.TENANT_ID = A.TENANT_ID )';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY MODIFY  PROVIDER_NAME VARCHAR2(64) NOT NULL';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD PROVIDER_VERSION VARCHAR2(64) DEFAULT 0.1  NOT NULL';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD PROVIDER_DISCOVERY VARCHAR2(64) ';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD  PROVIDER_ASSET_ROOT VARCHAR2(64)  DEFAULT' || '''' || 'assetRoot' || '''';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD TENANT_ID    NUMBER(*,0) DEFAULT -1';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH ADD TENANT_ID    NUMBER(*,0) DEFAULT -1';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH ADD IS_WIDGET NUMBER(1,0) default 0 not null constraint EMS_ANALYTICS_SRCH_LCK2 check (IS_WIDGET between 0 and 1)'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH_PARAMS ADD TENANT_ID    NUMBER(*,0) DEFAULT -1';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_PK PRIMARY KEY (FOLDER_ID,TENANT_ID) USING INDEX'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_U01 UNIQUE (NAME, PARENT_ID,DELETED,TENANT_ID) USING INDEX'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_FK1 FOREIGN KEY (PARENT_ID,TENANT_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID,TENANT_ID)';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYTICS_CATEGORY_PK PRIMARY KEY (CATEGORY_ID,TENANT_ID) USING INDEX';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYICS_CATEGORY_U01 UNIQUE (NAME,DELETED,TENANT_ID) USING INDEX'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYTICS_CATEGORY_FK1 FOREIGN KEY (DEFAULT_FOLDER_ID,TENANT_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID,TENANT_ID)';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_PK PRIMARY KEY (CATEGORY_ID,NAME,TENANT_ID) USING   INDEX';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK1 FOREIGN KEY (CATEGORY_ID,TENANT_ID) REFERENCES EMS_ANALYTICS_CATEGORY (CATEGORY_ID,TENANT_ID)';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_PK PRIMARY KEY (SEARCH_ID,TENANT_ID) USING INDEX'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_U01 UNIQUE (NAME, FOLDER_ID, CATEGORY_ID ,DELETED,TENANT_ID) USING INDEX '; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_FK1 FOREIGN KEY (CATEGORY_ID,TENANT_ID) REFERENCES EMS_ANALYTICS_CATEGORY (CATEGORY_ID,TENANT_ID)';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_FK2 FOREIGN KEY (FOLDER_ID,TENANT_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID,TENANT_ID)';
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH_PARAMS ADD  CONSTRAINT EMS_ANALYTICS_SEARCH_PROPS_PK PRIMARY KEY (SEARCH_ID,NAME,TENANT_ID) USING  INDEX'; 
EXECUTE IMMEDIATE 'ALTER  TABLE EMS_ANALYTICS_SEARCH_PARAMS ADD CONSTRAINT EMS_ANALYTICS_SEARCH_PARAMS_FK FOREIGN KEY (SEARCH_ID,TENANT_ID) REFERENCES EMS_ANALYTICS_SEARCH (SEARCH_ID,TENANT_ID)';
EXECUTE IMMEDIATE 'ALTER  TABLE  EMS_ANALYTICS_LAST_ACCESS  ADD CONSTRAINT EMS_ANALYTICS_LAST_ACCESS_PK PRIMARY KEY (OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,TENANT_ID) USING INDEX'; 
EXECUTE IMMEDIATE 'DELETE FROM EMS_ANALYTICS_SCHEMA_VER_SSF'; 
EXECUTE IMMEDIATE 'INSERT INTO EMS_ANALYTICS_SCHEMA_VER_SSF VALUES(1,0)';
COMMIT;
END; 
/

BEGIN
   DBMS_OUTPUT.PUT_LINE('Upgraded successfully.');
END;
/
