Rem
Rem    DDL change during upgrade
Rem    MODIFIED   (MM/DD/YY)
Rem    MIAYU       03/25/2015 - created, place holder now
Rem
Rem

Rem    VINJOSHI    28/05/2015 - jira issues emcpssf-116 



ALTER TABLE  EMS_ANALYTICS_SEARCH  DROP CONSTRAINT EMS_ANALYTICS_SEARCH_U01;

ALTER TABLE  EMS_ANALYTICS_CATEGORY  DROP CONSTRAINT EMS_ANALYICS_CATEGORY_U01;

ALTER TABLE  EMS_ANALYTICS_FOLDERS  DROP CONSTRAINT EMS_ANALYTICS_FOLDERS_U01;

ALTER TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_U01 UNIQUE (NAME, FOLDER_ID, CATEGORY_ID ,DELETED,TENANT_ID,OWNER) USING INDEX ;

ALTER TABLE EMS_ANALYTICS_CATEGORY ADD  CONSTRAINT EMS_ANALYICS_CATEGORY_U01 UNIQUE (NAME,DELETED,TENANT_ID,OWNER) USING INDEX;

ALTER TABLE EMS_ANALYTICS_FOLDERS ADD  CONSTRAINT EMS_ANALYTICS_FOLDERS_U01 UNIQUE (NAME, PARENT_ID,DELETED,TENANT_ID,OWNER) USING INDEX;
