Rem
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      upgrade_056_057_ta_dml.sql
Rem
Rem    DESCRIPTION
Rem      Upgrade file for upgrading from v0.5.6 to v0.5.7 
Rem
Rem    NOTES
Rem      This file will get called via generic upgrade.sql - upgrade.sql gets called as part of running SSF deployment recipe
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    WKEICHER		09/30/14 - Upgrade TA OOB Searches  
Rem


DEFINE TENANT_ID ='&1'

delete from EMS_ANALYTICS_SEARCH where SEARCH_ID IN (3000, 3006, 3007, 3008, 3009) AND TENANT_ID ='&TENANT_ID';
commit;

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID)
values (3000,'WebLogic Servers with a specific patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"weblogic_j2eeserver","metadata":{"category":false},"displayValue":"Oracle WebLogic Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"weblogic_j2eeserver","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(weblogic_j2eeserver,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(weblogic_j2eeserver,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID)
values (3006,'Oracle HTTP Servers with a specific patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,302,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_apache","metadata":{"category":false},"displayValue":"Oracle HTTP Server"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"oracle_apache","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(oracle_apache,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(oracle_apache,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID)
values (3007,'Databases with a specific patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,301,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"oracle_database","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(oracle_database,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(oracle_database,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID)
values (3008,'Databases with Autoextend ON and size greater than 30GB','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,301,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"oracle_database","metadata":{"category":false},"displayValue":"Database Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_autoextensible","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"YES"}}}}}}]}},"dataType":"string","displayName":"Autoextensible","displayDetails":"Datafiles","targetType":"oracle_database","mcName":"autoextensible","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName","fileName","tablespaceName","fileName","tablespaceName"]}},{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_database_DbDatafiles_fileSize","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"any","values":{"jsonConstructor":"CriterionExpression","data":{"type":"gt","values":{"jsonConstructor":"CriterionValue","data":{"value":32212254720}}}}}}]}},"dataType":"number","displayName":"Size","displayDetails":"Datafiles","targetType":"oracle_database","mcName":"fileSize","mgName":"DbDatafiles","mgDisplayName":"Datafiles","isKey":0,"groupKeyColumns":["fileName","tablespaceName","fileName","tablespaceName","fileName","tablespaceName"]}}]}',0,'&TENANT_ID');

Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,METADATA_CLOB,SEARCH_DISPLAY_STR,UI_HIDDEN,TENANT_ID) 
values (3009,'Fusion Instances missing a given patch','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE',null,303,2,null,null,null,null,1,null,0,null,'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"fusion_apps_instance","metadata":{"category":false},"displayValue":"Fusion Instance"}}]}},"dataType":"string","displayName":"Target Type","displayDetails":null}},{"jsonConstructor":"TargetStatusSearchCriterion","data":{"id":"target_status","_value":null,"dataType":"number","displayName":"Target Status","displayDetails":null}},{"jsonConstructor":"AssociationSearchCriterion","data":{"assoc":{"jsonConstructor":"Association","data":{"sourceTargetType":"fusion_apps_instance","destinationTargetType":"oracle_home","associationType":"installed_at","assocDisplayName":"installed_at","inverseAssocType":"install_home_for","id":"installed_at(fusion_apps_instance,oracle_home)"}},"wrappedCriterion":{"jsonConstructor":"MetricGroupSearchCriterion","data":{"id":"oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"all","values":{"jsonConstructor":"CriterionExpression","data":{"type":"not","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"Patches installed in Oracle Home","targetType":"oracle_home","mcName":"id","mgName":"LlInvPatches","mgDisplayName":"Patches installed in Oracle Home","isKey":1,"groupKeyColumns":["lang","upi","id"]}},"id":"installed_at(fusion_apps_instance,oracle_home)_oracle_home_LlInvPatches_id","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"or","values":[{"jsonConstructor":"CriterionExpression","data":{"type":"all","values":{"jsonConstructor":"CriterionExpression","data":{"type":"not","values":{"jsonConstructor":"CriterionExpression","data":{"type":"eq","values":{"jsonConstructor":"CriterionValue","data":{"value":"999999"}}}}}}}}]}},"dataType":"string","displayName":"Patch ID","displayDetails":"installed_at (Oracle Home) > Patches installed in Oracle Home"}}]}',0,'&TENANT_ID');

commit;
