DELETE FROM EMS_ANALYTICS_LAST_ACCESS where object_id<10000;
DELETE FROM EMS_ANALYTICS_SEARCH_PARAMS where search_id<10000;
DELETE FROM EMS_ANALYTICS_SEARCH where search_id<10000;
DELETE FROM EMS_ANALYTICS_CATEGORY_PARAMS where TENANT_ID <> -11;
DELETE FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID <> -11;
DELETE FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID <> -11;
commit;
