Rem
Rem emaas_savedsearch_seed_data_sec.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, 2017 Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_alter_table.sql
Rem
Rem    DESCRIPTION
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    XIADAI       05/10/17 -  Alter the constraint of tables
Rem
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
V_COUNT NUMBER;
BEGIN
    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CATEGORY_PK1' AND table_name = 'EMS_ANALYTICS_CATEGORY';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYTICS_CATEGORY_PK1 PRIMARY KEY (CATEGORY_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_PK1 has been added to EMS_ANALYTICS_CATEGORY');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_PK1 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_FOLDERS_PK1' AND table_name = 'EMS_ANALYTICS_FOLDERS';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_PK1 PRIMARY KEY (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_PK1 has been added to EMS_ANALYTICS_FOLDERS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_PK1 already exist  no need to add');
    END IF;

   SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_SEARCH_FK3' AND table_name = 'EMS_ANALYTICS_SEARCH';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_FK3 FOREIGN KEY (CATEGORY_ID) REFERENCES EMS_ANALYTICS_CATEGORY (CATEGORY_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK3 has been added to EMS_ANALYTICS_SEARCH');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK3 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_SEARCH_FK4' AND table_name = 'EMS_ANALYTICS_SEARCH';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_FK4 FOREIGN KEY (FOLDER_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK4 has been added to EMS_ANALYTICS_SEARCH');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK4 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CAT_PARAMS_FK2' AND table_name = 'EMS_ANALYTICS_CATEGORY_PARAMS';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK2 FOREIGN KEY (CATEGORY_ID) REFERENCES EMS_ANALYTICS_CATEGORY (CATEGORY_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK2 has been added to EMS_ANALYTICS_CATEGORY_PARAMS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK2 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_FOLDERS_FK2' AND table_name = 'EMS_ANALYTICS_FOLDERS';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_FK2 FOREIGN KEY (PARENT_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_FK2 has been added to EMS_ANALYTICS_FOLDERS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_FK2 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CATEGORY_FK2' AND table_name = 'EMS_ANALYTICS_CATEGORY';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYTICS_CATEGORY_FK2 FOREIGN KEY (DEFAULT_FOLDER_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_FK2 has been added to EMS_ANALYTICS_CATEGORY');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_FK2 already exist no need to add');
    END IF;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('>>>SSF DML ERROR<<<');
    DBMS_OUTPUT.PUT_LINE('Failed to add folder data due to error '||SQLERRM);
    RAISE;
END;
/
