Rem
Rem    DDL change during upgrade
Rem    MODIFIED   (MM/DD/YY)
Rem    Pamela    03/07/2017 - created
Rem
Rem

SET FEEDBACK ON
SET SERVEROUTPUT ON
DECLARE
  FLAG     VARCHAR(10);
BEGIN
   SELECT COMPRESSION INTO FLAG FROM USER_TABLES WHERE TABLE_NAME = 'EMS_ANALYTICS_SEARCH';
  IF FLAG = 'DISABLED' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH COMPRESS';
    DBMS_OUTPUT.PUT_LINE('COMPRESS EMS_ANALYTICS_SEARCH is done.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('EMS_ANALYTICS_SEARCH is compressed, no need to do any operation on it.');
  END IF;
END;
/