package oracle.sysman.SDKImpl.emaas.platform.savedsearch.model.importsearch;


//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.08.04 at 07:58:12 PM IST 
//




import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import oracle.sysman.SDKImpl.emaas.platform.savedsearch.model.FolderImpl;
import oracle.sysman.SDKImpl.emaas.platform.savedsearch.util.IdGenerator;
import oracle.sysman.SDKImpl.emaas.platform.savedsearch.util.ZDTContext;
import oracle.sysman.emSDK.emaas.platform.savedsearch.model.Folder;


/**
* <p>Java class for folderDetails complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="folderDetails">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;all>
*         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
*         &lt;element name="Name">
*           &lt;simpleType>
*             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
*               &lt;minLength value="1"/>
*             &lt;/restriction>
*           &lt;/simpleType>
*         &lt;/element>
*         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ParentId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
*         &lt;element name="UiHidden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
*       &lt;/all>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "folderDetails", propOrder = {

})
public class FolderDetails {

 @XmlElement(name="Id") 
 protected BigInteger id;
 
 @XmlElement(name="Name")
 protected String name;
 
 @XmlElement(name="Description")
 protected String description;
 
 @XmlElement(name="ParentId")
 protected BigInteger parentId;
 
 @XmlElement(name="UiHidden")
 protected boolean uiHidden;

 /**
  * Gets the value of the id property.
  * 
  * @return
  *     possible object is
  *     {@link Integer }
  *     
  */
 public BigInteger getId() {
     return id;
 }

 /**
  * Sets the value of the id property.
  * 
  * @param value
  *     allowed object is
  *     {@link Integer }
  *     
  */
 public void setId(BigInteger value) {
     this.id = value;
 }

 /**
  * Gets the value of the name property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setName(String value) {
     this.name = value;
 }

 /**
  * Gets the value of the description property.
  * 
  * @return
  *     possible object is
  *     {@link JAXBElement }{@code <}{@link String }{@code >}
  *     
  */
 public String getDescription() {
     return description;
 }

 /**
  * Sets the value of the description property.
  * 
  * @param value
  *     allowed object is
  *     {@link JAXBElement }{@code <}{@link String }{@code >}
  *     
  */
 public void setDescription(String value) {
     this.description = value;
 }

 /**
  * Gets the value of the parentId property.
  * 
  * @return
  *     possible object is
  *     {@link Integer }
  *     
  */
 public BigInteger getParentId() {
     return parentId;
 }

 /**
  * Sets the value of the parentId property.
  * 
  * @param value
  *     allowed object is
  *     {@link Integer }
  *     
  */
 public void setParentId(BigInteger value) {
     this.parentId = value;
 }

 /**
  * Gets the value of the uiHidden property.
  * 
  */
 public boolean isUiHidden() {
     return uiHidden;
 }

 /**
  * Sets the value of the uiHidden property.
  * 
  */
 public void setUiHidden(boolean value) {
     this.uiHidden = value;
 }
 
 public Folder getFolder()
 {
	 FolderImpl fld= new FolderImpl();
	 fld.setId(getId() == null ? IdGenerator.getIntUUID(ZDTContext.getRequestId()) : getId());
	 fld.setName(getName());
	 fld.setDescription(getDescription());
	 fld.setParentId(getParentId());
	 fld.setUiHidden(isUiHidden());
	 return fld;
 }

}
