Rem
Rem    DDL change during upgrade
Rem    MODIFIED   (MM/DD/YY)
Rem    ADUAN      07/05/2016 - created
Rem	   CHEHAO     07/21/2016 -	updated, moving columns from params table to search table and category table
Rem					DESCRIPTION ADD 15 ROWS IN EMS_ANALYTICS_SEARCH TABLE,BELOW ARE THE COLUMNS:
Rem				   	NAME_WIDGET_SOURCE,
Rem					WIDGET_GROUP_NAME,
Rem					WIDGET_SCREENSHOT_HREF,
Rem					WIDGET_ICON,
Rem					WIDGET_KOC_NAME,
Rem					WIDGET_VIEWMODEL,
Rem					WIDGET_TEMPLATE,
Rem					WIDGET_SUPPORT_TIME_CONTROL,
Rem					WIDGET_LINKED_DASHBOARD,
Rem					WIDGET_DEFAULT_WIDTH,
Rem					WIDGET_DEFAULT_HEIGHT,
Rem					DASHBOARD_INELIGIBLE,
REM					PROVIDER_NAME,
REM					PROVIDER_VERSION,
REM					PROVIDER_ASSET_ROOT
Rem				   ADD 1 ROW IN EMS_ANALYTIC_CATEGORY TABLE,BELOW IS THE COLUMN:
Rem					DASHBOARD_INELIGIBLE	

SET FEEDBACK ON
SET SERVEROUTPUT ON
DECLARE
  v_count     INTEGER;

BEGIN
		--add a new column 'NAME_WIDGET_SOURCE'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='NAME_WIDGET_SOURCE';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:NAME_WIDGET_SOURCE INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "NAME_WIDGET_SOURCE" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.NAME_WIDGET_SOURCE exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_GROUP_NAME'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_GROUP_NAME';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_GROUP_NAME INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_GROUP_NAME" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_GROUP_NAME exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_SCREENSHOT_HREF'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_SCREENSHOT_HREF';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_SCREENSHOT_HREF INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_SCREENSHOT_HREF" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_SCREENSHOT_HREF exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_ICON'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_ICON';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_ICON INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_ICON" VARCHAR2(1024) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_ICON exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_KOC_NAME'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_KOC_NAME';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_KOC_NAME INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_KOC_NAME" VARCHAR2(256) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_KOC_NAME exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_VIEWMODEL'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_VIEWMODEL';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_VIEWMODEL INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_VIEWMODEL" VARCHAR2(1024) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_VIEWMODEL exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_TEMPLATE'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_TEMPLATE';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_TEMPLATE INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_TEMPLATE" VARCHAR2(1024) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_TEMPLATE exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_SUPPORT_TIME_CONTROL'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_SUPPORT_TIME_CONTROL';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_SUPPORT_TIME_CONTROL INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_SUPPORT_TIME_CONTROL" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_SUPPORT_TIME_CONTROL exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_LINKED_DASHBOARD'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_LINKED_DASHBOARD';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_LINKED_DASHBOARD INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_LINKED_DASHBOARD" NUMBER(38,0) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_LINKED_DASHBOARD exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_DEFAULT_WIDTH'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_DEFAULT_WIDTH';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_DEFAULT_WIDTH INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_DEFAULT_WIDTH" NUMBER(38,0) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_DEFAULT_WIDTH exists already, no change is needed');
		END IF;
		
		--add a new column 'WIDGET_DEFAULT_HEIGHT'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='WIDGET_DEFAULT_HEIGHT';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:WIDGET_DEFAULT_HEIGHT INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "WIDGET_DEFAULT_HEIGHT" NUMBER(38,0) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.WIDGET_DEFAULT_HEIGHT exists already, no change is needed');
		END IF;
		
		--add a new column 'PROVIDER_NAME'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='PROVIDER_NAME';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:PROVIDER_NAME INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "PROVIDER_NAME" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.PROVIDER_NAME exists already, no change is needed');
		END IF;
		
		--add a new column 'PROVIDER_VERSION'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='PROVIDER_VERSION';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:PROVIDER_VERSION INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "PROVIDER_VERSION" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.PROVIDER_VERSION exists already, no change is needed');
		END IF;
		
		--add a new column 'PROVIDER_ASSET_ROOT'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='PROVIDER_ASSET_ROOT';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:PROVIDER_ASSET_ROOT INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "PROVIDER_ASSET_ROOT" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.PROVIDER_ASSET_ROOT exists already, no change is needed');
		END IF;
		
		--add a new column 'DASHBOARD_INELIGIBLE'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='DASHBOARD_INELIGIBLE';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:DASHBOARD_INELIGIBLE INTO EMS_ANALYTICS_SEARCH TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD "DASHBOARD_INELIGIBLE" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.DASHBOARD_INELIGIBLE exists already, no change is needed');
		END IF;
	
		--ALTER TABLE EMS_ANALYTICS_CATEGORY
	
		--add a new column 'DASHBOARD_INELIGIBLE'
		SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_CATEGORY' AND column_name='DASHBOARD_INELIGIBLE';
		IF v_count=0 THEN
			DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:DASHBOARD_INELIGIBLE INTO EMS_ANALYTICS_CATEGORY TABLE');
			EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY ADD "DASHBOARD_INELIGIBLE" VARCHAR2(64) DEFAULT 0';
		ELSE
			DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_CATEGORY.DASHBOARD_INELIGIBLE exists already, no change is needed');
		END IF;
	
	EXCEPTION
	  WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('Failed to add columns in EMS_ANALYTICS_SEARCH and EMS_ANALYTICS_CATEGORY due to '||SQLERRM);
		RAISE;
END;
/

