BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX EMS_SEARCH_PARAMS_IDX';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01418 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX EMS_SEARCH_PARAMS_IDX ON EMS_ANALYTICS_SEARCH_PARAMS(TENANT_ID, PARAM_VALUE_STR, NAME) COMPRESS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -00955 THEN
      RAISE;
    END IF;
END;
/
