Rem
Rem emaas_savedsearch_seed_data_sec.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, 2017 Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_alter_table.sql
Rem
Rem    DESCRIPTION
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    XIADAI       05/10/17 -  Alter the constraint of tables
Rem
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
V_FOLDER_ID					 NUMBER(38,0)          ;
V_NAME						 VARCHAR2(64 BYTE)     ;
V_PARENT_ID					 NUMBER(38,0)          ;
V_DESCRIPTION				 VARCHAR2(256 BYTE)    ;
V_CREATION_DATE				 TIMESTAMP(6)          ;
V_OWNER						 VARCHAR2(64 BYTE)     ;
V_LAST_MODIFICATION_DATE	 TIMESTAMP(6)          ;
V_LAST_MODIFIED_BY			 VARCHAR2(64 BYTE)     ;
V_NAME_NLSID				 VARCHAR2(256 BYTE)    ;
V_NAME_SUBSYSTEM			 VARCHAR2(64 BYTE)     ;
V_DESCRIPTION_NLSID			 VARCHAR2(256 BYTE)    ;
V_DESCRIPTION_SUBSYSTEM		 VARCHAR2(64 BYTE)     ;
V_SYSTEM_FOLDER				 NUMBER(1,0)           ;
V_EM_PLUGIN_ID				 VARCHAR2(64 BYTE)     ;
V_UI_HIDDEN					 NUMBER(1,0)           ;
V_DELETED					 NUMBER(38,0)          ;
V_TENANT_ID					 NUMBER(38,0)    :=   -11;

V_CATEGORY_ID                NUMBER(38,0);
V_DEFAULT_FOLDER_ID          NUMBER(38,0);
V_PROVIDER_NAME              VARCHAR2(64 BYTE);
V_PROVIDER_VERSION           VARCHAR2(64 BYTE);
V_PROVIDER_ASSET_ROOT        VARCHAR2(64 BYTE);

V_COUNT NUMBER;
BEGIN
--1. remove constraints
    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_SEARCH_FK1' AND table_name = 'EMS_ANALYTICS_SEARCH';
    IF V_COUNT=0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK1 does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP CONSTRAINT EMS_ANALYTICS_SEARCH_FK1';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK1 has been modified to EMS_ANALYTICS_SEARCH');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_SEARCH_FK2' AND table_name = 'EMS_ANALYTICS_SEARCH';
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK2 does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP CONSTRAINT EMS_ANALYTICS_SEARCH_FK2';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK2 has been modified to EMS_ANALYTICS_SEARCH');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CAT_PARAMS_FK1' AND table_name = 'EMS_ANALYTICS_CATEGORY_PARAMS';
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK1 does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY_PARAMS DROP CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK1';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK1 has been modified to EMS_ANALYTICS_CATEGORY_PARAMS');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_FOLDERS_FK1' AND table_name = 'EMS_ANALYTICS_FOLDERS';
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_FK1 does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_FOLDERS DROP CONSTRAINT EMS_ANALYTICS_FOLDERS_FK1';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_FK1 has been modified to EMS_ANALYTICS_FOLDERS');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CATEGORY_FK1' AND table_name = 'EMS_ANALYTICS_CATEGORY';
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_FK1 does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY DROP CONSTRAINT EMS_ANALYTICS_CATEGORY_FK1';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_FK1 has been modified to EMS_ANALYTICS_CATEGORY');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CATEGORY_PK' AND table_name = 'EMS_ANALYTICS_CATEGORY';
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_PK does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY DROP CONSTRAINT EMS_ANALYTICS_CATEGORY_PK';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_PK has been modified to EMS_ANALYTICS_CATEGORY');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_FOLDERS_PK' AND table_name = 'EMS_ANALYTICS_FOLDERS';
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_PK does not exist');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_FOLDERS DROP CONSTRAINT EMS_ANALYTICS_FOLDERS_PK';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_PK has been modified to EMS_ANALYTICS_FOLDERS');
    END IF;

--2. remove category and folder where categoryId or folderId != -11
    SELECT COUNT(1) INTO V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID <> V_TENANT_ID;
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CATEGORY ID DOES NOT EQUAL -11 NOT EXIST');
    ELSE
        DELETE FROM EMS_ANALYTICS_CATEGORY_PARAMS WHERE TENANT_ID <> V_TENANT_ID;
        DELETE FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID <> V_TENANT_ID;
        DBMS_OUTPUT.PUT_LINE('CATEGORY ID DOES NOT EQUAL -11  HAS BEEN REMOVED SUCCESSFULLY');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID <> V_TENANT_ID;
    IF V_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('FOLDER ID DOES NOT EQUAL -11 NOT EXIST');
    ELSE
        DELETE FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID <> V_TENANT_ID;
        DBMS_OUTPUT.PUT_LINE('FOLDER ID DOES NOT EQUAL -11  HAS BEEN REMOVED SUCCESSFULLY');
    END IF;

--3. INSERT folder seed data for tenant -11
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 1;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data All Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=   1;
        V_NAME					:=   'All Searches';
        V_PARENT_ID				:=   null;
        V_DESCRIPTION			:=   'Search Console Root Folder';
        V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=   'ORACLE';
        V_NAME_NLSID			:=   'ALL_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=   'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=   'ALL_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=   'EMANALYTICS';
        V_SYSTEM_FOLDER			:=   1;
        V_EM_PLUGIN_ID			:=   'oracle.sysman.core';
        V_UI_HIDDEN				:=   0;
        INSERT INTO EMS_ANALYTICS_FOLDERS (FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data All Searches has been added successfully for '||V_TENANT_ID);
    END IF;
     
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 2;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Log Analytics Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=  2;
        V_NAME					:=  'Log Analytics Searches';
        V_PARENT_ID				:=  1;
        V_DESCRIPTION			:=  'Log Analytics Root Folder';
        V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=  'ORACLE';
        V_LAST_MODIFICATION_DATE:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=  'ORACLE';
        V_NAME_NLSID			:=  'ALL_LOG_ANALYTICS_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=  'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=  'ALL_LOG_ANALYTICS_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=  'EMANALYTICS';
        V_SYSTEM_FOLDER			:=  1;
        V_EM_PLUGIN_ID			:=  'oracle.sysman.core';
        V_UI_HIDDEN				:=  0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Log Analytics Searches has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 3;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data All Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=   3;
        V_NAME					:=   'IT Analytics Searches';
        V_PARENT_ID				:=   1;
        V_DESCRIPTION			:=   'IT Analytics Root Folder';
        V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=   'ORACLE';
        V_NAME_NLSID			:=   'ALL_IT_ANALYTICS_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=   'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=   'ALL_IT_ANALYTICS_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=   'EMANALYTICS';
        V_SYSTEM_FOLDER			:=   1;
        V_EM_PLUGIN_ID			:=   'oracle.sysman.core';
        V_UI_HIDDEN				:=   0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 4;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Target Analytics Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:= 4;
        V_NAME					:= 'Target Analytics Searches';
        V_PARENT_ID				:= 1;
        V_DESCRIPTION			:= 'Target Analytics Root Folder';
        V_CREATION_DATE			:= SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:= SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:= 'ORACLE';
        V_NAME_NLSID			:= 'ALL_TARGET_ANALYTICS_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:= 'EMANALYTICS';
        V_DESCRIPTION_NLSID		:= 'ALL_TARGET_ANALYTICS_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:= 'EMANALYTICS';
        V_SYSTEM_FOLDER			:= 1;
        V_EM_PLUGIN_ID			:= 'oracle.sysman.core';
        V_UI_HIDDEN				:= 0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Target Analytics Searches has been added successfully for '||V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 5;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data APMCS Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=  5;
        V_NAME					:=  'APMCS Searches';
        V_PARENT_ID				:=  1;
        V_DESCRIPTION			:=  'Application Performance Monitoring Cloud Service Root Folder';
        V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=  'ORACLE';
        V_NAME_NLSID			:=  'ALL_APMCS_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=  'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=  'ALL_APMCS_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=  'EMANALYTICS';
        V_SYSTEM_FOLDER			:=  1;
        V_EM_PLUGIN_ID			:=  'oracle.sysman.core';
        V_UI_HIDDEN				:=  0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data APMCS Searches has been added successfully for '||V_TENANT_ID);
    END IF;


-- *********************** LA FOLDERS ********************************
-- folder id between 200 - 299 are reserved for Log Analytics

   SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 201;
   IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Database has been added before, no need to add again for '||V_TENANT_ID);
   ELSE
        V_FOLDER_ID				:=  201;
        V_NAME					:=  'Database';
        V_PARENT_ID				:=  2;
        V_DESCRIPTION			:=  'Databases';
        V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=  'ORACLE';
        V_NAME_NLSID			:=  null;
        V_NAME_SUBSYSTEM		:=  null;
        V_DESCRIPTION_NLSID		:=  null;
        V_DESCRIPTION_SUBSYSTEM	:=  null;
        V_SYSTEM_FOLDER			:=  1;
        V_EM_PLUGIN_ID			:=  null;
        V_UI_HIDDEN				:=  0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Database has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 206;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Alerts has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=  206;
        V_NAME					:=  'Alerts';
        V_PARENT_ID				:=  201;
        V_DESCRIPTION			:=  'Searches based on database alert logs';
        V_CREATION_DATE			:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:=  SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=  'ORACLE';
        V_NAME_NLSID			:=  null;
        V_NAME_SUBSYSTEM		:=  null;
        V_DESCRIPTION_NLSID		:=  null;
        V_DESCRIPTION_SUBSYSTEM	:=  null;
        V_SYSTEM_FOLDER			:=  1;
        V_EM_PLUGIN_ID			:=  null;
        V_UI_HIDDEN				:=  0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Alerts has been added successfully for '||V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 202;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Middleware has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=   202;
        V_NAME					:=   'Middleware';
        V_PARENT_ID				:=   2;
        V_DESCRIPTION			:=   'Middleware';
        V_CREATION_DATE			:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=   'ORACLE';
        V_LAST_MODIFICATION_DATE:=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=   'ORACLE';
        V_NAME_NLSID			:=   null;
        V_NAME_SUBSYSTEM		:=   null;
        V_DESCRIPTION_NLSID		:=   null;
        V_DESCRIPTION_SUBSYSTEM	:=   null;
        V_SYSTEM_FOLDER			:=   1;
        V_EM_PLUGIN_ID			:=   null;
        V_UI_HIDDEN				:=   0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Middleware has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 207;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Access has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      207;
        V_NAME					:=      'Access';
        V_PARENT_ID				:=      202;
        V_DESCRIPTION			:=      'Searches based on HTTP request access logs';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Access has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 208;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Server has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      208;
        V_NAME					:=      'Server';
        V_PARENT_ID				:=      202;
        V_DESCRIPTION			:=      'Searches based on operational middleware server logs';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Access has been added successfully for '||V_TENANT_ID);
    END IF;


    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 203;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Servers, Storage and Network has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      203;
        V_NAME					:=      'Servers, Storage and Network';
        V_PARENT_ID				:=      2;
        V_DESCRIPTION			:=      'Servers, Storage and Network';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Servers, Storage and Network has been added successfully for '||V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 209;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Security has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      209;
        V_NAME					:=      'Security';
        V_PARENT_ID				:=      203;
        V_DESCRIPTION			:=      'Searches based on logs that capture host-level security';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Security has been added successfully for '||V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 210;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Lifecycle has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=     210;
        V_NAME					:=     'Lifecycle';
        V_PARENT_ID				:=     203;
        V_DESCRIPTION			:=     'Searches based on logs that capture host lifecycle,such as package managers';
        V_CREATION_DATE			:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=     'ORACLE';
        V_LAST_MODIFICATION_DATE:=     SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=     'ORACLE';
        V_NAME_NLSID			:=     null;
        V_NAME_SUBSYSTEM		:=     null;
        V_DESCRIPTION_NLSID		:=     null;
        V_DESCRIPTION_SUBSYSTEM	:=     null;
        V_SYSTEM_FOLDER			:=     1;
        V_EM_PLUGIN_ID			:=     null;
        V_UI_HIDDEN				:=     0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Lifecycle has been added successfully for '||V_TENANT_ID);
    END IF;
  
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 205;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Enterprise Manager has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      205;
        V_NAME					:=      'Enterprise Manager';
        V_PARENT_ID				:=      2;
        V_DESCRIPTION			:=      'Entprise Manager';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Enterprise Manager has been added successfully for '||V_TENANT_ID);
    END IF;
    
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 211;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Servers has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      211;
        V_NAME					:=      'Servers';
        V_PARENT_ID				:=      205;
        V_DESCRIPTION			:=      'Searches based on Enterprise Manager server logs';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Servers has been added successfully for '||V_TENANT_ID);
    END IF;
    
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 212;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Agents has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      212;
        V_NAME					:=      'Agents';
        V_PARENT_ID				:=      205;
        V_DESCRIPTION			:=      'Searches based on Enterprise Manager agent logs';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Agents has been added successfully for '||V_TENANT_ID);
    END IF;
-- *********************** ITA FOLDERS ********************************
-- folder id between 300 - 399 are reserved for IT Analytics

-- *********************** TA FOLDERS ********************************
-- folder id between 400 - 499 are reserved for IT Analytics
--NONE

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 401;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data UDE Type-Ahead Feature has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      401;
        V_NAME					:=      'UDE Type-Ahead Feature';
        V_PARENT_ID				:=      4;
        V_DESCRIPTION			:=      'Folder for UDE Type-Ahead Feature';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      'UDE_TYPE_AHEAD_FEATURE';
        V_NAME_SUBSYSTEM		:=      'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=      'UDE_TYPE_AHEAD_FEATURE_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=      'EMANALYTICS';
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      'oracle.sysman.core';
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data UDE Type-Ahead Feature has been added successfully for '||V_TENANT_ID);
    END IF;

-- *********************** APM FOLDERS ********************************
-- folder id between 500 - 599 are reserved for APMCS
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 501;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Requests has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      501;
        V_NAME					:=      'Requests';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'Request Types Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Requests has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 502;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data All Pages has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      502;
        V_NAME					:=      'Pages';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'Page Types Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Pages has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 503;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Instances has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      503;
        V_NAME					:=      'Instances';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'Instances Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Instances has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 504;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Agents has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      504;
        V_NAME					:=      'Agents';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'Agents Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Agents has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 505;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data App Servers has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      505;
        V_NAME					:=      'App Servers';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'App Servers Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data App Servers has been added successfully for '||V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 506;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Ajax Calls has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      506;
        V_NAME					:=      'Ajax Calls';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'Ajax Calls Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Ajax Calls has been added successfully for '||V_TENANT_ID);
    END IF;
        
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 507;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data JDBC Calls has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      507;
        V_NAME					:=      'JDBC Calls';
        V_PARENT_ID				:=      5;
        V_DESCRIPTION			:=      'JDBC Calls Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      null;
        V_NAME_SUBSYSTEM		:=      null;
        V_DESCRIPTION_NLSID		:=      null;
        V_DESCRIPTION_SUBSYSTEM	:=      null;
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      null;
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data JDBC Calls has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 6;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Target Card Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      6;
        V_NAME					:=      'Target Card Searches';
        V_PARENT_ID				:=      1;
        V_DESCRIPTION			:=      'Target Card Root Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      'ALL_TARGETCARD_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=      'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=      'ALL_TARGETCARD_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=      'EMANALYTICS';
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      'oracle.sysman.core';
        V_UI_HIDDEN				:=      1;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Target Card Searches has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 7;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Security Analytics Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      7;
        V_NAME					:=      'Security Analytics Searches';
        V_PARENT_ID				:=      1;
        V_DESCRIPTION			:=      'Security Analytics Root Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      'ALL_SECURITYANALYTICS_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=      'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=      'ALL_SECURITYANALYTICS_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=      'EMANALYTICS';
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      'oracle.sysman.core';
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Security Analytics Searches has been added successfully for '||V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_FOLDERS WHERE TENANT_ID = V_TENANT_ID AND FOLDER_ID = 8;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('folder data Ochestration Searches has been added before, no need to add again for '||V_TENANT_ID);
    ELSE
        V_FOLDER_ID				:=      8;
        V_NAME					:=      'Ochestration Searches';
        V_PARENT_ID				:=      1;
        V_DESCRIPTION			:=      'Orchestration Root Folder';
        V_CREATION_DATE			:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_OWNER					:=      'ORACLE';
        V_LAST_MODIFICATION_DATE:=      SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_LAST_MODIFIED_BY		:=      'ORACLE';
        V_NAME_NLSID			:=      'ALL_ORCHESTRATION_SEARCHES_NAME';
        V_NAME_SUBSYSTEM		:=      'EMANALYTICS';
        V_DESCRIPTION_NLSID		:=      'ALL_ORCHESTRATION_SEARCHES_DESC';
        V_DESCRIPTION_SUBSYSTEM	:=      'EMANALYTICS';
        V_SYSTEM_FOLDER			:=      1;
        V_EM_PLUGIN_ID			:=      'oracle.sysman.core';
        V_UI_HIDDEN				:=      0;
        INSERT INTO EMS_ANALYTICS_FOLDERS(FOLDER_ID, NAME, PARENT_ID, DESCRIPTION, CREATION_DATE, OWNER, LAST_MODIFICATION_DATE, LAST_MODIFIED_BY, NAME_NLSID, NAME_SUBSYSTEM, DESCRIPTION_NLSID, DESCRIPTION_SUBSYSTEM, SYSTEM_FOLDER, EM_PLUGIN_ID, UI_HIDDEN, TENANT_ID) VALUES (V_FOLDER_ID,  V_NAME,  V_PARENT_ID,  V_DESCRIPTION,  V_CREATION_DATE,  V_OWNER,  V_LAST_MODIFICATION_DATE,  V_LAST_MODIFIED_BY,  V_NAME_NLSID,  V_NAME_SUBSYSTEM,  V_DESCRIPTION_NLSID,  V_DESCRIPTION_SUBSYSTEM,  V_SYSTEM_FOLDER,  V_EM_PLUGIN_ID,  V_UI_HIDDEN,  V_TENANT_ID);
        DBMS_OUTPUT.PUT_LINE('folder data Ochestration Searches has been added successfully for '||V_TENANT_ID);
    END IF;
    
--Rem SEED DATA FOR CATEGORY
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 1;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data Log Analytics has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=   1;
        V_NAME                     :=   'Log Analytics';
        V_DESCRIPTION              :=   'Search Category for Log Analytics';
        V_OWNER					   :=   'ORACLE';
        V_CREATION_DATE            :=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=   'LOG_ANALYTICS_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=   'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=   'LOG_ANALYTICS_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=   'EMANALYTICS';
        V_EM_PLUGIN_ID             :=   'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=   2;
        V_PROVIDER_NAME            :=   'LogAnalyticsUI';
        V_PROVIDER_VERSION         :=   '1.0';
        V_PROVIDER_ASSET_ROOT      :=   'assetRoot';
        INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 2;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data Data Explorer has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=   2;
        V_NAME                     :=   'Data Explorer';
        V_DESCRIPTION              :=   'Search Category for Target Analytics';
        V_OWNER					   :=   'ORACLE';
        V_CREATION_DATE            :=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=   'TARGET_ANALYTICS_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=   'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=   'TARGET_ANALYTICS_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=   'EMANALYTICS';
        V_EM_PLUGIN_ID             :=   'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=   4;
        V_PROVIDER_NAME            :=   'TargetAnalytics';
        V_PROVIDER_VERSION         :=   '1.0';
        V_PROVIDER_ASSET_ROOT      :=   'assetRoot';
        INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 3;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data IT Analytics has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=   3;
        V_NAME                     :=   'IT Analytics';
        V_DESCRIPTION              :=   'Search Category for IT Analytics';
        V_OWNER					   :=   'ORACLE';
        V_CREATION_DATE            :=   SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=   'IT_ANALYTICS_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=   'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=   'IT_ANALYTICS_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=   'EMANALYTICS';
        V_EM_PLUGIN_ID             :=   'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=   3;
        V_PROVIDER_NAME            :=   'emcitas-ui-apps';
        V_PROVIDER_VERSION         :=   '1.0';
        V_PROVIDER_ASSET_ROOT      :=   'assetRoot';
        INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;
    
    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 4;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data APMCS has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=       4;
        V_NAME                     :=       'APMCS';
        V_DESCRIPTION              :=       'Search Category for Application Performance Monitoring Cloud Service';
        V_OWNER					   :=       'ORACLE';
        V_CREATION_DATE            :=       SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=       'APMCS_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=       'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=       'APMCS_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=       'EMANALYTICS';
        V_EM_PLUGIN_ID             :=       'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=       5;
        V_PROVIDER_NAME            :=       'ApmUI';
        V_PROVIDER_VERSION         :=       '1.0';
        V_PROVIDER_ASSET_ROOT      :=       'home';
    INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 5;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data Target Card has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=       5;
        V_NAME                     :=       'Target Card';
        V_DESCRIPTION              :=       'Search Category for Target Card';
        V_OWNER					   :=       'ORACLE';
        V_CREATION_DATE            :=       SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=       'TARGETCARD_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=       'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=       'TARGETCARD_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=       'EMANALYTICS';
        V_EM_PLUGIN_ID             :=       'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=       6;
        V_PROVIDER_NAME            :=       'TargetCard';
        V_PROVIDER_VERSION         :=       '1.0';
        V_PROVIDER_ASSET_ROOT      :=       'home';
    INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 6;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data Security Analytics has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=       6;
        V_NAME                     :=       'Security Analytics';
        V_DESCRIPTION              :=       'Search Category for Security Analytics';
        V_OWNER					   :=       'ORACLE';
        V_CREATION_DATE            :=       SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=       'SECURITYANALYTICS_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=       'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=       'SECURITYANALYTICS_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=       'EMANALYTICS';
        V_EM_PLUGIN_ID             :=       'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=       7;
        V_PROVIDER_NAME            :=       'SecurityAnalyticsUI';
        V_PROVIDER_VERSION         :=       '1.0';
        V_PROVIDER_ASSET_ROOT      :=       'home';
    INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;

    SELECT COUNT(1) INTO  V_COUNT FROM EMS_ANALYTICS_CATEGORY WHERE TENANT_ID = V_TENANT_ID AND CATEGORY_ID = 7;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('category data Security Analytics has been added before, no need to add again for ' || V_TENANT_ID);
    ELSE
        V_CATEGORY_ID              :=       7;
        V_NAME                     :=       'Orchestration';
        V_DESCRIPTION              :=       'Search Category for Orchestration';
        V_OWNER					   :=       'ORACLE';
        V_CREATION_DATE            :=       SYS_EXTRACT_UTC(SYSTIMESTAMP);
        V_NAME_NLSID               :=       'ORCHESTRATION_CATEGORY_NAME';
        V_NAME_SUBSYSTEM           :=       'EMANALYTICS';
        V_DESCRIPTION_NLSID        :=       'ORCHESTRATION_CATEGORY_DESC';
        V_DESCRIPTION_SUBSYSTEM    :=       'EMANALYTICS';
        V_EM_PLUGIN_ID             :=       'oracle.sysman.core';
        V_DEFAULT_FOLDER_ID        :=       8;
        V_PROVIDER_NAME            :=       'CosUIService';
        V_PROVIDER_VERSION         :=       '1.0';
        V_PROVIDER_ASSET_ROOT      :=       'assetRoot';
    INSERT INTO EMS_ANALYTICS_CATEGORY (CATEGORY_ID,NAME,DESCRIPTION,OWNER,CREATION_DATE,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,EM_PLUGIN_ID,DEFAULT_FOLDER_ID,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TENANT_ID)VALUES (V_CATEGORY_ID,V_NAME,V_DESCRIPTION,V_OWNER,V_CREATION_DATE,V_NAME_NLSID,V_NAME_SUBSYSTEM,V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_EM_PLUGIN_ID,V_DEFAULT_FOLDER_ID,V_PROVIDER_NAME ,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TENANT_ID);
    END IF;
--3. create new constraint
    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CATEGORY_PK1' AND table_name = 'EMS_ANALYTICS_CATEGORY';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYTICS_CATEGORY_PK1 PRIMARY KEY (CATEGORY_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_PK1 has been added to EMS_ANALYTICS_CATEGORY');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_PK1 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_FOLDERS_PK1' AND table_name = 'EMS_ANALYTICS_FOLDERS';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_PK1 PRIMARY KEY (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_PK1 has been added to EMS_ANALYTICS_FOLDERS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_PK1 already exist  no need to add');
    END IF;

   SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_SEARCH_FK3' AND table_name = 'EMS_ANALYTICS_SEARCH';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_FK3 FOREIGN KEY (CATEGORY_ID) REFERENCES EMS_ANALYTICS_CATEGORY (CATEGORY_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK3 has been added to EMS_ANALYTICS_SEARCH');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK3 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_SEARCH_FK4' AND table_name = 'EMS_ANALYTICS_SEARCH';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD CONSTRAINT EMS_ANALYTICS_SEARCH_FK4 FOREIGN KEY (FOLDER_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK4 has been added to EMS_ANALYTICS_SEARCH');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_SEARCH_FK4 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CAT_PARAMS_FK2' AND table_name = 'EMS_ANALYTICS_CATEGORY_PARAMS';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY_PARAMS ADD CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK2 FOREIGN KEY (CATEGORY_ID) REFERENCES EMS_ANALYTICS_CATEGORY (CATEGORY_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK2 has been added to EMS_ANALYTICS_CATEGORY_PARAMS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CAT_PARAMS_FK2 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_FOLDERS_FK2' AND table_name = 'EMS_ANALYTICS_FOLDERS';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_FOLDERS ADD CONSTRAINT EMS_ANALYTICS_FOLDERS_FK2 FOREIGN KEY (PARENT_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_FK2 has been added to EMS_ANALYTICS_FOLDERS');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_FOLDERS_FK2 already exist no need to add');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM user_constraints WHERE constraint_name = 'EMS_ANALYTICS_CATEGORY_FK2' AND table_name = 'EMS_ANALYTICS_CATEGORY';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_CATEGORY ADD CONSTRAINT EMS_ANALYTICS_CATEGORY_FK2 FOREIGN KEY (DEFAULT_FOLDER_ID) REFERENCES EMS_ANALYTICS_FOLDERS (FOLDER_ID)';
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_FK2 has been added to EMS_ANALYTICS_CATEGORY');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CONSTRAINT EMS_ANALYTICS_CATEGORY_FK2 already exist no need to add');
    END IF;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('>>>SSF DML ERROR<<<');
    DBMS_OUTPUT.PUT_LINE('Failed to add folder data due to error '||SQLERRM);
    RAISE;
END;
/
