DEFINE TENANT_ID ='&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
  OOB_DB        CONSTANT EMS_ANALYTICS_SEARCH.SEARCH_ID%TYPE:=3029;
  OOB_WLS       CONSTANT EMS_ANALYTICS_SEARCH.SEARCH_ID%TYPE:=3030;
  OOB_HOST      CONSTANT EMS_ANALYTICS_SEARCH.SEARCH_ID%TYPE:=3031;  
  V_COUNT                 NUMBER;
  V_TENANT_ID             EMS_ANALYTICS_SEARCH.TENANT_ID%TYPE;
  V_TID                   NUMBER(38,0) := '&TENANT_ID';
  CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_FOLDERS ORDER BY TENANT_ID;
BEGIN
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;
     SELECT COUNT(SEARCH_ID) INTO V_COUNT FROM EMS_ANALYTICS_SEARCH WHERE SEARCH_ID=OOB_DB AND TENANT_ID=V_TENANT_ID;
     IF (V_COUNT=1) THEN
        DELETE FROM EMS_ANALYTICS_LAST_ACCESS
        WHERE TENANT_ID = V_TENANT_ID AND OBJECT_TYPE=2 and OBJECT_ID IN
            (SELECT SEARCH_ID FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID = V_TENANT_ID and  SEARCH_ID in (OOB_DB,OOB_WLS,OOB_HOST));
            
        DELETE FROM EMS_ANALYTICS_SEARCH_PARAMS
        WHERE TENANT_ID = V_TENANT_ID AND SEARCH_ID IN
            (SELECT SEARCH_ID FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID = V_TENANT_ID and   SEARCH_ID in (OOB_DB,OOB_WLS,OOB_HOST));
      
        DELETE FROM EMS_ANALYTICS_SEARCH WHERE TENANT_ID = V_TENANT_ID and  SEARCH_ID in (OOB_DB,OOB_WLS,OOB_HOST);
        DBMS_OUTPUT.PUT_LINE('Remove 3 out of box widgets for BF successfully! tenant_id='||V_TENANT_ID);
     ELSE
        DBMS_OUTPUT.PUT_LINE('3 out of box widgets for BF has been removed before, no need to remove again! tenant_id='||V_TENANT_ID);
     END IF;
     IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Failed to remove 3 out of box widgets for BF due to error '||SQLERRM);
    RAISE;
END;
/
