DEFINE TENANT_ID ='&1'
DECLARE
V_SEARCH_ID                    NUMBER(38,0)         ;
V_NAME                         VARCHAR2(64 BYTE)    ;
V_OWNER                        VARCHAR2(64 BYTE)    ;
V_CREATION_DATE                TIMESTAMP(6)         ;
V_LAST_MODIFICATION_DATE       TIMESTAMP(6)         ;
V_LAST_MODIFIED_BY             VARCHAR2(64 BYTE)    ;
V_DESCRIPTION                  VARCHAR2(256 BYTE)   ;
V_FOLDER_ID                    NUMBER(38,0)         ;
V_CATEGORY_ID                  NUMBER(38,0)         ;
V_NAME_NLSID                   VARCHAR2(256 BYTE)   ;
V_NAME_SUBSYSTEM               VARCHAR2(64 BYTE)    ;
V_DESCRIPTION_NLSID            VARCHAR2(256 BYTE)   ;
V_DESCRIPTION_SUBSYSTEM        VARCHAR2(64 BYTE)    ;
V_SYSTEM_SEARCH                NUMBER(1,0)          ;
V_EM_PLUGIN_ID                 VARCHAR2(64 BYTE)    ;
V_IS_LOCKED                    NUMBER(1,0)          ;
V_UI_HIDDEN                    NUMBER(1,0)          ;
V_DELETED                      NUMBER(38,0)         ;
V_IS_WIDGET                    NUMBER(1,0)          ;
V_TENANT_ID                    NUMBER(38,0);
  V_WIDGET_SOURCE            EMS_ANALYTICS_SEARCH.WIDGET_SOURCE%TYPE;
  V_WIDGET_GROUP_NAME        EMS_ANALYTICS_SEARCH.WIDGET_GROUP_NAME%TYPE;
  V_WIDGET_ICON              EMS_ANALYTICS_SEARCH.WIDGET_ICON%TYPE;
  V_WIDGET_KOC_NAME          EMS_ANALYTICS_SEARCH.WIDGET_KOC_NAME%TYPE;
  V_WIDGET_VIEWMODEL         EMS_ANALYTICS_SEARCH.WIDGET_VIEWMODEL%TYPE;
  V_WIDGET_TEMPLATE          EMS_ANALYTICS_SEARCH.WIDGET_TEMPLATE%TYPE;
  V_WIDGET_SUPPORT_TIME_CONTROL     EMS_ANALYTICS_SEARCH.WIDGET_SUPPORT_TIME_CONTROL%TYPE;
  V_DASHBOARD_INELIGIBLE     EMS_ANALYTICS_SEARCH.DASHBOARD_INELIGIBLE%TYPE;
  V_PROVIDER_NAME            EMS_ANALYTICS_SEARCH.PROVIDER_NAME%TYPE;
  V_PROVIDER_VERSION         EMS_ANALYTICS_SEARCH.PROVIDER_VERSION%TYPE;
  V_PROVIDER_ASSET_ROOT      EMS_ANALYTICS_SEARCH.PROVIDER_ASSET_ROOT%TYPE;
  V_WIDGET_LINKED_DASHBOARD  EMS_ANALYTICS_SEARCH.WIDGET_LINKED_DASHBOARD%TYPE;
  V_WIDGET_DEFAULT_WIDTH     EMS_ANALYTICS_SEARCH.WIDGET_DEFAULT_WIDTH%TYPE;
  V_WIDGET_DEFAULT_HEIGHT    EMS_ANALYTICS_SEARCH.WIDGET_DEFAULT_HEIGHT%TYPE; 
  V_PARAM_ATTRIBUTES         EMS_ANALYTICS_SEARCH_PARAMS.PARAM_ATTRIBUTES%TYPE; 
  V_PARAM_TYPE               EMS_ANALYTICS_SEARCH_PARAMS.PARAM_TYPE%TYPE; 
  V_PARAM_VALUE_STR          EMS_ANALYTICS_SEARCH_PARAMS.PARAM_VALUE_STR%TYPE; 
  V_PARAM_VALUE_CLOB         CLOB;
V_CLOB                            CLOB                           ;
V_SEARCH_STR                      CLOB                           ;
V_METADATA                        CLOB                           ;

v_count number;
  V_TID                   NUMBER(38,0) := '&TENANT_ID';
  CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_FOLDERS ORDER BY TENANT_ID;
BEGIN

  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       IF NOT TENANT_CURSOR%ISOPEN THEN
        OPEN TENANT_CURSOR;
       END IF;
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;

    SELECT COUNT(1) INTO v_count FROM EMS_ANALYTICS_SEARCH WHERE search_id=5004 AND TENANT_ID  =V_TENANT_ID;
    IF (v_count=0) THEN 
  
  V_SEARCH_ID                :=5004;
  V_NAME                     :='Orchestration Workflow Submission';
  V_OWNER                    :='ORACLE';
  V_CREATION_DATE            :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFICATION_DATE   :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY         :='ORACLE';
  V_DESCRIPTION              :=null;
  V_FOLDER_ID                :=8;
  V_CATEGORY_ID              :=7;
  V_NAME_NLSID               :=null;
  V_NAME_SUBSYSTEM           :=null;
  V_DESCRIPTION_NLSID        :=null;
  V_DESCRIPTION_SUBSYSTEM    :=null;
  V_SYSTEM_SEARCH            :=1;
  V_EM_PLUGIN_ID             :=null;
  V_IS_LOCKED                :=0;
  V_UI_HIDDEN                :=0;
  V_DELETED                  :=0;
  V_IS_WIDGET                :=1;
  V_METADATA                 :=null;
  V_SEARCH_STR               :=null;
  V_WIDGET_SOURCE       :='1';
  V_WIDGET_GROUP_NAME        :=null;
  V_WIDGET_ICON              :='/../images/func_horibargraph_24_ena.png';
  V_WIDGET_KOC_NAME          :='emcta-visualization';
  V_WIDGET_VIEWMODEL         :='/widget/visualizationWidget/js/VisualizationWidget.js';
  V_WIDGET_TEMPLATE          :='/widget/visualizationWidget/visualizationWidget.html';
  V_WIDGET_SUPPORT_TIME_CONTROL      :=null;
  V_DASHBOARD_INELIGIBLE     :=null;
  V_PROVIDER_NAME            :='TargetAnalytics';
  V_PROVIDER_VERSION         :='1.1';
  V_PROVIDER_ASSET_ROOT      :='assetRoot';
  V_WIDGET_LINKED_DASHBOARD  :=0;
  V_WIDGET_DEFAULT_WIDTH     :=0;
  V_WIDGET_DEFAULT_HEIGHT    :=0;
  Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,
                                    NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,
                                    UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID,METADATA_CLOB,SEARCH_DISPLAY_STR,
                                    WIDGET_SOURCE,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_KOC_NAME,WIDGET_VIEWMODEL,WIDGET_TEMPLATE,
                                    WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD,WIDGET_DEFAULT_WIDTH,WIDGET_DEFAULT_HEIGHT,
                                    DASHBOARD_INELIGIBLE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT)
	values (V_SEARCH_ID,V_NAME,V_OWNER,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_DESCRIPTION,V_FOLDER_ID,V_CATEGORY_ID,V_NAME_NLSID,V_NAME_SUBSYSTEM,
         V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_SYSTEM_SEARCH,V_EM_PLUGIN_ID,V_IS_LOCKED,V_UI_HIDDEN,V_DELETED,V_IS_WIDGET,V_TENANT_ID,V_METADATA,V_SEARCH_STR,
         V_WIDGET_SOURCE,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_KOC_NAME,V_WIDGET_VIEWMODEL,V_WIDGET_TEMPLATE,
         V_WIDGET_SUPPORT_TIME_CONTROL,V_WIDGET_LINKED_DASHBOARD,V_WIDGET_DEFAULT_WIDTH,V_WIDGET_DEFAULT_HEIGHT,
         V_DASHBOARD_INELIGIBLE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT);
  V_SEARCH_ID             :=5004;
  V_NAME                  :='CUSTOM_LABELS';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'[null,null,null]';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='SELECTED_TIME_PERIOD';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='Last 1 day';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_CORRELATION_TIME_PERIOD_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='744';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_CRITERIA';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{"version":0.5,"criteria":[{"jsonConstructor":"TargetTypeSearchCriterion","data":{"_id":"target_type","_value":{"jsonConstructor":"CriterionExpression","data":{"type":"in","values":[{"jsonConstructor":"CriterionValue","data":{"value":"omc_workflow_submission","metadata":{"category":false},"displayValue":"Orchestration Workflow Submission"}}]}},"dataType":"string","_displayName":"Entity Type","displayDetails":null,"role":"filter","func":null,"UIProperties":{"useForSort":false},"measures":[{"name":"TARGETTYPEDISPLAYNAME","displayName":"Target Type","description":"Target type such as Oracle WebLogic Domain or Host","dimensionName":"","dataType":1,"disableGroupBy":false,"precision":256,"scale":0,"hide":0,"isAttr":true}]}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.submitted_user","_value":null,"dataType":"string","_displayName":"User","displayDetails":null,"role":"value ","func":"count","UIProperties":{},"targetType":"omc_workflow_submission","propertyName":"submi'||
'tted_user"}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.schedule","_value":null,"dataType":"string","_displayName":"Schedule","displayDetails":null,"role":"value ","func":"count","UIProperties":{},"targetType":"omc_workflow_submission","propertyName":"schedule"}},{"jsonConstructor":"PropertySearchCriterion","data":{"_id":"property.workflow_type","_value":null,"dataType":"string","_displayName":"Workflow Type","displayDetails":null,"role":"value ","func":"count","UIProperties":{},"targetType":"omc_workflow_submission","propertyName":"workflow_type"}}]}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_DONUT_WIDGET_ENABLE_RANKING';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_DONUT_WIDGET_TOP_N_CONFIG';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='none';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_KEY_METRICS';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{"keyMetricsNameList":[],"otherKeyMetricsNameList":[]}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_OTHER_METRICS_CRITERIA';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'[]';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_3D';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='off';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_KEY_NAME_SELECTION';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'["no"]';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_FUNNEL_WIDGET_SHOW_ORIENTATION';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='vertical';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_HISTOGRAM_INSIGHT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='insights';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_HORI_SORT_COLUMN';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='0';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_HORI_SORT_ORDER';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='true';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_LINECHART_WIDGET_ENABLE_RANKING';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_LINECHART_WIDGET_TOP_N_CONFIG';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_LINE_CHART_WIDGET_SHOW_STACKED';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='on';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_QDELINE_DISPLAY_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["insights"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_QDELINE_TIME_PERIOD_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='744';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_QDELINE_TIME_SERIES_CALLOUT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["no"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_QDELINE_TIME_SERIES_ENABLE_CALLOUT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["avg","min","max"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_QDELINE_WIDGET_ENABLE_RANKING';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_QDELINE_WIDGET_TOP_N_CONFIG';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='none';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_ENABLE_RANKING';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_KEY_METRICS';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{"keyMetricsNameList":[],"otherKeyMetricsNameList":[]}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_OTHER_METRICS_CRITERIA';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'[]';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_SHARE_SAME_YAXIS';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_SHOW_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_SHOW_KEY_NAME_SELECTION';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'["no"]';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_SHOW_STACKED';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='off';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_TILE_SHOW_THRESHOLD';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_STACKEDBAR_WIDGET_TOP_N_CONFIG';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_TREEMAP_DISPLAY_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["insights"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_TREEMAP_TOP_N_ROWS';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='5000';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_TREEMAP_WIDGET_ENABLE_RANKING';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_TREEMAP_WIDGET_TOP_N_CONFIG';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='none';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_GAUGE_COLOR_VALUE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='#84bbe6';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_GAUGE_MAX_VALUE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='100';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_GAUGE_SELECTED_TILE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='emcta-tile-circular';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_GAUGE_SHOW_SPARK_CHART';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_GAUGE_THRESHOLD_CRITERION';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'[]';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_GAUGE_THRESHOLD_VALUE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='100';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LABEL_SELECTED_TILE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='emcta-tile-label';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LABEL_SHOW_SPARK_CHART';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LINE_CHART_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='none';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LINE_CHART_SELECTED_TILE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='emcta-tile-line';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LINE_CHART_SHOW_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LINE_CHART_SHOW_STACKED';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='on';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_LINE_CHART_TILE_SHOW_THRESHOLD';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_METRIC_TABLE_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='none';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_METRIC_TABLE_SHOW_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_SELECTED_TILE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='emcta-tile-label';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_SHOW_CALLOUT';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_SHOW_PERCENT_CHANGE';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_SHOW_SPARK_CHART';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TA_WIDGET_TILE_SHOW_THRESHOLD';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='false';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_AREA_CALLOUT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["avg","min","max"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_AREA_DISPLAY_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["insights"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_AREA_ENABLE_CALLOUT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["no"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_AREA_TIME_PERIOD_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='744';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_AREA_WIDGET_ENABLE_RANKING';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='true';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_AREA_WIDGET_TOP_N_CONFIG';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_CALLOUT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["avg","min","max"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_DISPLAY_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["insights"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_ENABLE_CALLOUT_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='["no"]';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_REFERENCE_LINE_NAME_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='""';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_REFERENCE_LINE_OPTION_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='"nameValue"';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_REFERENCE_LINE_VALUE_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TIME_SERIES_TIME_PERIOD_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='744';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='TOP_N_ROWS';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='50';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='VISUALIZATION_TYPE_KEY';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='LABEL';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=5004;
  V_NAME                  :='WIDGET_VISUAL';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCACMAP0DAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAo'||
'AKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPGPF/wy8H+O/HVpqkvi7XdI8X+GNN07UJdN8Ma7pNjqdpp2peGPjN4C8PaxdQvp15rmlpJH8Q/H9xoWrWNzphuPEHh22eC4uItD1OxuQB/w0+Di/DaHQIz8UvjJ8QJNB0vxZpf2j4l+OpPE82tf8JZrOgawdQ19I9O0621HVPDn9gLpXhO8FvAdF0bWNfskSc6pJKgB7JQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAFVbCxS+l1NLO0XUp7S3sJ9QW3hW+msbSa5uLWzluwgnktLae9vJ7e3eRoYZru5ljRXnlZwC1QAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB4943+EXhbx98QPAfjq917xDpPi74Y2Hie30T/AIR7UdLtWTSfH9iul6xHqEN3pWoXkKX8miWM9jqmnz6ZqcE2hz6fZ6iujan4r0nWwDj/AA9+zXpnhhfCMWl/F347x2vhS58a38tk3xBRbPxdqnjvWPEevavqvjWC30SBdf1G31PxNfXWnXLfZjFc29hfXS3mowSXkwBW0f8AZf0LQPDOm+FdJ+KfxtsLDRPhP4f+D+gXNn43srLUvD+geH7pbhdb0G7sfD9t/ZHi3V4INP0zWtYsY'||
'4IrrS9I0ezgsbRdMtGjAPpqgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoArJZWcd5PqKWlsmoXVtaWV1fJBEt5c2dhLez2NpPdBBPNbWU+pajNaQSO0VtLf3skKI91OZACzQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB4L8S/wBnzwN8UPHHhDxzrWreKNH8SeEJdCv9LPhrVrHTEvrnwn4jTXNEvNTjuNLvrq8OlQar4u8LokVxBanw18SvGtjPC97qel6hpIBj3v7Mvh3VvD9z4f134k/GnxDFdaR8TtBm1DXPH8mo6jLpHxUj8QQazptz52mHT9Q0/RLPxA1n4X07U9PvdP0yLQ/Ck91a6hfeGNGu7QArX/7MGk3Fj4h0zS/jB8f/AAnp2ueMB4zs7Dwb8SW8M2fhO5j0S40qHQPCVrpmjxQaX4PXUZx4suvC88d7pWseJovP16DVdKub/SLwAs/EH9nOx8VeOdU+I/hHxfqvw28Y+J9G0Pw74y1rw3ZQ22o+IdE8JaH8SIvC1r/bOkXWgeI7Ka28YeM/CvibXpjrd3F4j0n4Y+GPBU1tZ6Hd6s90Aeg/D34X/wDCvtW8caufiH8UPG7eN9Zi1g6b8QfFp8SaP4QERvGGkeBrD7DZr4f0VzeN5tmZLySRbezR7krbRgAHqNABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAUU0zTYtSudZj0+xj1i9sbHTLzVUtLdNSu9N0y41C603T7m+WMXU9jp91q2q3NjaSyvb2lxqeoTQRxyXty0oBeoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAK'||
'ACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//Z';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID                :=4005;
  V_NAME                     :='CARD_DEF_omc_workflow_submission';
  V_OWNER                    :='ORACLE';
  V_CREATION_DATE            :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFICATION_DATE   :=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_LAST_MODIFIED_BY         :='ORACLE';
  V_DESCRIPTION              :=null;
  V_FOLDER_ID                :=6;
  V_CATEGORY_ID              :=5;
  V_NAME_NLSID               :=null;
  V_NAME_SUBSYSTEM           :=null;
  V_DESCRIPTION_NLSID        :=null;
  V_DESCRIPTION_SUBSYSTEM    :=null;
  V_SYSTEM_SEARCH            :=1;
  V_EM_PLUGIN_ID             :=null;
  V_IS_LOCKED                :=0;
  V_UI_HIDDEN                :=0;
  V_DELETED                  :=0;
  V_IS_WIDGET                :=1;
  V_METADATA                 :=null;
  V_SEARCH_STR               :=null;
  V_WIDGET_SOURCE       :=null;
  V_WIDGET_GROUP_NAME        :=null;
  V_WIDGET_ICON              :=null;
  V_WIDGET_KOC_NAME          :=null;
  V_WIDGET_VIEWMODEL         :=null;
  V_WIDGET_TEMPLATE          :=null;
  V_WIDGET_SUPPORT_TIME_CONTROL      :=null;
  V_DASHBOARD_INELIGIBLE     :=null;
  V_PROVIDER_NAME            :=null;
  V_PROVIDER_VERSION         :=null;
  V_PROVIDER_ASSET_ROOT      :=null;
  V_WIDGET_LINKED_DASHBOARD  :=0;
  V_WIDGET_DEFAULT_WIDTH     :=0;
  V_WIDGET_DEFAULT_HEIGHT    :=0;
  Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,
                                    NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,
                                    UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID,METADATA_CLOB,SEARCH_DISPLAY_STR,
                                    WIDGET_SOURCE,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_KOC_NAME,WIDGET_VIEWMODEL,WIDGET_TEMPLATE,
                                    WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD,WIDGET_DEFAULT_WIDTH,WIDGET_DEFAULT_HEIGHT,
                                    DASHBOARD_INELIGIBLE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT)
	values (V_SEARCH_ID,V_NAME,V_OWNER,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_DESCRIPTION,V_FOLDER_ID,V_CATEGORY_ID,V_NAME_NLSID,V_NAME_SUBSYSTEM,
         V_DESCRIPTION_NLSID,V_DESCRIPTION_SUBSYSTEM,V_SYSTEM_SEARCH,V_EM_PLUGIN_ID,V_IS_LOCKED,V_UI_HIDDEN,V_DELETED,V_IS_WIDGET,V_TENANT_ID,V_METADATA,V_SEARCH_STR,
         V_WIDGET_SOURCE,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_KOC_NAME,V_WIDGET_VIEWMODEL,V_WIDGET_TEMPLATE,
         V_WIDGET_SUPPORT_TIME_CONTROL,V_WIDGET_LINKED_DASHBOARD,V_WIDGET_DEFAULT_WIDTH,V_WIDGET_DEFAULT_HEIGHT,
         V_DASHBOARD_INELIGIBLE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT);
  V_SEARCH_ID             :=4005;
  V_NAME                  :='cardef';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=2;
  V_PARAM_VALUE_STR       :=null;
  V_PARAM_VALUE_CLOB      :=
'{"id":null,"entityType":"omc_workflow_submission","widgets":null,"widgetRefs":[{"id":"5004","parameters":null,"entityCapability":null,"accessControl":{"userPrivilege":"VIEW_ANY_SUBMISSION"}}]}';

  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=4005;
  V_NAME                  :='entityType';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='omc_workflow_submission';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=4005;
  V_NAME                  :='isCardDef';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='true';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);


  V_SEARCH_ID             :=4005;
  V_NAME                  :='version';
  V_PARAM_ATTRIBUTES      :=null;
  V_PARAM_TYPE            :=1;
  V_PARAM_VALUE_STR       :='1001';
  V_PARAM_VALUE_CLOB      :=null;
  INSERT INTO EMS_ANALYTICS_SEARCH_PARAMS(SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) 
  VALUES(V_SEARCH_ID,V_NAME,V_PARAM_ATTRIBUTES,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_CLOB,V_TENANT_ID);    
    
      insert into EMS_ANALYTICS_LAST_ACCESS(OBJECT_ID,ACCESSED_BY,OBJECT_TYPE,ACCESS_DATE,TENANT_ID)
      select SEARCH_ID,'ORACLE',2,SYS_EXTRACT_UTC(SYSTIMESTAMP),V_TENANT_ID from EMS_ANALYTICS_SEARCH 
      where search_id in (5004,4005) and TENANT_ID =V_TENANT_ID;
  
  V_SEARCH_ID             :=4000;
  V_NAME                  :='cardef';
  V_PARAM_VALUE_CLOB      :='{"id":null,"entityType":"omc_weblogic_j2eeserver","widgets":null,"widgetRefs":[{"id":3030,"parameters":null,"entityCapability":null,"accessControl":{"userPrivilege":"USE_TARGET_ANALYTICS"}}]}';
  UPDATE EMS_ANALYTICS_SEARCH_PARAMS
  SET PARAM_VALUE_CLOB=V_PARAM_VALUE_CLOB 
  WHERE SEARCH_ID=V_SEARCH_ID AND NAME=V_NAME AND TENANT_ID=V_TENANT_ID;  
  
  V_SEARCH_ID             :=4001;
  V_NAME                  :='cardef';
  V_PARAM_VALUE_CLOB      :='{"id":null,"entityType":"omc_oracle_db","widgets":null,"widgetRefs":[{"id":3029,"parameters":null,"entityCapability":null,"accessControl":{"userPrivilege":"USE_TARGET_ANALYTICS"}}]}';
  UPDATE EMS_ANALYTICS_SEARCH_PARAMS
  SET PARAM_VALUE_CLOB=V_PARAM_VALUE_CLOB 
  WHERE SEARCH_ID=V_SEARCH_ID AND NAME=V_NAME AND TENANT_ID=V_TENANT_ID;    

  V_SEARCH_ID             :=4002;
  V_NAME                  :='cardef';
  V_PARAM_VALUE_CLOB      :='{"id":null,"entityType":"omc_host","widgets":null,"widgetRefs":[{"id":3031,"parameters":null,"entityCapability":null,"accessControl":{"userPrivilege":"USE_TARGET_ANALYTICS"}}]}';
  UPDATE EMS_ANALYTICS_SEARCH_PARAMS
  SET PARAM_VALUE_CLOB=V_PARAM_VALUE_CLOB 
  WHERE SEARCH_ID=V_SEARCH_ID AND NAME=V_NAME AND TENANT_ID=V_TENANT_ID;
 
  V_SEARCH_ID             :=4003;
  V_NAME                  :='cardef';
  V_PARAM_VALUE_CLOB      :='{"id":null,"entityType":"omc_entity","widgets":null,"widgetRefs":[{"id":2027,"parameters":null,"entityCapability":{"type":"SERVICE: Log Analytics","name":"LOG_COLLECTED"},"accessControl":{"userPrivilege":"SEARCH_LOGS"}}]}';
  UPDATE EMS_ANALYTICS_SEARCH_PARAMS
  SET PARAM_VALUE_CLOB=V_PARAM_VALUE_CLOB 
  WHERE SEARCH_ID=V_SEARCH_ID AND NAME=V_NAME AND TENANT_ID=V_TENANT_ID;

      DBMS_OUTPUT.PUT_LINE('2 new TA OOB widgets and 2 target card mapping have been added successfully.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('2 new TA OOB widgets and 2 target card mapping have been added before, no need to add again.');
    END IF;
    IF (V_TID<>-1) THEN
        EXIT;
    END IF;
  END LOOP;
  IF TENANT_CURSOR%ISOPEN THEN
    CLOSE TENANT_CURSOR;
  END IF;

  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Failed to add 2 new TA OOB widgets and 2 target card mapping  due to '||SQLERRM);   
  RAISE;  
END;
/
