Rem
Rem    DDL change during upgrade
Rem    MODIFIED   (MM/DD/YY)
Rem    REX     09/06/2016 - created, REMOVE COLUMNS IN EMS_ANALYTICS_SEARCH

SET FEEDBACK ON
SET SERVEROUTPUT ON
DECLARE
  v_count     INTEGER;
BEGIN
	--delete obsolete column 'NAME_NLSID'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='NAME_NLSID';
	IF v_count>0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: DELETING COLUMN:NAME_NLSID IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP COLUMN NAME_NLSID';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.NAME_NLSID is not exists, no deletion is needed');
	END IF;
	
	--delete obsolete column 'NAME_SUBSYSTEM'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='NAME_SUBSYSTEM';
	IF v_count>0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: DELETING COLUMN:NAME_SUBSYSTEM IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP COLUMN NAME_SUBSYSTEM';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.NAME_SUBSYSTEM is not exists, no deletion is needed');
	END IF;
	
	--delete obsolete column 'DESCRIPTION_NLSID'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='DESCRIPTION_NLSID';
	IF v_count>0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: DELETING COLUMN:DESCRIPTION_NLSID IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP COLUMN DESCRIPTION_NLSID';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.DESCRIPTION_NLSID is not exists, no deletion is needed');
	END IF;
	
	--delete obsolete column 'DESCRIPTION_SUBSYSTEM'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='DESCRIPTION_SUBSYSTEM';
	IF v_count>0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: DELETING COLUMN:DESCRIPTION_SUBSYSTEM IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP COLUMN DESCRIPTION_SUBSYSTEM';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.DESCRIPTION_SUBSYSTEM is not exists, no deletion is needed');
	END IF;
	
	--delete obsolete column 'EM_PLUGIN_ID'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='EM_PLUGIN_ID';
	IF v_count>0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: DELETING COLUMN:EM_PLUGIN_ID IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH DROP COLUMN EM_PLUGIN_ID';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.EM_PLUGIN_ID is not exists, no deletion is needed');
	END IF;
	
	EXCEPTION
	  WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('Failed to delete columns in EMS_ANALYTICS_SEARCH due to '||SQLERRM);
		RAISE;
END;
/

