Rem
Rem    DDL change during upgrade
Rem    MODIFIED   (MM/DD/YY)
Rem    REX     09/06/2016 - created, ADD COLUMNS IN EMS_ANALYTICS_SEARCH TEMPORARY FOR TENANT ONBOARD

SET FEEDBACK ON
SET SERVEROUTPUT ON
DECLARE
  v_count     INTEGER;
BEGIN
	--add obsolete column 'NAME_NLSID'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='NAME_NLSID';
	IF v_count=0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:NAME_NLSID IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD NAME_NLSID VARCHAR2(256)';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.NAME_NLSID is existing');
	END IF;
	
	--add obsolete column 'NAME_SUBSYSTEM'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='NAME_SUBSYSTEM';
	IF v_count=0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:NAME_SUBSYSTEM IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD NAME_SUBSYSTEM VARCHAR2(64)';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.NAME_SUBSYSTEM is existing');
	END IF;
	
	--add obsolete column 'DESCRIPTION_NLSID'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='DESCRIPTION_NLSID';
	IF v_count=0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:DESCRIPTION_NLSID IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD DESCRIPTION_NLSID VARCHAR2(256)';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.DESCRIPTION_NLSID is existing');
	END IF;
	
	--add obsolete column 'DESCRIPTION_SUBSYSTEM'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='DESCRIPTION_SUBSYSTEM';
	IF v_count=0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:DESCRIPTION_SUBSYSTEM IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD DESCRIPTION_SUBSYSTEM VARCHAR2(64)';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.DESCRIPTION_SUBSYSTEM is existing');
	END IF;
	
	--add obsolete column 'EM_PLUGIN_ID'
	SELECT count(*) into v_count from user_tab_columns WHERE table_name='EMS_ANALYTICS_SEARCH' AND column_name='EM_PLUGIN_ID';
	IF v_count=0 THEN
		DBMS_OUTPUT.PUT_LINE('Schema object: ADDING COLUMN:EM_PLUGIN_ID IN EMS_ANALYTICS_SEARCH TABLE');
		EXECUTE IMMEDIATE 'ALTER TABLE EMS_ANALYTICS_SEARCH ADD EM_PLUGIN_ID VARCHAR2(64)';
	ELSE
		DBMS_OUTPUT.PUT_LINE('Schema object: EMS_ANALYTICS_SEARCH.EM_PLUGIN_ID is existing');
	END IF;
	
	EXCEPTION
	  WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('Failed to delete columns in EMS_ANALYTICS_SEARCH due to '||SQLERRM);
		RAISE;
END;
/

