Rem
Rem emaas_savesearch_seed_data_la.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_savesearch_seed_data.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for category and default folder
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    Miao     06/21/16 - Created
Rem

DEFINE TENANT_ID ='&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
  V_COUNT number;
BEGIN

SELECT COUNT(1) INTO V_COUNT from EMS_ANALYTICS_SEARCH where TENANT_ID='&TENANT_ID' AND SEARCH_ID=2027;
IF (V_COUNT<=0) THEN
  Insert into EMS_ANALYTICS_SEARCH (SEARCH_ID,NAME,OWNER,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,DESCRIPTION,FOLDER_ID,CATEGORY_ID,NAME_NLSID,NAME_SUBSYSTEM,DESCRIPTION_NLSID,DESCRIPTION_SUBSYSTEM,SYSTEM_SEARCH,EM_PLUGIN_ID,IS_LOCKED,SEARCH_DISPLAY_STR,UI_HIDDEN,DELETED,IS_WIDGET,TENANT_ID) 
  values (2027,'Log Records For Last 15 Minutes','ORACLE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP),'ORACLE','Time-based histogram of log entries.',2,1,null,null,null,null,1,null,0, '*',0,0,1,'&TENANT_ID');
  Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2027,'VISUALIZATION_TYPE_KEY',null,1,'HISTOGRAM',null,'&TENANT_ID');
  Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2027,'WIDGET_KOC_NAME',null,1,'emcla-visualization',null,'&TENANT_ID');
  Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2027,'WIDGET_TEMPLATE',null,1,'/html/search/widgets/visualizationWidget.html',null,'&TENANT_ID');
  Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2027,'WIDGET_VIEWMODEL',null,1,'/js/viewmodel/search/widget/VisualizationWidget.js',null,'&TENANT_ID');
  Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2027,'WIDGET_SUPPORT_TIME_CONTROL',null,1,'1',null,'&TENANT_ID');
  Insert into EMS_ANALYTICS_SEARCH_PARAMS (SEARCH_ID,NAME,PARAM_ATTRIBUTES,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_CLOB,TENANT_ID) values (2027,'time',null,1,'{"type":"relative","duration":15,"timeUnit":"MINUTE"}',null,'&TENANT_ID');
  commit;
  DBMS_OUTPUT.PUT_LINE('New LA WIDGET for Target Card has been added successfully');  
ELSE
  DBMS_OUTPUT.PUT_LINE('New LA WIDGET for Target Card has been added before, no need to add again');  
END IF;
  
EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Failed to add new LA WIDGET for Target Card due to '||SQLERRM);   
  RAISE;  
END;
/

