  SET FEEDBACK ON
  SET SERVEROUTPUT ON
  DEFINE TENANT_ID ='&1'
DECLARE
v_count     INTEGER;
V_TENANT_ID NUMBER(38,0);
V_TID NUMBER(38,0) := '&TENANT_ID';

CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_ANALYTICS_SEARCH ORDER BY TENANT_ID;

BEGIN
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;  
     
    SELECT COUNT(*) INTO v_count FROM EMS_ANALYTICS_SEARCH
        WHERE SEARCH_ID IN (5000, 5001, 5002, 5003, 5004, 5013, 5014) AND DASHBOARD_INELIGIBLE = 1 AND TENANT_ID = V_TENANT_ID;
    IF v_count > 0 THEN
       DBMS_OUTPUT.PUT_LINE('COS Widget has been updated before, no need to do it ! for tenant:'||V_TENANT_ID);
    ELSE
        UPDATE EMS_ANALYTICS_SEARCH SET DASHBOARD_INELIGIBLE = 1
            WHERE SEARCH_ID IN (5000, 5001, 5002, 5003, 5004, 5013, 5014) AND TENANT_ID = V_TENANT_ID;
       DBMS_OUTPUT.PUT_LINE('COS Widget has been updated successfully for tenant:'||V_TENANT_ID);
    END IF;
     IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  commit;
  DBMS_OUTPUT.PUT_LINE('Upgrade is done');    
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Failed to update the sql due to '||SQLERRM);
      RAISE;
  END;
  /
